{"sections":[],"metadata":{"required":true,"modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"cancelButton"}],"roleHeading":"Instance Property","externalID":"c:@M@TalkSDK@objc(pl)CallErrorView(py)cancelButton","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelButton","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"},{"text":"!","kind":"text"}],"title":"cancelButton"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callerrorview\/cancelbutton"]},{"paths":["\/documentation\/talksdk\/callerrorview\/cancelbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Cancel button. Tapping will close the Call Screen.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/cancelButton"},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView/cancelButton":{"url":"\/documentation\/talksdk\/callerrorview\/cancelbutton","navigatorTitle":[{"kind":"identifier","text":"cancelButton"}],"required":true,"title":"cancelButton","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/cancelButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cancelButton","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"text":"!","kind":"text"}],"abstract":[{"type":"text","text":"Cancel button. Tapping will close the Call Screen."}],"role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView":{"title":"CallErrorView","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView","url":"\/documentation\/talksdk\/callerrorview","navigatorTitle":[{"text":"CallErrorView","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Represent the error view with "},{"code":"retry","type":"codeVoice"},{"type":"text","text":" and "},{"code":"cancel","type":"codeVoice"},{"text":" buttons.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallErrorView"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"cancelButton","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"cancelButton","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"kind":"text","text":" * "},{"text":"cancelButton","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1cancelButton\/title","op":"replace","value":"cancelButton"},{"value":[{"text":"cancelButton","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1cancelButton\/fragments"},{"value":"CallErrorView","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/title"},{"value":[{"kind":"identifier","text":"CallErrorView"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/fragments"}]}]}