{"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView"]]},"metadata":{"required":true,"modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"text":"titleLabel","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@TalkSDK@objc(pl)CallErrorView(py)titleLabel","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"titleLabel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"title":"titleLabel"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"! { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callerrorview\/titlelabel"]},{"paths":["\/documentation\/talksdk\/callerrorview\/titlelabel"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/titleLabel","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView/titleLabel":{"title":"titleLabel","type":"topic","required":true,"kind":"symbol","url":"\/documentation\/talksdk\/callerrorview\/titlelabel","role":"symbol","navigatorTitle":[{"text":"titleLabel","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/titleLabel","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"titleLabel","kind":"identifier"},{"kind":"text","text":": "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView":{"title":"CallErrorView","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView","url":"\/documentation\/talksdk\/callerrorview","navigatorTitle":[{"text":"CallErrorView","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Represent the error view with "},{"code":"retry","type":"codeVoice"},{"type":"text","text":" and "},{"code":"cancel","type":"codeVoice"},{"text":" buttons.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallErrorView"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"titleLabel","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"titleLabel"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"titleLabel","kind":"identifier"}],"languages":["occ"]}]}},{"value":"titleLabel","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1titleLabel\/title"},{"value":[{"text":"titleLabel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1titleLabel\/fragments"},{"value":"CallErrorView","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/title"},{"value":[{"kind":"identifier","text":"CallErrorView"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/fragments","op":"replace"}]}]}