{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/talksdk\/callstatus\/connecting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callstatus\/connecting"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/connecting","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","title":"CallStatus.connecting","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connecting"}],"modules":[{"name":"TalkSDK"}],"externalID":"c:@M@TalkSDK@E@CallStatus@CallStatusConnecting","role":"symbol","navigatorTitle":[{"text":"CallStatusConnecting","kind":"identifier"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"The call is connecting."}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/connecting":{"title":"CallStatus.connecting","url":"\/documentation\/talksdk\/callstatus\/connecting","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connecting","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The call is connecting."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/connecting","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallStatusConnecting"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallStatus","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatus"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","url":"\/documentation\/talksdk\/callstatus","role":"symbol","title":"CallStatus","kind":"symbol","abstract":[{"type":"text","text":"Represents all possible states of the call."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"CallStatusConnecting","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallStatusConnecting"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CallStatusConnecting"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1connecting\/title","op":"replace","value":"CallStatusConnecting"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1connecting\/fragments","value":[{"kind":"identifier","text":"CallStatusConnecting"}],"op":"replace"},{"value":"CallStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/fragments","value":[{"kind":"identifier","text":"CallStatus"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}