{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/connected"},"kind":"symbol","variants":[{"paths":["\/documentation\/talksdk\/callstatus\/connected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callstatus\/connected"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The call has been connected."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus"]]},"metadata":{"roleHeading":"Case","externalID":"c:@M@TalkSDK@E@CallStatus@CallStatusConnected","symbolKind":"case","role":"symbol","title":"CallStatus.connected","navigatorTitle":[{"text":"CallStatusConnected","kind":"identifier"}],"modules":[{"name":"TalkSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallStatus","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatus"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","url":"\/documentation\/talksdk\/callstatus","role":"symbol","title":"CallStatus","kind":"symbol","abstract":[{"type":"text","text":"Represents all possible states of the call."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/connected":{"type":"topic","url":"\/documentation\/talksdk\/callstatus\/connected","title":"CallStatus.connected","abstract":[{"text":"The call has been connected.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallStatusConnected"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/connected","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"CallStatusConnected","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallStatusConnected"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"CallStatusConnected","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/title","value":"CallStatus","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CallStatus"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/fragments"},{"value":"CallStatusConnected","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1connected\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1connected\/fragments","value":[{"kind":"identifier","text":"CallStatusConnected"}],"op":"replace"}]}]}