{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/disconnected","interfaceLanguage":"swift"},"abstract":[{"text":"The call has disconnected.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callstatus\/disconnected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callstatus\/disconnected"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disconnected"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"role":"symbol","modules":[{"name":"TalkSDK"}],"title":"CallStatus.disconnected","navigatorTitle":[{"kind":"identifier","text":"CallStatusDisconnected"}],"roleHeading":"Case","externalID":"c:@M@TalkSDK@E@CallStatus@CallStatusDisconnected","symbolKind":"case"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/disconnected":{"kind":"symbol","abstract":[{"type":"text","text":"The call has disconnected."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/disconnected","navigatorTitle":[{"text":"CallStatusDisconnected","kind":"identifier"}],"title":"CallStatus.disconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"url":"\/documentation\/talksdk\/callstatus\/disconnected","type":"topic","role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallStatus","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatus"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","url":"\/documentation\/talksdk\/callstatus","role":"symbol","title":"CallStatus","kind":"symbol","abstract":[{"type":"text","text":"Represents all possible states of the call."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"CallStatusDisconnected","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CallStatusDisconnected","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"CallStatusDisconnected"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1disconnected\/title","op":"replace","value":"CallStatusDisconnected"},{"op":"replace","value":[{"text":"CallStatusDisconnected","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1disconnected\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/title","value":"CallStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/fragments","value":[{"kind":"identifier","text":"CallStatus"}],"op":"replace"}]}]}