{"abstract":[{"type":"text","text":"The call has been disconnected."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/failed"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"roleHeading":"Case","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"text":"CallStatusFailed","kind":"identifier"}],"role":"symbol","title":"CallStatus.failed","externalID":"c:@M@TalkSDK@E@CallStatus@CallStatusFailed","symbolKind":"case"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus"]]},"variants":[{"paths":["\/documentation\/talksdk\/callstatus\/failed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callstatus\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/failed":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/failed","abstract":[{"type":"text","text":"The call has been disconnected."}],"type":"topic","title":"CallStatus.failed","url":"\/documentation\/talksdk\/callstatus\/failed","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"navigatorTitle":[{"text":"CallStatusFailed","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallStatus","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatus"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","url":"\/documentation\/talksdk\/callstatus","role":"symbol","title":"CallStatus","kind":"symbol","abstract":[{"type":"text","text":"Represents all possible states of the call."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"CallStatusFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallStatusFailed"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"CallStatusFailed"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1failed\/title","value":"CallStatusFailed"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1failed\/fragments","value":[{"kind":"identifier","text":"CallStatusFailed"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/title","value":"CallStatus"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/fragments","value":[{"kind":"identifier","text":"CallStatus"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}