{"abstract":[{"type":"text","text":"Type of audio routing option."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AudioRoutingType","preciseIdentifier":"c:@M@TalkSDK@E@AudioRoutingType","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/talksdk\/audioroutingoption\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/audioroutingoption\/type"]}],"metadata":{"required":true,"modules":[{"name":"TalkSDK"}],"title":"type","externalID":"c:@M@TalkSDK@objc(pl)AudioRoutingOption(py)type","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AudioRoutingType","preciseIdentifier":"c:@M@TalkSDK@E@AudioRoutingType"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"symbolKind":"property","roleHeading":"Instance Property"},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption\/type"},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingOption/type":{"title":"type","required":true,"navigatorTitle":[{"text":"type","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption\/type","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioRoutingType","preciseIdentifier":"c:@M@TalkSDK@E@AudioRoutingType","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Type of audio routing option."}],"url":"\/documentation\/talksdk\/audioroutingoption\/type","kind":"symbol","type":"topic"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType":{"navigatorTitle":[{"kind":"identifier","text":"AudioRoutingType"}],"type":"topic","url":"\/documentation\/talksdk\/audioroutingtype","abstract":[{"text":"Describes type of an audio routing option.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioRoutingType","kind":"identifier"}],"title":"AudioRoutingType"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingOption":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AudioRoutingOption","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AudioRoutingOption"}],"abstract":[{"text":"Describes possible options for routing call’s audio input and output.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption","title":"AudioRoutingOption","url":"\/documentation\/talksdk\/audioroutingoption","role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"type","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType","preciseIdentifier":"c:@M@TalkSDK@E@AudioRoutingType","text":"AudioRoutingType"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"value":"AudioRoutingType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AudioRoutingType"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption\/title","value":"AudioRoutingOption","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption\/fragments","value":[{"kind":"identifier","text":"AudioRoutingOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}