{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Allow Button that opens an alert asking user about microphone permission. In case permission is already granted, calls "},{"type":"codeVoice","code":"requestPermissionCompletion"},{"text":".","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen"]]},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"role":"symbol","externalID":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen(py)allowButton","symbolKind":"property","navigatorTitle":[{"text":"allowButton","kind":"identifier"}],"title":"allowButton","required":true,"modules":[{"name":"TalkSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"kind":"text","text":"! { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/microphonepermissionscreen\/allowbutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/microphonepermissionscreen\/allowbutton"]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/allowButton","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen/allowButton":{"title":"allowButton","url":"\/documentation\/talksdk\/microphonepermissionscreen\/allowbutton","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowButton","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"required":true,"type":"topic","abstract":[{"text":"Allow Button that opens an alert asking user about microphone permission. In case permission is already granted, calls ","type":"text"},{"type":"codeVoice","code":"requestPermissionCompletion"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/allowButton","role":"symbol","navigatorTitle":[{"text":"allowButton","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MicrophonePermissionScreen","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MicrophonePermissionScreen","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen","url":"\/documentation\/talksdk\/microphonepermissionscreen","role":"symbol","title":"MicrophonePermissionScreen","kind":"symbol","abstract":[{"type":"text","text":"Screen handling microphone permission configuration."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"allowButton","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"allowButton","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"allowButton","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1allowButton\/title","value":"allowButton","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1allowButton\/fragments","op":"replace","value":[{"text":"allowButton","kind":"identifier"}]},{"value":"MicrophonePermissionScreen","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/fragments","op":"replace","value":[{"kind":"identifier","text":"MicrophonePermissionScreen"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}