{"variants":[{"paths":["\/documentation\/talksdk\/audiooutput\/headset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/audiooutput\/headset"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"The call audio will be routed through the headset."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/headset","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"headset","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AudioOutputHeadset"}],"roleHeading":"Case","modules":[{"name":"TalkSDK"}],"title":"AudioOutput.headset","role":"symbol","externalID":"c:@M@TalkSDK@E@AudioOutput@AudioOutputHeadset"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"headset","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput":{"title":"AudioOutput","abstract":[{"type":"text","text":"Describes possible options for audio playback during the call."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AudioOutput","kind":"identifier"}],"navigatorTitle":[{"text":"AudioOutput","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/talksdk\/audiooutput","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput/headset":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/headset","abstract":[{"text":"The call audio will be routed through the headset.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headset","kind":"identifier"}],"title":"AudioOutput.headset","url":"\/documentation\/talksdk\/audiooutput\/headset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioOutputHeadset"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"AudioOutputHeadset","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"AudioOutputHeadset","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AudioOutputHeadset"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput\/title","op":"replace","value":"AudioOutput"},{"op":"replace","value":[{"kind":"identifier","text":"AudioOutput"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput\/fragments"},{"value":"AudioOutputHeadset","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput~1headset\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput~1headset\/fragments","value":[{"kind":"identifier","text":"AudioOutputHeadset"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}