{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/audiooutput"]},{"paths":["\/documentation\/talksdk\/audiooutput"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"TalkSDK"}],"roleHeading":"Enumeration","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioOutput","kind":"identifier"}],"symbolKind":"enum","title":"AudioOutput","navigatorTitle":[{"kind":"identifier","text":"AudioOutput"}],"externalID":"c:@M@TalkSDK@E@AudioOutput"},"abstract":[{"text":"Describes possible options for audio playback during the call.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/headset","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/speaker"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/Equatable-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.TalkSDK\/SQ","doc:\/\/com.zendesk.TalkSDK\/SH","doc:\/\/com.zendesk.TalkSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOutput"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput/init(rawValue:)":{"url":"\/documentation\/talksdk\/audiooutput\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/init(rawValue:)","title":"init(rawValue:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput/speaker":{"kind":"symbol","abstract":[{"text":"The call audio will be routed through the speakers.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"speaker","kind":"identifier"}],"title":"AudioOutput.speaker","url":"\/documentation\/talksdk\/audiooutput\/speaker","role":"symbol","navigatorTitle":[{"text":"AudioOutputSpeaker","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/speaker","type":"topic"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AudioOutput","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Describes possible options for audio playback during the call.","type":"text"}],"title":"AudioOutput","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput","navigatorTitle":[{"kind":"identifier","text":"AudioOutput"}],"type":"topic","kind":"symbol","url":"\/documentation\/talksdk\/audiooutput"},"doc://com.zendesk.TalkSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/talksdk\/audiooutput\/equatable-implementations","kind":"article","type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/Equatable-Implementations","role":"collectionGroup"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.TalkSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput/headset":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/headset","abstract":[{"text":"The call audio will be routed through the headset.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headset","kind":"identifier"}],"title":"AudioOutput.headset","url":"\/documentation\/talksdk\/audiooutput\/headset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioOutputHeadset"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/RawRepresentable-Implementations","kind":"article","type":"topic","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/talksdk\/audiooutput\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AudioOutput","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AudioOutput","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AudioOutput"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/headset","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/speaker"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioOutput"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AudioOutputSpeaker","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput~1speaker\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput~1speaker\/fragments","value":[{"text":"AudioOutputSpeaker","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput\/title","value":"AudioOutput","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput\/fragments","value":[{"text":"AudioOutput","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput~1headset\/title","op":"replace","value":"AudioOutputHeadset"},{"value":[{"text":"AudioOutputHeadset","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput~1headset\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}