{"topicSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/bluetooth","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/builtIn"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/Equatable-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/audioroutingtype"]},{"paths":["\/documentation\/talksdk\/audioroutingtype"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioRoutingType","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AudioRoutingType","kind":"identifier"}],"navigatorTitle":[{"text":"AudioRoutingType","kind":"identifier"}],"externalID":"c:@M@TalkSDK@E@AudioRoutingType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","title":"AudioRoutingType","modules":[{"name":"TalkSDK"}]},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.TalkSDK\/SQ","doc:\/\/com.zendesk.TalkSDK\/SH","doc:\/\/com.zendesk.TalkSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","abstract":[{"text":"Describes type of an audio routing option.","type":"text"}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType":{"navigatorTitle":[{"kind":"identifier","text":"AudioRoutingType"}],"type":"topic","url":"\/documentation\/talksdk\/audioroutingtype","abstract":[{"text":"Describes type of an audio routing option.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioRoutingType","kind":"identifier"}],"title":"AudioRoutingType"},"doc://com.zendesk.TalkSDK/SQ":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.TalkSDK/SH":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType/bluetooth":{"navigatorTitle":[{"text":"AudioRoutingTypeBluetooth","kind":"identifier"}],"type":"topic","url":"\/documentation\/talksdk\/audioroutingtype\/bluetooth","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/bluetooth","abstract":[{"type":"text","text":"Used for routing option using bluetooth connectivity."}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bluetooth","kind":"identifier"}],"title":"AudioRoutingType.bluetooth"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType/builtIn":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"builtIn","kind":"identifier"}],"abstract":[{"type":"text","text":"Used for routing option using built-in speakers and microphone."}],"navigatorTitle":[{"text":"AudioRoutingTypeBuiltIn","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"AudioRoutingType.builtIn","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/builtIn","type":"topic","url":"\/documentation\/talksdk\/audioroutingtype\/builtin"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/Equatable-Implementations","abstract":[],"type":"topic","url":"\/documentation\/talksdk\/audioroutingtype\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/RawRepresentable-Implementations","type":"topic","kind":"article","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/talksdk\/audioroutingtype\/rawrepresentable-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType/init(rawValue:)":{"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/talksdk\/audioroutingtype\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/init(rawValue:)"},"doc://com.zendesk.TalkSDK/SY":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","value":"AudioRoutingType","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioRoutingType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AudioRoutingType"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/bluetooth","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/builtIn"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioRoutingType"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType\/title","value":"AudioRoutingType","op":"replace"},{"value":[{"kind":"identifier","text":"AudioRoutingType"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType\/fragments"},{"value":"AudioRoutingTypeBluetooth","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType~1bluetooth\/title"},{"value":[{"kind":"identifier","text":"AudioRoutingTypeBluetooth"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType~1bluetooth\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType~1builtIn\/title","value":"AudioRoutingTypeBuiltIn"},{"value":[{"kind":"identifier","text":"AudioRoutingTypeBuiltIn"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType~1builtIn\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}