{"abstract":[{"type":"text","text":"A view controller that is displayed before making a call, used to ask the user about necessary permissions that need to be granted."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSCoding","doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.TalkSDK\/s7CVarArgP","doc:\/\/com.zendesk.TalkSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.TalkSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.TalkSDK\/SQ","doc:\/\/com.zendesk.TalkSDK\/SH","doc:\/\/com.zendesk.TalkSDK\/s8SendableP","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIContentContainer","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIStateRestoring","doc:\/\/com.zendesk.TalkSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallConfigurationViewController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"},"metadata":{"externalID":"c:@M@TalkSDK@objc(cs)CallConfigurationViewController","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallConfigurationViewController","kind":"identifier"}],"symbolKind":"class","title":"CallConfigurationViewController","role":"symbol","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CallConfigurationViewController"}]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/init(digitalLine:talk:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/cancelHandler","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/microphoneScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/recordingConsentScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/startCallHandler"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/viewDidLoad()","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/viewWillAppear(_:)"]}],"kind":"symbol","references":{"doc://com.zendesk.TalkSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIFocusEnvironment"},"doc://com.zendesk.TalkSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.TalkSDK\/s7CVarArgP"},"doc://com.zendesk.TalkSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UITraitEnvironment"},"doc://com.zendesk.TalkSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SH"},"doc://com.zendesk.TalkSDK/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(cs)UIViewController"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallConfigurationViewController"}],"navigatorTitle":[{"text":"CallConfigurationViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A view controller that is displayed before making a call, used to ask the user about necessary permissions that need to be granted."}],"type":"topic","url":"\/documentation\/talksdk\/callconfigurationviewcontroller","title":"CallConfigurationViewController","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/viewDidLoad()":{"url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/viewdidload()","abstract":[],"type":"topic","title":"viewDidLoad()","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/viewDidLoad()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/microphoneScreen":{"title":"microphoneScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/microphoneScreen","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/microphonescreen","navigatorTitle":[{"text":"microphoneScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Container for UI elements shown as Microphone permission screen. Enables customization of UI controls such as font, text colors, etc."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"microphoneScreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MicrophonePermissionScreen","preciseIdentifier":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen"}]},"doc://com.zendesk.TalkSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/cancelHandler":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelHandler","kind":"identifier"},{"kind":"text","text":": "},{"text":"CancelRequestHandler","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP20CancelRequestHandlera","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/cancelHandler","title":"cancelHandler","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/cancelhandler","role":"symbol","navigatorTitle":[{"text":"cancelHandler","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Handler that is called when end user cancels the configuration at any time."}],"kind":"symbol"},"doc://com.zendesk.TalkSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSObject"},"doc://com.zendesk.TalkSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SQ"},"doc://com.zendesk.TalkSDK/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.zendesk.TalkSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.TalkSDK/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSExtensionRequestHandling"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/startCallHandler":{"navigatorTitle":[{"text":"startCallHandler","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/startCallHandler","title":"startCallHandler","role":"symbol","type":"topic","abstract":[{"text":"Handler called after completing the configuration, it will be called with user’s ","type":"text"},{"code":"RecordingConsentAnswer","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/startcallhandler","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCallHandler"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera","text":"StartCallHandler","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.zendesk.TalkSDK/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIStateRestoring"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/viewWillAppear(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/viewwillappear(_:)","title":"viewWillAppear(_:)","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/viewWillAppear(_:)"},"doc://com.zendesk.TalkSDK/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIResponderStandardEditActions"},"doc://com.zendesk.TalkSDK/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.zendesk.TalkSDK/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIContentContainer"},"doc://com.zendesk.TalkSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/init(digitalLine:talk:)":{"title":"init(digitalLine:talk:)","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/init(digitalLine:talk:)","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/init(digitalline:talk:)","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"digitalLine","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"},{"text":", ","kind":"text"},{"text":"talk","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Talk","kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(cs)ZDKTalk"},{"text":")","kind":"text"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen":{"title":"CallConfigurationScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","url":"\/documentation\/talksdk\/callconfigurationscreen","navigatorTitle":[{"text":"CallConfigurationScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A screen presented before making a call, used to ask the user about necessary permissions that need to be granted."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationScreen"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/recordingConsentScreen":{"title":"recordingConsentScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/recordingConsentScreen","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/recordingconsentscreen","navigatorTitle":[{"text":"recordingConsentScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Container for UI elements shown as Recording Consent screen. Enables customization of UI controls such as font, text colors, etc.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentScreen"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen","kind":"typeIdentifier","text":"RecordingConsentScreen"}]},"doc://com.zendesk.TalkSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIAppearanceContainer"},"doc://com.zendesk.TalkSDK/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/s8SendableP"},"doc://com.zendesk.TalkSDK/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSCoding"},"doc://com.zendesk.TalkSDK/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/5UIKit23UITraitChangeObservableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"CallConfigurationViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallConfigurationViewController"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CallConfigurationViewController","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/cancelHandler","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/microphoneScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/recordingConsentScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/startCallHandler"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/viewDidLoad()","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/viewWillAppear(_:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"CallConfigurationViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/title","value":"CallConfigurationViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/fragments","value":[{"text":"CallConfigurationViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1microphoneScreen\/title","value":"microphoneScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1microphoneScreen\/fragments","value":[{"text":"microphoneScreen","kind":"identifier"}]},{"value":"cancelHandler","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1cancelHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1cancelHandler\/fragments","value":[{"kind":"identifier","text":"cancelHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1startCallHandler\/title","value":"startCallHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1startCallHandler\/fragments","value":[{"text":"startCallHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1viewWillAppear(_:)\/title","op":"replace","value":"viewWillAppear:"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1viewWillAppear(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/title","value":"CallConfigurationScreen","op":"replace"},{"value":[{"text":"CallConfigurationScreen","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/fragments","op":"replace"},{"op":"replace","value":"recordingConsentScreen","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1recordingConsentScreen\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1recordingConsentScreen\/fragments","value":[{"kind":"identifier","text":"recordingConsentScreen"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}