{"abstract":[{"text":"Represent the timer view with a label showing call’s duration.","type":"text"}],"variants":[{"paths":["\/documentation\/talksdk\/calltimerview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/calltimerview"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView\/timerLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView\/titleLabel"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallTimerView","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"The view is shown when a call is in progress with the title "},{"type":"codeVoice","code":"Call in progress"},{"type":"text","text":" and an automatically updated timer label showing call’s duration in seconds."},{"text":" ","type":"text"},{"type":"text","text":"On that screen you can change the font, text colors, background color, etc."}],"type":"paragraph"},{"style":"important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"You cannot change layout of elements. In case you need your own layout setup, use other SDK API methods and build your own Call View.","type":"text"}]}],"name":"Important"}]}],"metadata":{"externalID":"c:@M@TalkSDK@objc(pl)CallTimerView","modules":[{"name":"TalkSDK"}],"title":"CallTimerView","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallTimerView","kind":"identifier"}],"symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","navigatorTitle":[{"text":"CallTimerView","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallTimerView/timerLabel":{"title":"timerLabel","url":"\/documentation\/talksdk\/calltimerview\/timerlabel","navigatorTitle":[{"text":"timerLabel","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"timerLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView\/timerLabel","kind":"symbol","role":"symbol","required":true,"type":"topic","abstract":[{"text":"Label displaying call duration in seconds. Refreshed every second.","type":"text"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallTimerView":{"navigatorTitle":[{"text":"CallTimerView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/talksdk\/calltimerview","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallTimerView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView","type":"topic","abstract":[{"type":"text","text":"Represent the timer view with a label showing call’s duration."}],"title":"CallTimerView"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallTimerView/titleLabel":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"titleLabel","kind":"identifier"},{"kind":"text","text":": "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView\/titleLabel","role":"symbol","kind":"symbol","title":"titleLabel","url":"\/documentation\/talksdk\/calltimerview\/titlelabel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","value":"CallTimerView","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"CallTimerView"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallTimerView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView\/timerLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView\/titleLabel"]}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallTimerView"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"timerLabel","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView~1timerLabel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView~1timerLabel\/fragments","value":[{"text":"timerLabel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView\/title","value":"CallTimerView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView\/fragments","value":[{"kind":"identifier","text":"CallTimerView"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView~1titleLabel\/title","op":"replace","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]}]}]}