{"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"relationshipsSections":[{"title":"Conforming Types","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController"],"kind":"relationships","type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"abstract":[{"text":"A screen presented for an ongoing call.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallScreen","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This screen is shown during the all states of call ("},{"type":"codeVoice","code":"starting"},{"type":"text","text":", "},{"code":"in progress","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"fail"},{"type":"text","text":", etc)."},{"text":" ","type":"text"},{"type":"text","text":"It contains various sub-views related to displaying info depending on call state."}],"type":"paragraph"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"Labels with text under the buttons are not the part of button.","type":"text"}]}],"name":"Note"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callButtonsView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callErrorView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callLoadingView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callTimerView"]},{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/disconnect()"],"title":"Instance Methods"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"CallScreen"}],"externalID":"c:@M@TalkSDK@objc(pl)CallScreen","title":"CallScreen","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallScreen"}],"roleHeading":"Protocol","modules":[{"name":"TalkSDK"}],"symbolKind":"protocol","role":"symbol"},"variants":[{"paths":["\/documentation\/talksdk\/callscreen"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callscreen"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","url":"\/documentation\/talksdk\/callviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}],"kind":"symbol","abstract":[{"text":"A view controller displayed for an ongoing call.","type":"text"}],"role":"symbol","title":"CallViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallViewController","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen/callTimerView":{"title":"callTimerView","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callTimerView","url":"\/documentation\/talksdk\/callscreen\/calltimerview","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"callTimerView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallTimerView","text":"CallTimerView","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"callTimerView","kind":"identifier"}],"abstract":[{"type":"text","text":"Timer view displaying call duration."}],"kind":"symbol","type":"topic","required":true},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen":{"type":"topic","abstract":[{"text":"A screen presented for an ongoing call.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallScreen","kind":"identifier"}],"title":"CallScreen","url":"\/documentation\/talksdk\/callscreen","role":"symbol","navigatorTitle":[{"text":"CallScreen","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen/callErrorView":{"url":"\/documentation\/talksdk\/callscreen\/callerrorview","title":"callErrorView","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callErrorView","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callErrorView"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallErrorView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallErrorView"}],"navigatorTitle":[{"text":"callErrorView","kind":"identifier"}],"abstract":[{"type":"text","text":"Error view with retry and cancel buttons."}],"kind":"symbol","type":"topic","required":true},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen/callLoadingView":{"title":"callLoadingView","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callLoadingView","url":"\/documentation\/talksdk\/callscreen\/callloadingview","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callLoadingView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"CallLoadingView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallLoadingView"}],"navigatorTitle":[{"text":"callLoadingView","kind":"identifier"}],"abstract":[{"type":"text","text":"Loading view with activity indicator."}],"kind":"symbol","type":"topic","required":true},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen/callButtonsView":{"type":"topic","abstract":[{"text":"View containing call screen action buttons.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callButtonsView","url":"\/documentation\/talksdk\/callscreen\/callbuttonsview","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"callButtonsView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallButtonsView","text":"CallButtonsView"}],"role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"callButtonsView"}],"title":"callButtonsView"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen/disconnect()":{"type":"topic","abstract":[{"text":"Disconnects the call.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/disconnect()","url":"\/documentation\/talksdk\/callscreen\/disconnect()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"disconnect","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","required":true,"navigatorTitle":[{"text":"disconnect","kind":"identifier"}],"title":"disconnect()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"CallScreen","op":"replace","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallScreen"}],"op":"replace"},{"value":[{"kind":"identifier","text":"CallScreen"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callButtonsView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callErrorView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callLoadingView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callTimerView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/disconnect()"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallScreen"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/title","op":"replace","value":"CallViewController"},{"value":[{"text":"CallViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callTimerView\/title","value":"callTimerView","op":"replace"},{"value":[{"text":"callTimerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callTimerView\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/title","value":"CallScreen","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/fragments","value":[{"text":"CallScreen","kind":"identifier"}],"op":"replace"},{"value":"callErrorView","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callErrorView\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callErrorView\/fragments","op":"replace","value":[{"text":"callErrorView","kind":"identifier"}]},{"value":"callLoadingView","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callLoadingView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callLoadingView\/fragments","value":[{"text":"callLoadingView","kind":"identifier"}]},{"value":"callButtonsView","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callButtonsView\/title"},{"op":"replace","value":[{"text":"callButtonsView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callButtonsView\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1disconnect()\/title","op":"replace","value":"disconnect"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1disconnect()\/fragments","value":[{"kind":"text","text":"- "},{"text":"disconnect","kind":"identifier"}],"op":"replace"}]}]}