{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallConfigurationScreen"}],"title":"CallConfigurationScreen","externalID":"c:@M@TalkSDK@objc(pl)CallConfigurationScreen","modules":[{"name":"TalkSDK"}],"roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallConfigurationScreen"}]},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/cancelHandler","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/microphoneScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/recordingConsentScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/startCallHandler-c.property"]},{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/CancelRequestHandler","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/StartCallHandler-swift.typealias"],"title":"Type Aliases"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallConfigurationScreen","kind":"identifier"}]}]},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"text":"This screen internally manages all required checks: microphone permission access, digital line recording consent configuration etc., and presents the appropriate UI:","type":"text"},{"text":" ","type":"text"},{"code":"Microphone screen","type":"codeVoice"},{"text":" view is presented if microphone permission is not granted","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"Recording Consent Screen"},{"text":" view is presented only if ","type":"text"},{"type":"codeVoice","code":"Recording Consent"},{"text":" configuration for the provided ","type":"text"},{"code":"Digital Line","type":"codeVoice"},{"text":" is set to ","type":"text"},{"type":"codeVoice","code":"optIn"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"optOut"},{"type":"text","text":". If during fetching of the configuration error occurs, the "},{"type":"codeVoice","code":"Error View"},{"text":" will be shown.","type":"text"}],"type":"paragraph"},{"style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For better user experience before showing the "},{"type":"codeVoice","code":"Call Configuration Screen"},{"text":" you may want to check for agents availability by calling a ","type":"text"},{"type":"codeVoice","code":"Talk"},{"type":"text","text":" object method:"}]}],"type":"aside"},{"code":["func lineStatus(digitalLine: DigitalLine, completion: @escaping (LineStatusResult) -> Void)"],"type":"codeListing","syntax":null},{"type":"paragraph","inlineContent":[{"type":"text","text":"This screen will not be dismissed automatically. You need to provide the functionality on "},{"type":"codeVoice","code":"cancelHandler"},{"type":"text","text":" and "},{"code":"startCallHandler","type":"codeVoice"},{"type":"text","text":" handlers."}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"A screen presented before making a call, used to ask the user about necessary permissions that need to be granted."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"sections":[],"relationshipsSections":[{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"]}],"variants":[{"paths":["\/documentation\/talksdk\/callconfigurationscreen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callconfigurationscreen"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen":{"title":"CallConfigurationScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","url":"\/documentation\/talksdk\/callconfigurationscreen","navigatorTitle":[{"text":"CallConfigurationScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A screen presented before making a call, used to ask the user about necessary permissions that need to be granted."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationScreen"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/microphoneScreen":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"microphoneScreen","kind":"identifier"},{"kind":"text","text":": "},{"text":"MicrophonePermissionScreen","preciseIdentifier":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"microphoneScreen","kind":"identifier"}],"url":"\/documentation\/talksdk\/callconfigurationscreen\/microphonescreen","abstract":[{"type":"text","text":"Container for UI elements shown as Microphone permission screen. Enables customization of UI controls such as font, text colors, etc."}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/microphoneScreen","role":"symbol","type":"topic","title":"microphoneScreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/cancelHandler":{"abstract":[{"type":"text","text":"Handler that is called when end user cancels the configuration at any time."}],"type":"topic","role":"symbol","url":"\/documentation\/talksdk\/callconfigurationscreen\/cancelhandler","kind":"symbol","title":"cancelHandler","navigatorTitle":[{"text":"cancelHandler","kind":"identifier"}],"required":true,"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/cancelHandler","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelHandler","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CancelRequestHandler","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP20CancelRequestHandlera"},{"kind":"text","text":"?"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/StartCallHandler-swift.typealias":{"kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-swift.typealias","role":"symbol","title":"CallConfigurationScreen.StartCallHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"StartCallHandler","kind":"identifier"}],"abstract":[{"type":"text","text":"Handler type which is called when all call configuration steps are completed (microphone permission is granted and recording consent configuration is fetched and answered) and call can be made."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/StartCallHandler-swift.typealias","navigatorTitle":[{"text":"StartCallHandler","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/recordingConsentScreen":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentScreen"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen","text":"RecordingConsentScreen"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/recordingConsentScreen","title":"recordingConsentScreen","navigatorTitle":[{"text":"recordingConsentScreen","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Container for UI elements shown as Recording Consent screen. Enables customization of UI controls such as font, text colors, etc."}],"url":"\/documentation\/talksdk\/callconfigurationscreen\/recordingconsentscreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/CancelRequestHandler":{"type":"topic","abstract":[{"type":"text","text":"Handler type which is called when user taps on Cancel button on configuration screen."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/CancelRequestHandler","url":"\/documentation\/talksdk\/callconfigurationscreen\/cancelrequesthandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"CancelRequestHandler","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CancelRequestHandler"}],"title":"CallConfigurationScreen.CancelRequestHandler"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallConfigurationViewController"}],"navigatorTitle":[{"text":"CallConfigurationViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A view controller that is displayed before making a call, used to ask the user about necessary permissions that need to be granted."}],"type":"topic","url":"\/documentation\/talksdk\/callconfigurationviewcontroller","title":"CallConfigurationViewController","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/startCallHandler-c.property":{"kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-c.property","role":"symbol","title":"startCallHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"startCallHandler","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera","kind":"typeIdentifier","text":"StartCallHandler"},{"kind":"text","text":"?"}],"required":true,"abstract":[{"text":"Handler called after completing the configuration, it will be called with user’s ","type":"text"},{"type":"codeVoice","code":"RecordingConsentAnswer"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/startCallHandler-c.property","navigatorTitle":[{"kind":"identifier","text":"startCallHandler"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"CallConfigurationScreen","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"CallConfigurationScreen","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CallConfigurationScreen","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/cancelHandler","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/microphoneScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/recordingConsentScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/startCallHandler-c.property"],"title":"Instance Properties"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"],"type":"conformingTypes","title":"Conforming Types"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallConfigurationScreen"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CallConfigurationScreen","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/fragments","value":[{"kind":"identifier","text":"CallConfigurationScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1microphoneScreen\/title","value":"microphoneScreen"},{"value":[{"text":"microphoneScreen","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1microphoneScreen\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1cancelHandler\/title","op":"replace","value":"cancelHandler"},{"value":[{"kind":"identifier","text":"cancelHandler"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1cancelHandler\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1recordingConsentScreen\/title","value":"recordingConsentScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1recordingConsentScreen\/fragments","value":[{"kind":"identifier","text":"recordingConsentScreen"}]},{"value":"CallConfigurationViewController","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/title"},{"value":[{"text":"CallConfigurationViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1startCallHandler-c.property\/title","value":"startCallHandler"},{"value":[{"text":"startCallHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1startCallHandler-c.property\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}