{"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/allowButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/backgroundColor","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/cancelButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/messageLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/titleLabel"],"title":"Instance Properties"}],"abstract":[{"text":"Screen handling microphone permission configuration.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MicrophonePermissionScreen"}],"languages":["swift"]}]},{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"This screen checks and requests microphone permission. If there was no check before, it will show a system alert asking for permission. If there was a check and the microphone access was denied, it will show an alert asking user to turn on permission in Settings. If the microphone permission were already granted the screen is not presented."}],"type":"paragraph"},{"name":"Important","type":"aside","content":[{"inlineContent":[{"text":"Please remember about adding ","type":"text"},{"code":"NSMicrophoneUsageDescription","type":"codeVoice"},{"text":" into your app’s ","type":"text"},{"type":"codeVoice","code":"Info.plist"},{"text":" file with description.","type":"text"}],"type":"paragraph"}],"style":"important"},{"type":"aside","style":"important","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You cannot change layout of elements. In case you need your own layout setup, use other SDK API methods and build your own "},{"type":"codeVoice","code":"Recording Consent"},{"type":"text","text":" view."}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/talksdk\/microphonepermissionscreen"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/microphonepermissionscreen"]}],"metadata":{"roleHeading":"Protocol","title":"MicrophonePermissionScreen","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MicrophonePermissionScreen"}],"modules":[{"name":"TalkSDK"}],"externalID":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MicrophonePermissionScreen"}],"symbolKind":"protocol"},"kind":"symbol","references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen/allowButton":{"title":"allowButton","url":"\/documentation\/talksdk\/microphonepermissionscreen\/allowbutton","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowButton","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"required":true,"type":"topic","abstract":[{"text":"Allow Button that opens an alert asking user about microphone permission. In case permission is already granted, calls ","type":"text"},{"type":"codeVoice","code":"requestPermissionCompletion"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/allowButton","role":"symbol","navigatorTitle":[{"text":"allowButton","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen/cancelButton":{"navigatorTitle":[{"kind":"identifier","text":"cancelButton"}],"type":"topic","kind":"symbol","url":"\/documentation\/talksdk\/microphonepermissionscreen\/cancelbutton","role":"symbol","abstract":[{"type":"text","text":"Cancel Button which cancels all the flow and call "},{"code":"cancelHandler","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/cancelButton","required":true,"title":"cancelButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButton"},{"kind":"text","text":": "},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"},{"text":"!","kind":"text"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MicrophonePermissionScreen","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MicrophonePermissionScreen","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen","url":"\/documentation\/talksdk\/microphonepermissionscreen","role":"symbol","title":"MicrophonePermissionScreen","kind":"symbol","abstract":[{"type":"text","text":"Screen handling microphone permission configuration."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen/messageLabel":{"title":"messageLabel","url":"\/documentation\/talksdk\/microphonepermissionscreen\/messagelabel","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageLabel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"required":true,"type":"topic","abstract":[{"type":"text","text":"Label which shows description message under the title label."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/messageLabel","role":"symbol","navigatorTitle":[{"text":"messageLabel","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen/backgroundColor":{"required":true,"title":"backgroundColor","abstract":[{"type":"text","text":"Background color of the screen container."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"backgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/talksdk\/microphonepermissionscreen\/backgroundcolor","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/backgroundColor"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen/titleLabel":{"title":"titleLabel","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/titleLabel","abstract":[{"type":"text","text":"Label which shows main title. Example: ‘Allow microphone’."}],"type":"topic","role":"symbol","url":"\/documentation\/talksdk\/microphonepermissionscreen\/titlelabel","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"!","kind":"text"}],"kind":"symbol","required":true},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MicrophonePermissionScreen"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MicrophonePermissionScreen"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MicrophonePermissionScreen"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/allowButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/backgroundColor","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/cancelButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/messageLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/titleLabel"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MicrophonePermissionScreen"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"allowButton","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1allowButton\/title","op":"replace"},{"value":[{"kind":"identifier","text":"allowButton"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1allowButton\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1cancelButton\/title","value":"cancelButton"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1cancelButton\/fragments","value":[{"text":"cancelButton","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"MicrophonePermissionScreen","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/title"},{"value":[{"kind":"identifier","text":"MicrophonePermissionScreen"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1messageLabel\/title","value":"messageLabel"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1messageLabel\/fragments","op":"replace","value":[{"text":"messageLabel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1backgroundColor\/title","value":"backgroundColor"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1backgroundColor\/fragments","value":[{"kind":"identifier","text":"backgroundColor"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1titleLabel\/title","value":"titleLabel"},{"value":[{"text":"titleLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1titleLabel\/fragments","op":"replace"}]}]}