{"topicSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/optIn","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/optOut","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/unknown"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/Equatable-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/RawRepresentable-Implementations"]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"enum","title":"RecordingConsent","modules":[{"name":"TalkSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecordingConsent","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol","externalID":"c:@M@TalkSDK@E@RecordingConsent","navigatorTitle":[{"text":"RecordingConsent","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent"},"abstract":[{"text":"Represents digital line’s recording consent configuration.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RecordingConsent","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/SQ","doc:\/\/com.zendesk.TalkSDK\/SH","doc:\/\/com.zendesk.TalkSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/recordingconsent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/recordingconsent"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent/Equatable-Implementations":{"kind":"article","abstract":[],"type":"topic","role":"collectionGroup","url":"\/documentation\/talksdk\/recordingconsent\/equatable-implementations","title":"Equatable Implementations","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/Equatable-Implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent/optOut":{"kind":"symbol","title":"RecordingConsent.optOut","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/optOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"optOut","kind":"identifier"}],"navigatorTitle":[{"text":"RecordingConsentOptOut","kind":"identifier"}],"role":"symbol","url":"\/documentation\/talksdk\/recordingconsent\/optout","type":"topic","abstract":[{"type":"text","text":"Call recording is enabled by default, but the end user has the option to opt-out"}]},"doc://com.zendesk.TalkSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/talksdk\/recordingconsent\/init(rawvalue:)","type":"topic","abstract":[]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent":{"navigatorTitle":[{"text":"RecordingConsent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/talksdk\/recordingconsent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsent"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent","type":"topic","abstract":[{"type":"text","text":"Represents digital line’s recording consent configuration."}],"title":"RecordingConsent"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent/unknown":{"abstract":[{"type":"text","text":"Call recording is not defined in Talk settings"}],"url":"\/documentation\/talksdk\/recordingconsent\/unknown","kind":"symbol","title":"RecordingConsent.unknown","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/unknown","role":"symbol","navigatorTitle":[{"text":"RecordingConsentUnknown","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/talksdk\/recordingconsent\/rawrepresentable-implementations","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/RawRepresentable-Implementations"},"doc://com.zendesk.TalkSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SY"},"doc://com.zendesk.TalkSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SQ"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent/optIn":{"title":"RecordingConsent.optIn","type":"topic","abstract":[{"text":"Call recording is disabled by default, but the end user has the option to opt-in","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optIn"}],"navigatorTitle":[{"kind":"identifier","text":"RecordingConsentOptIn"}],"role":"symbol","kind":"symbol","url":"\/documentation\/talksdk\/recordingconsent\/optin","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/optIn"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"RecordingConsent","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"RecordingConsent","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RecordingConsent"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/optIn","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/optOut","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/unknown"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecordingConsent","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1optOut\/title","value":"RecordingConsentOptOut"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1optOut\/fragments","op":"replace","value":[{"text":"RecordingConsentOptOut","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/title","value":"RecordingConsent","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/fragments","value":[{"kind":"identifier","text":"RecordingConsent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1unknown\/title","value":"RecordingConsentUnknown","op":"replace"},{"value":[{"kind":"identifier","text":"RecordingConsentUnknown"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1unknown\/fragments"},{"value":"RecordingConsentOptIn","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1optIn\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1optIn\/fragments","op":"replace","value":[{"kind":"identifier","text":"RecordingConsentOptIn"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}