{"variants":[{"paths":["\/documentation\/talksdk\/talkcall"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talkcall"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TalkCall"}],"externalID":"c:@M@TalkSDK@objc(pl)TalkCall","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","modules":[{"name":"TalkSDK"}],"title":"TalkCall","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TalkCall","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Represents a call created by Talk SDK.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TalkCall","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Responsibility of this class is to provide set of basic operations related to the ongoing call, like muting, disconnecting or changing audio output type."}]}]}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/audioOutput","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/audioRouting","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/availableAudioRoutingOptions","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/duration","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/muted"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/disconnect()"],"title":"Instance Methods"}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall/disconnect()":{"navigatorTitle":[{"kind":"identifier","text":"disconnect"}],"abstract":[{"type":"text","text":"Ends the ongoing call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/disconnect()","role":"symbol","url":"\/documentation\/talksdk\/talkcall\/disconnect()","type":"topic","title":"disconnect()","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"disconnect","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall/duration":{"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"navigatorTitle":[{"text":"duration","kind":"identifier"}],"abstract":[{"type":"text","text":"Property that shows duration of call in seconds."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/duration","title":"duration","url":"\/documentation\/talksdk\/talkcall\/duration","role":"symbol","required":true},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TalkCall"}],"navigatorTitle":[{"kind":"identifier","text":"TalkCall"}],"abstract":[{"text":"Represents a call created by Talk SDK.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","title":"TalkCall","url":"\/documentation\/talksdk\/talkcall","role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall/audioRouting":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/audioRouting","url":"\/documentation\/talksdk\/talkcall\/audiorouting","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioRouting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioRoutingOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)AudioRoutingOption"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"audioRouting"}],"kind":"symbol","abstract":[{"text":"Current audio routing for call’s audio input and output.","type":"text"}],"role":"symbol","title":"audioRouting","required":true},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall/audioOutput":{"navigatorTitle":[{"text":"audioOutput","kind":"identifier"}],"abstract":[{"type":"text","text":"Device specified audio output."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/audioOutput","role":"symbol","url":"\/documentation\/talksdk\/talkcall\/audiooutput","type":"topic","title":"audioOutput","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOutput"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AudioOutput","preciseIdentifier":"c:@M@TalkSDK@E@AudioOutput"}],"kind":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall/availableAudioRoutingOptions":{"navigatorTitle":[{"text":"availableAudioRoutingOptions","kind":"identifier"}],"abstract":[{"text":"List of all currently available audio routing options provided by the device.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/availableAudioRoutingOptions","role":"symbol","url":"\/documentation\/talksdk\/talkcall\/availableaudioroutingoptions","type":"topic","title":"availableAudioRoutingOptions","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableAudioRoutingOptions"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)AudioRoutingOption","kind":"typeIdentifier","text":"AudioRoutingOption"},{"text":"]","kind":"text"}],"kind":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall/muted":{"navigatorTitle":[{"kind":"identifier","text":"muted"}],"abstract":[{"text":"Property that defines if the call is muted.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/muted","role":"symbol","url":"\/documentation\/talksdk\/talkcall\/muted","type":"topic","title":"muted","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"muted"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"TalkCall"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"TalkCall","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"TalkCall","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/audioOutput","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/audioRouting","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/availableAudioRoutingOptions","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/duration","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/muted"]},{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/disconnect()"],"title":"Instance Methods"}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TalkCall","kind":"identifier"}]}]},"op":"replace"},{"value":"disconnect","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1disconnect()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1disconnect()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disconnect"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1duration\/title","value":"duration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/title","value":"TalkCall"},{"op":"replace","value":[{"kind":"identifier","text":"TalkCall"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/fragments"},{"value":"audioRouting","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1audioRouting\/title"},{"value":[{"kind":"identifier","text":"audioRouting"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1audioRouting\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1audioOutput\/title","value":"audioOutput"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1audioOutput\/fragments","value":[{"kind":"identifier","text":"audioOutput"}]},{"value":"availableAudioRoutingOptions","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1availableAudioRoutingOptions\/title","op":"replace"},{"value":[{"text":"availableAudioRoutingOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1availableAudioRoutingOptions\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1muted\/title","value":"muted","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1muted\/fragments","value":[{"kind":"identifier","text":"muted"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}