{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKTalkCallData) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TalkCallData","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/init(digitalLine:recordingConsentAnswer:)"]},{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/digitalLine","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/recordingConsentAnswer"],"title":"Instance Properties"}],"kind":"symbol","metadata":{"symbolKind":"class","externalID":"c:@M@TalkSDK@objc(cs)ZDKTalkCallData","modules":[{"name":"TalkSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallData"}],"title":"TalkCallData","roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"TalkCallData","kind":"identifier"}]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.TalkSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.TalkSDK\/s7CVarArgP","doc:\/\/com.zendesk.TalkSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.TalkSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.TalkSDK\/SQ","doc:\/\/com.zendesk.TalkSDK\/SH"],"type":"conformsTo"}],"abstract":[{"code":"CallData","type":"codeVoice"},{"type":"text","text":" conforming class that represents parameters required to make a call."}],"variants":[{"paths":["\/documentation\/talksdk\/talkcalldata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talkcalldata"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.TalkSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.TalkSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData":{"abstract":[{"type":"codeVoice","code":"CallData"},{"type":"text","text":" conforming class that represents parameters required to make a call."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallData"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData","type":"topic","url":"\/documentation\/talksdk\/talkcalldata","navigatorTitle":[{"text":"TalkCallData","kind":"identifier"}],"kind":"symbol","title":"TalkCallData"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData/digitalLine":{"type":"topic","abstract":[{"type":"text","text":"Name of digital line configured by the admin in Talk Settings."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalLine","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7TalkSDK11DigitalLinea","text":"DigitalLine","kind":"typeIdentifier"}],"title":"digitalLine","url":"\/documentation\/talksdk\/talkcalldata\/digitalline","role":"symbol","navigatorTitle":[{"text":"digitalLine","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/digitalLine","kind":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData/recordingConsentAnswer":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/recordingConsentAnswer","navigatorTitle":[{"text":"recordingConsentAnswer","kind":"identifier"}],"type":"topic","title":"recordingConsentAnswer","url":"\/documentation\/talksdk\/talkcalldata\/recordingconsentanswer","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"recordingConsentAnswer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer","kind":"typeIdentifier","text":"RecordingConsentAnswer"}],"kind":"symbol","abstract":[{"type":"text","text":"Answer received from end user about recording the call."}],"role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","navigatorTitle":[{"text":"CallData","kind":"identifier"}],"type":"topic","title":"CallData","url":"\/documentation\/talksdk\/calldata","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallData","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"role":"symbol"},"doc://com.zendesk.TalkSDK/SQ":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.TalkSDK/SH":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.TalkSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.TalkSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.TalkSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData/init(digitalLine:recordingConsentAnswer:)":{"kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/talkcalldata\/init(digitalline:recordingconsentanswer:)","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/init(digitalLine:recordingConsentAnswer:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7TalkSDK11DigitalLinea","kind":"typeIdentifier","text":"DigitalLine"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recordingConsentAnswer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer","text":"RecordingConsentAnswer"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithDigitalLine:recordingConsentAnswer:"}],"title":"init(digitalLine:recordingConsentAnswer:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKTalkCallData"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKTalkCallData","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKTalkCallData"}],"op":"replace"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/digitalLine","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/recordingConsentAnswer"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/init(digitalLine:recordingConsentAnswer:)"]}],"path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.TalkSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData"],"type":"conformsTo","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ZDKTalkCallData","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/title","value":"ZDKTalkCallData","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKTalkCallData"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/fragments"},{"value":"digitalLine","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1digitalLine\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1digitalLine\/fragments","op":"replace","value":[{"text":"digitalLine","kind":"identifier"}]},{"value":"recordingConsentAnswer","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1recordingConsentAnswer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1recordingConsentAnswer\/fragments","value":[{"text":"recordingConsentAnswer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/title","value":"CallData"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/fragments","op":"replace","value":[{"text":"CallData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1init(digitalLine:recordingConsentAnswer:)\/title","op":"replace","value":"initWithDigitalLine:recordingConsentAnswer:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDigitalLine:recordingConsentAnswer:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1init(digitalLine:recordingConsentAnswer:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}