{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider\/StatusChangeHandler"},"metadata":{"modules":[{"name":"TalkSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"StatusChangeHandler","kind":"identifier"}],"symbolKind":"typealias","externalID":"s:7TalkSDK0A12CoreProviderP19StatusChangeHandlera","roleHeading":"Type Alias","navigatorTitle":[{"text":"StatusChangeHandler","kind":"identifier"}],"title":"TalkCoreProvider.StatusChangeHandler"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Handler type for call status changes and errors.","type":"text"}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"StatusChangeHandler","kind":"identifier"},{"text":" = (","kind":"text"},{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","preciseIdentifier":"c:@M@TalkSDK@E@CallStatus","text":"CallStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError","text":"TalkCallError","kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@E@TalkCallError"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}]}]}],"variants":[{"paths":["\/documentation\/talksdk\/talkcoreprovider\/statuschangehandler"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TalkCallError","kind":"identifier"}],"abstract":[{"text":"Represents errors occuring for a ","type":"text"},{"type":"codeVoice","code":"failed"},{"type":"text","text":" or "},{"code":"disconnected","type":"codeVoice"},{"text":" call.","type":"text"}],"kind":"symbol","title":"TalkCallError","role":"symbol","url":"\/documentation\/talksdk\/talkcallerror","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError","type":"topic","navigatorTitle":[{"text":"TalkCallError","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCoreProvider/StatusChangeHandler":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusChangeHandler","kind":"identifier"}],"type":"topic","url":"\/documentation\/talksdk\/talkcoreprovider\/statuschangehandler","abstract":[{"type":"text","text":"Handler type for call status changes and errors."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider\/StatusChangeHandler","kind":"symbol","navigatorTitle":[{"text":"StatusChangeHandler","kind":"identifier"}],"title":"TalkCoreProvider.StatusChangeHandler"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallStatus","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatus"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","url":"\/documentation\/talksdk\/callstatus","role":"symbol","title":"CallStatus","kind":"symbol","abstract":[{"type":"text","text":"Represents all possible states of the call."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCoreProvider":{"title":"TalkCoreProvider","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider","url":"\/documentation\/talksdk\/talkcoreprovider","navigatorTitle":[{"text":"TalkCoreProvider","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Main "},{"code":"Talk","type":"codeVoice"},{"text":" provider, responsible for the core calling API functionality.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TalkCoreProvider"}]}},"variantOverrides":[{"patch":[{"value":"TalkCallError","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/title","op":"replace"},{"value":[{"text":"TalkCallError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/fragments"},{"value":"CallStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/fragments","value":[{"text":"CallStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}