{"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall"]]},"abstract":[{"text":"Current audio routing for call’s audio input and output.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioRouting"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)AudioRoutingOption","kind":"typeIdentifier","text":"AudioRoutingOption"},{"kind":"text","text":"?"}],"role":"symbol","externalID":"c:@M@TalkSDK@objc(pl)TalkCall(py)audioRouting","roleHeading":"Instance Property","modules":[{"name":"TalkSDK"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"audioRouting"}],"title":"audioRouting"},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/audioRouting","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioRouting"},{"kind":"text","text":": "},{"text":"AudioRoutingOption","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption","preciseIdentifier":"c:@M@TalkSDK@objc(pl)AudioRoutingOption"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/talksdk\/talkcall\/audiorouting"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/talkcall\/audiorouting"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TalkCall"}],"navigatorTitle":[{"kind":"identifier","text":"TalkCall"}],"abstract":[{"text":"Represents a call created by Talk SDK.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","title":"TalkCall","url":"\/documentation\/talksdk\/talkcall","role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingOption":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AudioRoutingOption","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AudioRoutingOption"}],"abstract":[{"text":"Describes possible options for routing call’s audio input and output.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption","title":"AudioRoutingOption","url":"\/documentation\/talksdk\/audioroutingoption","role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall/audioRouting":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/audioRouting","url":"\/documentation\/talksdk\/talkcall\/audiorouting","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audioRouting","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AudioRoutingOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)AudioRoutingOption"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"audioRouting"}],"kind":"symbol","abstract":[{"text":"Current audio routing for call’s audio input and output.","type":"text"}],"role":"symbol","title":"audioRouting","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"audioRouting","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"audioRouting","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@TalkSDK@objc(pl)AudioRoutingOption","text":"id<AudioRoutingOption>"},{"text":" * ","kind":"text"},{"text":"audioRouting","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"TalkCall","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/fragments","value":[{"text":"TalkCall","kind":"identifier"}]},{"op":"replace","value":"AudioRoutingOption","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption\/fragments","value":[{"text":"AudioRoutingOption","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1audioRouting\/title","value":"audioRouting"},{"value":[{"text":"audioRouting","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1audioRouting\/fragments"}]}]}