{"kind":"symbol","sections":[],"metadata":{"required":true,"title":"availableAudioRoutingOptions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)TalkCall(py)availableAudioRoutingOptions","modules":[{"name":"TalkSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"availableAudioRoutingOptions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AudioRoutingOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)AudioRoutingOption"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"availableAudioRoutingOptions","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/availableAudioRoutingOptions"},"abstract":[{"type":"text","text":"List of all currently available audio routing options provided by the device."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"availableAudioRoutingOptions"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)AudioRoutingOption","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption","text":"AudioRoutingOption","kind":"typeIdentifier"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/talkcall\/availableaudioroutingoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/talkcall\/availableaudioroutingoptions"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TalkCall"}],"navigatorTitle":[{"kind":"identifier","text":"TalkCall"}],"abstract":[{"text":"Represents a call created by Talk SDK.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","title":"TalkCall","url":"\/documentation\/talksdk\/talkcall","role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingOption":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AudioRoutingOption","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AudioRoutingOption"}],"abstract":[{"text":"Describes possible options for routing call’s audio input and output.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption","title":"AudioRoutingOption","url":"\/documentation\/talksdk\/audioroutingoption","role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall/availableAudioRoutingOptions":{"navigatorTitle":[{"text":"availableAudioRoutingOptions","kind":"identifier"}],"abstract":[{"text":"List of all currently available audio routing options provided by the device.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/availableAudioRoutingOptions","role":"symbol","url":"\/documentation\/talksdk\/talkcall\/availableaudioroutingoptions","type":"topic","title":"availableAudioRoutingOptions","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableAudioRoutingOptions"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)AudioRoutingOption","kind":"typeIdentifier","text":"AudioRoutingOption"},{"text":"]","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"availableAudioRoutingOptions"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"availableAudioRoutingOptions","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<AudioRoutingOption>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"availableAudioRoutingOptions","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"TalkCall","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/title"},{"value":[{"kind":"identifier","text":"TalkCall"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/fragments"},{"value":"AudioRoutingOption","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption\/title"},{"op":"replace","value":[{"text":"AudioRoutingOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1availableAudioRoutingOptions\/title","value":"availableAudioRoutingOptions"},{"value":[{"kind":"identifier","text":"availableAudioRoutingOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1availableAudioRoutingOptions\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}