{"abstract":[{"type":"text","text":"Property that shows duration of call in seconds."}],"metadata":{"role":"symbol","title":"duration","symbolKind":"property","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"navigatorTitle":[{"kind":"identifier","text":"duration"}],"externalID":"c:@M@TalkSDK@objc(pl)TalkCall(py)duration","roleHeading":"Instance Property","modules":[{"name":"TalkSDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall"]]},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/duration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Default value is ","type":"text"},{"type":"codeVoice","code":"0"},{"type":"text","text":". It will be "},{"code":"0","type":"codeVoice"},{"text":" until the call is started.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/talkcall\/duration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/talkcall\/duration"]}],"kind":"symbol","references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TalkCall"}],"navigatorTitle":[{"kind":"identifier","text":"TalkCall"}],"abstract":[{"text":"Represents a call created by Talk SDK.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","title":"TalkCall","url":"\/documentation\/talksdk\/talkcall","role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall/duration":{"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"navigatorTitle":[{"text":"duration","kind":"identifier"}],"abstract":[{"type":"text","text":"Property that shows duration of call in seconds."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/duration","title":"duration","url":"\/documentation\/talksdk\/talkcall\/duration","role":"symbol","required":true}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"duration","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"duration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/title","value":"TalkCall","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/fragments","op":"replace","value":[{"text":"TalkCall","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1duration\/title","op":"replace","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}