{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callButtonsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallButtonsView","text":"CallButtonsView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callscreen\/callbuttonsview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callscreen\/callbuttonsview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callButtonsView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"View containing call screen action buttons."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"callButtonsView"}],"role":"symbol","title":"callButtonsView","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callButtonsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallButtonsView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallButtonsView"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)CallScreen(py)callButtonsView","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen":{"role":"symbol","title":"CallScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallScreen"}],"abstract":[{"type":"text","text":"A screen presented for an ongoing call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallScreen"}],"url":"\/documentation\/talksdk\/callscreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView":{"role":"symbol","title":"CallButtonsView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallButtonsView"}],"abstract":[{"type":"text","text":"Represent the bottom buttons view in call screen."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallButtonsView"}],"url":"\/documentation\/talksdk\/callbuttonsview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen/callButtonsView":{"navigatorTitle":[{"kind":"identifier","text":"callButtonsView"}],"role":"symbol","title":"callButtonsView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callButtonsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallButtonsView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallButtonsView"}],"abstract":[{"type":"text","text":"View containing call screen action buttons."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callButtonsView","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callscreen\/callbuttonsview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"callButtonsView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"callButtonsView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIView<CallButtonsView>","preciseIdentifier":"c:Q$objc(cs)UIView@M@TalkSDK@objc(pl)CallButtonsView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"callButtonsView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/title","value":"CallScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/fragments","value":[{"kind":"identifier","text":"CallScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/title","value":"CallButtonsView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/fragments","value":[{"kind":"identifier","text":"CallButtonsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callButtonsView\/title","value":"callButtonsView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callButtonsView\/fragments","value":[{"kind":"identifier","text":"callButtonsView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}