{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callErrorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallErrorView","text":"CallErrorView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callscreen\/callerrorview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callscreen\/callerrorview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callErrorView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error view with retry and cancel buttons."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"callErrorView"}],"role":"symbol","title":"callErrorView","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callErrorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallErrorView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallErrorView"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)CallScreen(py)callErrorView","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen":{"role":"symbol","title":"CallScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallScreen"}],"abstract":[{"type":"text","text":"A screen presented for an ongoing call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallScreen"}],"url":"\/documentation\/talksdk\/callscreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView":{"role":"symbol","title":"CallErrorView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallErrorView"}],"abstract":[{"type":"text","text":"Represent the error view with "},{"type":"codeVoice","code":"retry"},{"type":"text","text":" and "},{"type":"codeVoice","code":"cancel"},{"type":"text","text":" buttons."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallErrorView"}],"url":"\/documentation\/talksdk\/callerrorview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen/callErrorView":{"navigatorTitle":[{"kind":"identifier","text":"callErrorView"}],"role":"symbol","title":"callErrorView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callErrorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallErrorView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallErrorView"}],"abstract":[{"type":"text","text":"Error view with retry and cancel buttons."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callErrorView","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callscreen\/callerrorview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"callErrorView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"callErrorView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIView<CallErrorView>","preciseIdentifier":"c:Q$objc(cs)UIView@M@TalkSDK@objc(pl)CallErrorView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"callErrorView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/title","value":"CallScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/fragments","value":[{"kind":"identifier","text":"CallScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/title","value":"CallErrorView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/fragments","value":[{"kind":"identifier","text":"CallErrorView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callErrorView\/title","value":"callErrorView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callErrorView\/fragments","value":[{"kind":"identifier","text":"callErrorView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}