{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"agentAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/linestatus\/agentavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/linestatus\/agentavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus\/agentAvailable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Boolean flag which should be used to determine whether the “call us button” should be visible to end user."},{"type":"text","text":" "},{"type":"text","text":"Value "},{"type":"codeVoice","code":"true"},{"type":"text","text":" means that line is available to use. Value "},{"type":"codeVoice","code":"false"},{"type":"text","text":" means that the line is either disabled or no agent is available."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"agentAvailable"}],"role":"symbol","title":"agentAvailable","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"agentAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)LineStatus(py)agentAvailable","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/LineStatus/agentAvailable":{"navigatorTitle":[{"kind":"identifier","text":"agentAvailable"}],"role":"symbol","title":"agentAvailable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"agentAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Boolean flag which should be used to determine whether the “call us button” should be visible to end user."},{"type":"text","text":" "},{"type":"text","text":"Value "},{"type":"codeVoice","code":"true"},{"type":"text","text":" means that line is available to use. Value "},{"type":"codeVoice","code":"false"},{"type":"text","text":" means that the line is either disabled or no agent is available."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus\/agentAvailable","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/linestatus\/agentavailable"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/LineStatus":{"role":"symbol","title":"LineStatus","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineStatus"}],"abstract":[{"type":"text","text":"Comprehensive information about status of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineStatus"}],"url":"\/documentation\/talksdk\/linestatus"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"agentAvailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"agentAvailable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"agentAvailable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus~1agentAvailable\/title","value":"agentAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus~1agentAvailable\/fragments","value":[{"kind":"identifier","text":"agentAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/title","value":"LineStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/fragments","value":[{"kind":"identifier","text":"LineStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}