{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsent","text":"RecordingConsent"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/linestatus\/recordingconsent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/linestatus\/recordingconsent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus\/recordingConsent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Digital line’s current recording and recording consent configuration."},{"type":"text","text":" "},{"type":"text","text":"Using value of this property the end user may be allowed for opting-in or opting-out from call recording."},{"type":"text","text":" "},{"type":"text","text":"If the "},{"type":"strong","inlineContent":[{"type":"text","text":"recordingConsent"}]},{"type":"text","text":" is "},{"type":"codeVoice","code":"unknown"},{"type":"text","text":" it means that end user does not need to opt-in or opt-out from call recording."},{"type":"text","text":" "},{"type":"text","text":"At the same time the "},{"type":"codeVoice","code":"unknown"},{"type":"text","text":" value does not provide any information whether the call will be recorded or not."},{"type":"text","text":" "},{"type":"text","text":"With the "},{"type":"codeVoice","code":"unknown"},{"type":"text","text":" value, all configuration is handled server side."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"recordingConsent"}],"role":"symbol","title":"recordingConsent","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecordingConsent","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsent"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)LineStatus(py)recordingConsent","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent":{"role":"symbol","title":"RecordingConsent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsent"}],"abstract":[{"type":"text","text":"Represents digital line’s recording consent configuration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsent"}],"url":"\/documentation\/talksdk\/recordingconsent"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/LineStatus":{"role":"symbol","title":"LineStatus","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineStatus"}],"abstract":[{"type":"text","text":"Comprehensive information about status of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineStatus"}],"url":"\/documentation\/talksdk\/linestatus"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/LineStatus/recordingConsent":{"navigatorTitle":[{"kind":"identifier","text":"recordingConsent"}],"role":"symbol","title":"recordingConsent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecordingConsent","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsent"}],"abstract":[{"type":"text","text":"Digital line’s current recording and recording consent configuration."},{"type":"text","text":" "},{"type":"text","text":"Using value of this property the end user may be allowed for opting-in or opting-out from call recording."},{"type":"text","text":" "},{"type":"text","text":"If the "},{"type":"strong","inlineContent":[{"type":"text","text":"recordingConsent"}]},{"type":"text","text":" is "},{"type":"codeVoice","code":"unknown"},{"type":"text","text":" it means that end user does not need to opt-in or opt-out from call recording."},{"type":"text","text":" "},{"type":"text","text":"At the same time the "},{"type":"codeVoice","code":"unknown"},{"type":"text","text":" value does not provide any information whether the call will be recorded or not."},{"type":"text","text":" "},{"type":"text","text":"With the "},{"type":"codeVoice","code":"unknown"},{"type":"text","text":" value, all configuration is handled server side."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus\/recordingConsent","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/linestatus\/recordingconsent"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recordingConsent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"recordingConsent"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsent","text":"RecordingConsent"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/title","value":"RecordingConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/fragments","value":[{"kind":"identifier","text":"RecordingConsent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/title","value":"LineStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/fragments","value":[{"kind":"identifier","text":"LineStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus~1recordingConsent\/title","value":"recordingConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus~1recordingConsent\/fragments","value":[{"kind":"identifier","text":"recordingConsent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}