{"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/digitalLine","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Name of digital line configured by the admin in Talk Settings."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"digitalLine","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7TalkSDK11DigitalLinea","kind":"typeIdentifier","text":"DigitalLine","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/talkcalldata\/digitalline"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/talkcalldata\/digitalline"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"digitalLine","symbolKind":"property","role":"symbol","externalID":"c:@M@TalkSDK@objc(cs)ZDKTalkCallData(py)digitalLine","modules":[{"name":"TalkSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalLine"},{"text":": ","kind":"text"},{"text":"DigitalLine","kind":"typeIdentifier","preciseIdentifier":"s:7TalkSDK11DigitalLinea"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"digitalLine","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData":{"abstract":[{"type":"codeVoice","code":"CallData"},{"type":"text","text":" conforming class that represents parameters required to make a call."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallData"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData","type":"topic","url":"\/documentation\/talksdk\/talkcalldata","navigatorTitle":[{"text":"TalkCallData","kind":"identifier"}],"kind":"symbol","title":"TalkCallData"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/DigitalLine":{"title":"DigitalLine","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalLine"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DigitalLine"}],"url":"\/documentation\/talksdk\/digitalline","kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","type":"topic","abstract":[{"type":"text","text":"Name of digital line."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData/digitalLine":{"type":"topic","abstract":[{"type":"text","text":"Name of digital line configured by the admin in Talk Settings."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalLine","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7TalkSDK11DigitalLinea","text":"DigitalLine","kind":"typeIdentifier"}],"title":"digitalLine","url":"\/documentation\/talksdk\/talkcalldata\/digitalline","role":"symbol","navigatorTitle":[{"text":"digitalLine","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/digitalLine","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"digitalLine"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"digitalLine","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"digitalLine","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"ZDKTalkCallData","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/fragments","value":[{"text":"ZDKTalkCallData","kind":"identifier"}],"op":"replace"},{"value":"digitalLine","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1digitalLine\/title","op":"replace"},{"value":[{"text":"digitalLine","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1digitalLine\/fragments"}]}]}