{"variants":[{"paths":["\/documentation\/talksdk\/talkcalldata\/init(digitalline:recordingconsentanswer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/talkcalldata\/init(digitalline:recordingconsentanswer:)"]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/init(digitalLine:recordingConsentAnswer:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine"},{"kind":"text","text":", "},{"text":"recordingConsentAnswer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer","text":"RecordingConsentAnswer","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer"},{"kind":"text","text":")"}]}]}],"metadata":{"title":"init(digitalLine:recordingConsentAnswer:)","navigatorTitle":[{"text":"initWithDigitalLine:recordingConsentAnswer:","kind":"identifier"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"digitalLine","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7TalkSDK11DigitalLinea","text":"DigitalLine","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"recordingConsentAnswer"},{"kind":"text","text":": "},{"text":"RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@TalkSDK@objc(cs)ZDKTalkCallData(im)initWithDigitalLine:recordingConsentAnswer:","modules":[{"name":"TalkSDK"}],"roleHeading":"Initializer"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData":{"abstract":[{"type":"codeVoice","code":"CallData"},{"type":"text","text":" conforming class that represents parameters required to make a call."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallData"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData","type":"topic","url":"\/documentation\/talksdk\/talkcalldata","navigatorTitle":[{"text":"TalkCallData","kind":"identifier"}],"kind":"symbol","title":"TalkCallData"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData/init(digitalLine:recordingConsentAnswer:)":{"kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/talkcalldata\/init(digitalline:recordingconsentanswer:)","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/init(digitalLine:recordingConsentAnswer:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7TalkSDK11DigitalLinea","kind":"typeIdentifier","text":"DigitalLine"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"recordingConsentAnswer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer","text":"RecordingConsentAnswer"},{"text":")","kind":"text"}],"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithDigitalLine:recordingConsentAnswer:"}],"title":"init(digitalLine:recordingConsentAnswer:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer":{"title":"RecordingConsentAnswer","abstract":[{"type":"text","text":"Represents the answer received from end user about recording the call."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecordingConsentAnswer","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","url":"\/documentation\/talksdk\/recordingconsentanswer","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswer"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/DigitalLine":{"title":"DigitalLine","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalLine"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DigitalLine"}],"url":"\/documentation\/talksdk\/digitalline","kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","type":"topic","abstract":[{"type":"text","text":"Name of digital line."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithDigitalLine:recordingConsentAnswer:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDigitalLine:recordingConsentAnswer:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDigitalLine:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"digitalLine","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"recordingConsentAnswer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer","kind":"typeIdentifier","text":"RecordingConsentAnswer"},{"kind":"text","text":") "},{"text":"recordingConsentAnswer","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/title","op":"replace","value":"ZDKTalkCallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/fragments","value":[{"text":"ZDKTalkCallData","kind":"identifier"}]},{"op":"replace","value":"initWithDigitalLine:recordingConsentAnswer:","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1init(digitalLine:recordingConsentAnswer:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithDigitalLine:recordingConsentAnswer:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1init(digitalLine:recordingConsentAnswer:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/title","value":"RecordingConsentAnswer","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswer"}],"op":"replace"}]}]}