{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/microphonepermissionscreen\/titlelabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/microphonepermissionscreen\/titlelabel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/titleLabel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Label which shows main title. Example: ‘Allow microphone’."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"role":"symbol","title":"titleLabel","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen(py)titleLabel","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen/titleLabel":{"navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Label which shows main title. Example: ‘Allow microphone’."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen\/titleLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/microphonepermissionscreen\/titlelabel"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen":{"role":"symbol","title":"MicrophonePermissionScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MicrophonePermissionScreen"}],"abstract":[{"type":"text","text":"Screen handling microphone permission configuration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MicrophonePermissionScreen"}],"url":"\/documentation\/talksdk\/microphonepermissionscreen"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"titleLabel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"titleLabel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/title","value":"MicrophonePermissionScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/fragments","value":[{"kind":"identifier","text":"MicrophonePermissionScreen"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}