{"variants":[{"paths":["\/documentation\/talksdk\/callviewcontroller\/avroutepickerviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callviewcontroller\/avroutepickerviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/AVRoutePickerViewDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/routePickerViewDidEndPresentingRoutes(_:)","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/routePickerViewWillBeginPresentingRoutes(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"TalkSDK"}],"role":"collectionGroup","title":"AVRoutePickerViewDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController":{"role":"symbol","title":"CallViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallViewController"}],"abstract":[{"type":"text","text":"A view controller displayed for an ongoing call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}],"url":"\/documentation\/talksdk\/callviewcontroller"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/routePickerViewWillBeginPresentingRoutes(_:)":{"role":"symbol","title":"routePickerViewWillBeginPresentingRoutes(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"routePickerViewWillBeginPresentingRoutes"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVRoutePickerView","preciseIdentifier":"c:objc(cs)AVRoutePickerView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/routePickerViewWillBeginPresentingRoutes(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"routePickerViewWillBeginPresentingRoutes:"}],"url":"\/documentation\/talksdk\/callviewcontroller\/routepickerviewwillbeginpresentingroutes(_:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/routePickerViewDidEndPresentingRoutes(_:)":{"role":"symbol","title":"routePickerViewDidEndPresentingRoutes(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"routePickerViewDidEndPresentingRoutes"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVRoutePickerView","preciseIdentifier":"c:objc(cs)AVRoutePickerView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/routePickerViewDidEndPresentingRoutes(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"routePickerViewDidEndPresentingRoutes:"}],"url":"\/documentation\/talksdk\/callviewcontroller\/routepickerviewdidendpresentingroutes(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/routePickerViewDidEndPresentingRoutes(_:)","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/routePickerViewWillBeginPresentingRoutes(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/title","value":"CallViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/fragments","value":[{"kind":"identifier","text":"CallViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1routePickerViewWillBeginPresentingRoutes(_:)\/title","value":"routePickerViewWillBeginPresentingRoutes:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1routePickerViewWillBeginPresentingRoutes(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"routePickerViewWillBeginPresentingRoutes:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1routePickerViewDidEndPresentingRoutes(_:)\/title","value":"routePickerViewDidEndPresentingRoutes:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1routePickerViewDidEndPresentingRoutes(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"routePickerViewDidEndPresentingRoutes:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}