{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callTimerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallTimerView","text":"CallTimerView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callviewcontroller\/calltimerview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callviewcontroller\/calltimerview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callTimerView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Timer view displaying call duration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callTimerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallTimerView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallTimerView"}],"title":"callTimerView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@TalkSDK@objc(cs)CallViewController(py)callTimerView","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"callTimerView"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallTimerView":{"role":"symbol","title":"CallTimerView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallTimerView"}],"abstract":[{"type":"text","text":"Represent the timer view with a label showing call’s duration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallTimerView"}],"url":"\/documentation\/talksdk\/calltimerview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController":{"role":"symbol","title":"CallViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallViewController"}],"abstract":[{"type":"text","text":"A view controller displayed for an ongoing call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}],"url":"\/documentation\/talksdk\/callviewcontroller"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/callTimerView":{"role":"symbol","title":"callTimerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callTimerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallTimerView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallTimerView"}],"abstract":[{"type":"text","text":"Timer view displaying call duration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callTimerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callTimerView"}],"url":"\/documentation\/talksdk\/callviewcontroller\/calltimerview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"callTimerView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"callTimerView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIView<CallTimerView>","preciseIdentifier":"c:Q$objc(cs)UIView@M@TalkSDK@objc(pl)CallTimerView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"callTimerView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView\/title","value":"CallTimerView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView\/fragments","value":[{"kind":"identifier","text":"CallTimerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/title","value":"CallViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/fragments","value":[{"kind":"identifier","text":"CallViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callTimerView\/title","value":"callTimerView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callTimerView\/fragments","value":[{"kind":"identifier","text":"callTimerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}