{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"call"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData","text":"CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusChangeHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider\/StatusChangeHandler","preciseIdentifier":"s:7TalkSDK0A12CoreProviderP19StatusChangeHandlera","text":"StatusChangeHandler"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","preciseIdentifier":"c:@M@TalkSDK@objc(pl)TalkCall","text":"TalkCall"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"TalkCall"},{"type":"text","text":" object representing the call, enabling to control it’s various parameters as: "},{"type":"codeVoice","code":"DeviceOutput"},{"type":"text","text":", "},{"type":"codeVoice","code":"mute"},{"type":"text","text":" or "},{"type":"codeVoice","code":"disconnect"},{"type":"text","text":"."}]}]},{"kind":"parameters","parameters":[{"name":"callData","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Details for the call which contain "},{"type":"codeVoice","code":"digitalLine"},{"type":"text","text":" and "},{"type":"codeVoice","code":"recordingConsentAnswer"}]}]},{"name":"statusChangeHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"will be called on every call status change"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"After call is initialized or fails to connect a handler is called with matching result."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You need to keep strong reference to returned "},{"type":"codeVoice","code":"TalkCall"},{"type":"text","text":" object, otherwise call will be disconnected and released from memory."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talkcoreprovider\/call(calldata:statuschangehandler:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider\/call(callData:statusChangeHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a call for provided call data."}],"kind":"symbol","metadata":{"role":"symbol","title":"call(callData:statusChangeHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"call"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusChangeHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatusChangeHandler","preciseIdentifier":"s:7TalkSDK0A12CoreProviderP19StatusChangeHandlera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TalkCall","preciseIdentifier":"c:@M@TalkSDK@objc(pl)TalkCall"}],"symbolKind":"method","externalID":"s:7TalkSDK0A12CoreProviderP4call0E4Data19statusChangeHandlerAA0A4Call_pAA0jF0_p_yAA0J6StatusO_AA0aJ5ErrorOSgtctF","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCoreProvider/call(callData:statusChangeHandler:)":{"role":"symbol","title":"call(callData:statusChangeHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"call"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusChangeHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatusChangeHandler","preciseIdentifier":"s:7TalkSDK0A12CoreProviderP19StatusChangeHandlera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TalkCall","preciseIdentifier":"c:@M@TalkSDK@objc(pl)TalkCall"}],"abstract":[{"type":"text","text":"Initializes a call for provided call data."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider\/call(callData:statusChangeHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/talkcoreprovider\/call(calldata:statuschangehandler:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData":{"role":"symbol","title":"CallData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallData"}],"abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallData"}],"url":"\/documentation\/talksdk\/calldata"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCoreProvider":{"role":"symbol","title":"TalkCoreProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCoreProvider"}],"abstract":[{"type":"text","text":"Main "},{"type":"codeVoice","code":"Talk"},{"type":"text","text":" provider, responsible for the core calling API functionality."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCoreProvider"}],"url":"\/documentation\/talksdk\/talkcoreprovider"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall":{"role":"symbol","title":"TalkCall","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCall"}],"abstract":[{"type":"text","text":"Represents a call created by Talk SDK."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCall"}],"url":"\/documentation\/talksdk\/talkcall"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCoreProvider/StatusChangeHandler":{"role":"symbol","title":"TalkCoreProvider.StatusChangeHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusChangeHandler"}],"abstract":[{"type":"text","text":"Handler type for call status changes and errors."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider\/StatusChangeHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusChangeHandler"}],"url":"\/documentation\/talksdk\/talkcoreprovider\/statuschangehandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/title","value":"CallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/fragments","value":[{"kind":"identifier","text":"CallData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/title","value":"TalkCall"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/fragments","value":[{"kind":"identifier","text":"TalkCall"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}