{"variants":[{"paths":["\/documentation\/talksdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData"]},{"title":"Protocols","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallSummary","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkFlowProvider","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkScreenProvider"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine"]},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AgentStatusError","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"TalkSDK","title":"TalkSDK","symbolKind":"module","role":"collection","modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingOption":{"role":"symbol","title":"AudioRoutingOption","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioRoutingOption"}],"abstract":[{"type":"text","text":"Describes possible options for routing call’s audio input and output."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioRoutingOption"}],"url":"\/documentation\/talksdk\/audioroutingoption"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController":{"role":"symbol","title":"CallViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallViewController"}],"abstract":[{"type":"text","text":"A view controller displayed for an ongoing call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}],"url":"\/documentation\/talksdk\/callviewcontroller"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/DigitalLine":{"role":"symbol","title":"DigitalLine","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalLine"}],"abstract":[{"type":"text","text":"Name of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DigitalLine"}],"url":"\/documentation\/talksdk\/digitalline"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkFlowProvider":{"role":"symbol","title":"TalkFlowProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkFlowProvider"}],"abstract":[{"type":"text","text":"Call flow provider, responsible for effortlessly starting the call using SDK provided screens and APIs."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkFlowProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkFlowProvider"}],"url":"\/documentation\/talksdk\/talkflowprovider"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer":{"role":"symbol","title":"RecordingConsentAnswer","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentAnswer"}],"abstract":[{"type":"text","text":"Represents the answer received from end user about recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswer"}],"url":"\/documentation\/talksdk\/recordingconsentanswer"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall":{"role":"symbol","title":"TalkCall","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCall"}],"abstract":[{"type":"text","text":"Represents a call created by Talk SDK."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCall"}],"url":"\/documentation\/talksdk\/talkcall"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError":{"role":"symbol","title":"TalkCallError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallError"}],"abstract":[{"type":"text","text":"Represents errors occuring for a "},{"type":"codeVoice","code":"failed"},{"type":"text","text":" or "},{"type":"codeVoice","code":"disconnected"},{"type":"text","text":" call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallError"}],"url":"\/documentation\/talksdk\/talkcallerror"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"role":"symbol","title":"Talk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"abstract":[{"type":"text","text":"An entry point into Talk SDK for iOS."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"url":"\/documentation\/talksdk\/talk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallErrorDomain":{"role":"symbol","title":"TalkCallErrorDomain","fragments":[{"kind":"identifier","text":"TalkCallErrorDomain"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallErrorDomain","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/talkcallerrordomain"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/LineStatus":{"role":"symbol","title":"LineStatus","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineStatus"}],"abstract":[{"type":"text","text":"Comprehensive information about status of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineStatus"}],"url":"\/documentation\/talksdk\/linestatus"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen":{"role":"symbol","title":"MicrophonePermissionScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MicrophonePermissionScreen"}],"abstract":[{"type":"text","text":"Screen handling microphone permission configuration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MicrophonePermissionScreen"}],"url":"\/documentation\/talksdk\/microphonepermissionscreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AgentStatusError":{"role":"symbol","title":"AgentStatusError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgentStatusError"}],"abstract":[{"type":"text","text":"Represents errors occuring during "},{"type":"codeVoice","code":"lineStatus"},{"type":"text","text":" check."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AgentStatusError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgentStatusError"}],"url":"\/documentation\/talksdk\/agentstatuserror"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen":{"role":"symbol","title":"CallScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallScreen"}],"abstract":[{"type":"text","text":"A screen presented for an ongoing call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallScreen"}],"url":"\/documentation\/talksdk\/callscreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallLoadingView":{"role":"symbol","title":"CallLoadingView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallLoadingView"}],"abstract":[{"type":"text","text":"Represent the loading view with activity indicator on the call screen."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallLoadingView"}],"url":"\/documentation\/talksdk\/callloadingview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen":{"role":"symbol","title":"RecordingConsentScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentScreen"}],"abstract":[{"type":"text","text":"Screen handling recording consent."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentScreen"}],"url":"\/documentation\/talksdk\/recordingconsentscreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView":{"role":"symbol","title":"CallButtonsView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallButtonsView"}],"abstract":[{"type":"text","text":"Represent the bottom buttons view in call screen."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallButtonsView"}],"url":"\/documentation\/talksdk\/callbuttonsview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController":{"role":"symbol","title":"CallConfigurationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationViewController"}],"abstract":[{"type":"text","text":"A view controller that is displayed before making a call, used to ask the user about necessary permissions that need to be granted."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallConfigurationViewController"}],"url":"\/documentation\/talksdk\/callconfigurationviewcontroller"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView":{"role":"symbol","title":"CallErrorView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallErrorView"}],"abstract":[{"type":"text","text":"Represent the error view with "},{"type":"codeVoice","code":"retry"},{"type":"text","text":" and "},{"type":"codeVoice","code":"cancel"},{"type":"text","text":" buttons."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallErrorView"}],"url":"\/documentation\/talksdk\/callerrorview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkSDKVersionString":{"role":"symbol","title":"TalkSDKVersionString","fragments":[{"kind":"identifier","text":"TalkSDKVersionString"}],"abstract":[{"type":"text","text":"Project version string for TalkSDK."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkSDKVersionString","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/talksdkversionstring"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCoreProvider":{"role":"symbol","title":"TalkCoreProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCoreProvider"}],"abstract":[{"type":"text","text":"Main "},{"type":"codeVoice","code":"Talk"},{"type":"text","text":" provider, responsible for the core calling API functionality."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCoreProvider"}],"url":"\/documentation\/talksdk\/talkcoreprovider"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType":{"role":"symbol","title":"AudioRoutingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioRoutingType"}],"abstract":[{"type":"text","text":"Describes type of an audio routing option."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioRoutingType"}],"url":"\/documentation\/talksdk\/audioroutingtype"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus":{"role":"symbol","title":"CallStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallStatus"}],"abstract":[{"type":"text","text":"Represents all possible states of the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatus"}],"url":"\/documentation\/talksdk\/callstatus"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkSDKVersionNumber":{"role":"symbol","title":"TalkSDKVersionNumber","fragments":[{"kind":"identifier","text":"TalkSDKVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for TalkSDK."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkSDKVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/talksdkversionnumber"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData":{"role":"symbol","title":"TalkCallData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallData"}],"abstract":[{"type":"codeVoice","code":"CallData"},{"type":"text","text":" conforming class that represents parameters required to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallData"}],"url":"\/documentation\/talksdk\/talkcalldata"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallSummary":{"role":"symbol","title":"CallSummary","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallSummary"}],"abstract":[{"type":"text","text":"Represents details of a finished call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallSummary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallSummary"}],"url":"\/documentation\/talksdk\/callsummary"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallTimerView":{"role":"symbol","title":"CallTimerView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallTimerView"}],"abstract":[{"type":"text","text":"Represent the timer view with a label showing call’s duration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallTimerView"}],"url":"\/documentation\/talksdk\/calltimerview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData":{"role":"symbol","title":"CallData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallData"}],"abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallData"}],"url":"\/documentation\/talksdk\/calldata"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkScreenProvider":{"role":"symbol","title":"TalkScreenProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkScreenProvider"}],"abstract":[{"type":"text","text":"Screen provider, responsible for creating preconfigured and ready to use call configuration and call view controllers."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkScreenProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkScreenProvider"}],"url":"\/documentation\/talksdk\/talkscreenprovider"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen":{"role":"symbol","title":"CallConfigurationScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationScreen"}],"abstract":[{"type":"text","text":"A screen presented before making a call, used to ask the user about necessary permissions that need to be granted."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallConfigurationScreen"}],"url":"\/documentation\/talksdk\/callconfigurationscreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput":{"role":"symbol","title":"AudioOutput","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOutput"}],"abstract":[{"type":"text","text":"Describes possible options for audio playback during the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioOutput"}],"url":"\/documentation\/talksdk\/audiooutput"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent":{"role":"symbol","title":"RecordingConsent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsent"}],"abstract":[{"type":"text","text":"Represents digital line’s recording consent configuration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsent"}],"url":"\/documentation\/talksdk\/recordingconsent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData"]},{"title":"Protocols","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall"]},{"title":"Variables","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallErrorDomain","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkSDKVersionNumber","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkSDKVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption\/title","value":"AudioRoutingOption"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption\/fragments","value":[{"kind":"identifier","text":"AudioRoutingOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/title","value":"CallViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/fragments","value":[{"kind":"identifier","text":"CallViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/title","value":"RecordingConsentAnswer"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/title","value":"TalkCall"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/fragments","value":[{"kind":"identifier","text":"TalkCall"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/title","value":"TalkCallError"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/fragments","value":[{"kind":"identifier","text":"TalkCallError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","value":"ZDKTalk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/title","value":"LineStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/fragments","value":[{"kind":"identifier","text":"LineStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/title","value":"MicrophonePermissionScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/fragments","value":[{"kind":"identifier","text":"MicrophonePermissionScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/title","value":"CallScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/fragments","value":[{"kind":"identifier","text":"CallScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView\/title","value":"CallLoadingView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView\/fragments","value":[{"kind":"identifier","text":"CallLoadingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/title","value":"RecordingConsentScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/fragments","value":[{"kind":"identifier","text":"RecordingConsentScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/title","value":"CallButtonsView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/fragments","value":[{"kind":"identifier","text":"CallButtonsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/title","value":"CallConfigurationViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/fragments","value":[{"kind":"identifier","text":"CallConfigurationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/title","value":"CallErrorView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/fragments","value":[{"kind":"identifier","text":"CallErrorView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType\/title","value":"AudioRoutingType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType\/fragments","value":[{"kind":"identifier","text":"AudioRoutingType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/title","value":"CallStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/fragments","value":[{"kind":"identifier","text":"CallStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/title","value":"ZDKTalkCallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/fragments","value":[{"kind":"identifier","text":"ZDKTalkCallData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView\/title","value":"CallTimerView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView\/fragments","value":[{"kind":"identifier","text":"CallTimerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/title","value":"CallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/fragments","value":[{"kind":"identifier","text":"CallData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/title","value":"CallConfigurationScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/fragments","value":[{"kind":"identifier","text":"CallConfigurationScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput\/title","value":"AudioOutput"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput\/fragments","value":[{"kind":"identifier","text":"AudioOutput"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/title","value":"RecordingConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/fragments","value":[{"kind":"identifier","text":"RecordingConsent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}