{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentAnswer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer","text":"RecordingConsentAnswer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talkcalldata\/recordingconsentanswer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talkcalldata\/recordingconsentanswer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/recordingConsentAnswer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Answer received from end user about recording the call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentAnswer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer"}],"title":"recordingConsentAnswer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@TalkSDK@objc(cs)ZDKTalkCallData(py)recordingConsentAnswer","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"recordingConsentAnswer"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData/recordingConsentAnswer":{"role":"symbol","title":"recordingConsentAnswer","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentAnswer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer"}],"abstract":[{"type":"text","text":"Answer received from end user about recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData\/recordingConsentAnswer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recordingConsentAnswer"}],"url":"\/documentation\/talksdk\/talkcalldata\/recordingconsentanswer"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer":{"role":"symbol","title":"RecordingConsentAnswer","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentAnswer"}],"abstract":[{"type":"text","text":"Represents the answer received from end user about recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswer"}],"url":"\/documentation\/talksdk\/recordingconsentanswer"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData":{"role":"symbol","title":"TalkCallData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallData"}],"abstract":[{"type":"codeVoice","code":"CallData"},{"type":"text","text":" conforming class that represents parameters required to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallData"}],"url":"\/documentation\/talksdk\/talkcalldata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recordingConsentAnswer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"recordingConsentAnswer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer","text":"RecordingConsentAnswer"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentAnswer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1recordingConsentAnswer\/title","value":"recordingConsentAnswer"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData~1recordingConsentAnswer\/fragments","value":[{"kind":"identifier","text":"recordingConsentAnswer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/title","value":"RecordingConsentAnswer"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/title","value":"ZDKTalkCallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/fragments","value":[{"kind":"identifier","text":"ZDKTalkCallData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}