{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speakerTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callbuttonsview\/speakertitlelabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callbuttonsview\/speakertitlelabel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/speakerTitleLabel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"speakerTitleLabel"}],"role":"symbol","title":"speakerTitleLabel","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speakerTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)CallButtonsView(py)speakerTitleLabel","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView":{"role":"symbol","title":"CallButtonsView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallButtonsView"}],"abstract":[{"type":"text","text":"Represent the bottom buttons view in call screen."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallButtonsView"}],"url":"\/documentation\/talksdk\/callbuttonsview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView/speakerTitleLabel":{"navigatorTitle":[{"kind":"identifier","text":"speakerTitleLabel"}],"role":"symbol","title":"speakerTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speakerTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/speakerTitleLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callbuttonsview\/speakertitlelabel"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"speakerTitleLabel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"speakerTitleLabel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"speakerTitleLabel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/title","value":"CallButtonsView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/fragments","value":[{"kind":"identifier","text":"CallButtonsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1speakerTitleLabel\/title","value":"speakerTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1speakerTitleLabel\/fragments","value":[{"kind":"identifier","text":"speakerTitleLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}