{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"microphoneScreen"},{"kind":"text","text":": "},{"text":"MicrophonePermissionScreen","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen","preciseIdentifier":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen"]]},"metadata":{"navigatorTitle":[{"text":"microphoneScreen","kind":"identifier"}],"externalID":"c:@M@TalkSDK@objc(pl)CallConfigurationScreen(py)microphoneScreen","roleHeading":"Instance Property","symbolKind":"property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"microphoneScreen","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MicrophonePermissionScreen","preciseIdentifier":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen"}],"role":"symbol","title":"microphoneScreen","modules":[{"name":"TalkSDK"}]},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/microphoneScreen","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Container for UI elements shown as Microphone permission screen. Enables customization of UI controls such as font, text colors, etc.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callconfigurationscreen\/microphonescreen"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callconfigurationscreen\/microphonescreen"]}],"sections":[],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen":{"title":"CallConfigurationScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","url":"\/documentation\/talksdk\/callconfigurationscreen","navigatorTitle":[{"text":"CallConfigurationScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A screen presented before making a call, used to ask the user about necessary permissions that need to be granted."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationScreen"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MicrophonePermissionScreen","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MicrophonePermissionScreen","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen","url":"\/documentation\/talksdk\/microphonepermissionscreen","role":"symbol","title":"MicrophonePermissionScreen","kind":"symbol","abstract":[{"type":"text","text":"Screen handling microphone permission configuration."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/microphoneScreen":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"microphoneScreen","kind":"identifier"},{"kind":"text","text":": "},{"text":"MicrophonePermissionScreen","preciseIdentifier":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"microphoneScreen","kind":"identifier"}],"url":"\/documentation\/talksdk\/callconfigurationscreen\/microphonescreen","abstract":[{"type":"text","text":"Container for UI elements shown as Microphone permission screen. Enables customization of UI controls such as font, text colors, etc."}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/microphoneScreen","role":"symbol","type":"topic","title":"microphoneScreen"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"microphoneScreen"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"microphoneScreen"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"id<MicrophonePermissionScreen>","preciseIdentifier":"c:Qo@M@TalkSDK@objc(pl)MicrophonePermissionScreen"},{"kind":"text","text":" * "},{"text":"microphoneScreen","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/title","value":"CallConfigurationScreen"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/fragments","value":[{"kind":"identifier","text":"CallConfigurationScreen"}],"op":"replace"},{"value":"MicrophonePermissionScreen","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/title"},{"op":"replace","value":[{"text":"MicrophonePermissionScreen","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/fragments"},{"value":"microphoneScreen","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1microphoneScreen\/title"},{"value":[{"kind":"identifier","text":"microphoneScreen"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1microphoneScreen\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}