{"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recordingConsentScreen"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecordingConsentScreen","preciseIdentifier":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen"}],"symbolKind":"property","modules":[{"name":"TalkSDK"}],"title":"recordingConsentScreen","navigatorTitle":[{"kind":"identifier","text":"recordingConsentScreen"}],"externalID":"c:@M@TalkSDK@objc(pl)CallConfigurationScreen(py)recordingConsentScreen","required":true},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callconfigurationscreen\/recordingconsentscreen"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callconfigurationscreen\/recordingconsentscreen"]}],"abstract":[{"type":"text","text":"Container for UI elements shown as Recording Consent screen. Enables customization of UI controls such as font, text colors, etc."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recordingConsentScreen","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","text":"RecordingConsentScreen"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/recordingConsentScreen","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen":{"title":"CallConfigurationScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","url":"\/documentation\/talksdk\/callconfigurationscreen","navigatorTitle":[{"text":"CallConfigurationScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A screen presented before making a call, used to ask the user about necessary permissions that need to be granted."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationScreen"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen":{"title":"RecordingConsentScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","url":"\/documentation\/talksdk\/recordingconsentscreen","navigatorTitle":[{"text":"RecordingConsentScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Screen handling recording consent.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RecordingConsentScreen","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/recordingConsentScreen":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentScreen"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen","text":"RecordingConsentScreen"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/recordingConsentScreen","title":"recordingConsentScreen","navigatorTitle":[{"text":"recordingConsentScreen","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Container for UI elements shown as Recording Consent screen. Enables customization of UI controls such as font, text colors, etc."}],"url":"\/documentation\/talksdk\/callconfigurationscreen\/recordingconsentscreen"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"recordingConsentScreen","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"recordingConsentScreen"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@TalkSDK@objc(pl)RecordingConsentScreen","text":"id<RecordingConsentScreen>"},{"text":" * ","kind":"text"},{"text":"recordingConsentScreen","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/title","op":"replace","value":"CallConfigurationScreen"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/fragments","value":[{"text":"CallConfigurationScreen","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/title","op":"replace","value":"RecordingConsentScreen"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/fragments","value":[{"kind":"identifier","text":"RecordingConsentScreen"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1recordingConsentScreen\/title","value":"recordingConsentScreen","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1recordingConsentScreen\/fragments","value":[{"text":"recordingConsentScreen","kind":"identifier"}],"op":"replace"}]}]}