{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"StartCallHandler","kind":"identifier"}],"role":"symbol","title":"CallConfigurationScreen.StartCallHandler","modules":[{"name":"TalkSDK"}],"externalID":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"StartCallHandler","kind":"identifier"}],"symbolKind":"typealias","roleHeading":"Type Alias"},"abstract":[{"type":"text","text":"Handler type which is called when all call configuration steps are completed (microphone permission is granted and recording consent configuration is fetched and answered) and call can be made."}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/StartCallHandler-swift.typealias","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-swift.typealias"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartCallHandler"},{"text":" = (","kind":"text"},{"text":"RecordingConsentAnswer","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer":{"title":"RecordingConsentAnswer","abstract":[{"type":"text","text":"Represents the answer received from end user about recording the call."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecordingConsentAnswer","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","url":"\/documentation\/talksdk\/recordingconsentanswer","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswer"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen":{"title":"CallConfigurationScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","url":"\/documentation\/talksdk\/callconfigurationscreen","navigatorTitle":[{"text":"CallConfigurationScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A screen presented before making a call, used to ask the user about necessary permissions that need to be granted."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationScreen"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/StartCallHandler-swift.typealias":{"kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-swift.typealias","role":"symbol","title":"CallConfigurationScreen.StartCallHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"StartCallHandler","kind":"identifier"}],"abstract":[{"type":"text","text":"Handler type which is called when all call configuration steps are completed (microphone permission is granted and recording consent configuration is fetched and answered) and call can be made."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/StartCallHandler-swift.typealias","navigatorTitle":[{"text":"StartCallHandler","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/title","value":"RecordingConsentAnswer","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/fragments","op":"replace","value":[{"kind":"identifier","text":"RecordingConsentAnswer"}]},{"value":"CallConfigurationScreen","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallConfigurationScreen"}]}]}]}