{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCallHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera","text":"StartCallHandler","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/StartCallHandler-swift.typealias"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-c.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-c.property"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"TalkSDK"}],"externalID":"c:@M@TalkSDK@objc(pl)CallConfigurationScreen(py)startCallHandler","title":"startCallHandler","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startCallHandler"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera","kind":"typeIdentifier","text":"StartCallHandler"},{"text":"?","kind":"text"}],"required":true,"navigatorTitle":[{"text":"startCallHandler","kind":"identifier"}],"symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen"]]},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/startCallHandler-c.property","interfaceLanguage":"swift"},"abstract":[{"text":"Handler called after completing the configuration, it will be called with user’s ","type":"text"},{"type":"codeVoice","code":"RecordingConsentAnswer"},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/StartCallHandler-swift.typealias":{"kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-swift.typealias","role":"symbol","title":"CallConfigurationScreen.StartCallHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"StartCallHandler","kind":"identifier"}],"abstract":[{"type":"text","text":"Handler type which is called when all call configuration steps are completed (microphone permission is granted and recording consent configuration is fetched and answered) and call can be made."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/StartCallHandler-swift.typealias","navigatorTitle":[{"text":"StartCallHandler","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/startCallHandler-c.property":{"kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-c.property","role":"symbol","title":"startCallHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"startCallHandler","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera","kind":"typeIdentifier","text":"StartCallHandler"},{"kind":"text","text":"?"}],"required":true,"abstract":[{"text":"Handler called after completing the configuration, it will be called with user’s ","type":"text"},{"type":"codeVoice","code":"RecordingConsentAnswer"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/startCallHandler-c.property","navigatorTitle":[{"kind":"identifier","text":"startCallHandler"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen":{"title":"CallConfigurationScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","url":"\/documentation\/talksdk\/callconfigurationscreen","navigatorTitle":[{"text":"CallConfigurationScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A screen presented before making a call, used to ask the user about necessary permissions that need to be granted."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationScreen"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"startCallHandler","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"startCallHandler"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:BFv(#$@M@TalkSDK@E@RecordingConsentAnswer)","text":"void (^)(enum RecordingConsentAnswer)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"startCallHandler","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"startCallHandler","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1startCallHandler-c.property\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1startCallHandler-c.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"startCallHandler"}]},{"value":"CallConfigurationScreen","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CallConfigurationScreen"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/fragments","op":"replace"}]}]}