{"metadata":{"externalID":"c:@M@TalkSDK@E@TalkCallError@TalkCallErrorNetworkError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"role":"symbol","roleHeading":"Case","title":"TalkCallError.networkError","symbolKind":"case","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorNetworkError"}]},"abstract":[{"text":"Establishing the call failed because of network issues.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/networkError","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/talkcallerror\/networkerror"]},{"paths":["\/documentation\/talksdk\/talkcallerror\/networkerror"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/networkError":{"kind":"symbol","abstract":[{"type":"text","text":"Establishing the call failed because of network issues."}],"role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/networkError","url":"\/documentation\/talksdk\/talkcallerror\/networkerror","type":"topic","title":"TalkCallError.networkError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorNetworkError"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TalkCallError","kind":"identifier"}],"abstract":[{"text":"Represents errors occuring for a ","type":"text"},{"type":"codeVoice","code":"failed"},{"type":"text","text":" or "},{"code":"disconnected","type":"codeVoice"},{"text":" call.","type":"text"}],"kind":"symbol","title":"TalkCallError","role":"symbol","url":"\/documentation\/talksdk\/talkcallerror","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError","type":"topic","navigatorTitle":[{"text":"TalkCallError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"TalkCallErrorNetworkError","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TalkCallErrorNetworkError"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"TalkCallErrorNetworkError"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1networkError\/title","value":"TalkCallErrorNetworkError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1networkError\/fragments","value":[{"kind":"identifier","text":"TalkCallErrorNetworkError"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/title","value":"TalkCallError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/fragments","value":[{"text":"TalkCallError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}