{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unauthorized"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorUnauthorized"}],"symbolKind":"case","title":"TalkCallError.unauthorized","externalID":"c:@M@TalkSDK@E@TalkCallError@TalkCallErrorUnauthorized","modules":[{"name":"TalkSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unauthorized"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/unauthorized"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/talkcallerror\/unauthorized"]},{"paths":["\/documentation\/talksdk\/talkcallerror\/unauthorized"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError"]]},"abstract":[{"type":"text","text":"The app is not authorized to make a call."}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/unauthorized":{"title":"TalkCallError.unauthorized","type":"topic","kind":"symbol","url":"\/documentation\/talksdk\/talkcallerror\/unauthorized","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorUnauthorized"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/unauthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unauthorized"}],"abstract":[{"type":"text","text":"The app is not authorized to make a call."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TalkCallError","kind":"identifier"}],"abstract":[{"text":"Represents errors occuring for a ","type":"text"},{"type":"codeVoice","code":"failed"},{"type":"text","text":" or "},{"code":"disconnected","type":"codeVoice"},{"text":" call.","type":"text"}],"kind":"symbol","title":"TalkCallError","role":"symbol","url":"\/documentation\/talksdk\/talkcallerror","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError","type":"topic","navigatorTitle":[{"text":"TalkCallError","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"TalkCallErrorUnauthorized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"TalkCallErrorUnauthorized","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"TalkCallErrorUnauthorized","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"TalkCallErrorUnauthorized","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1unauthorized\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1unauthorized\/fragments","op":"replace","value":[{"text":"TalkCallErrorUnauthorized","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/title","op":"replace","value":"TalkCallError"},{"value":[{"text":"TalkCallError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/fragments"}]}]}