{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorUnknown"}],"externalID":"c:@M@TalkSDK@E@TalkCallError@TalkCallErrorUnknown","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"title":"TalkCallError.unknown","modules":[{"name":"TalkSDK"}],"symbolKind":"case"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/talkcallerror\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/talkcallerror\/unknown"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/unknown"},"abstract":[{"text":"An unknown error occurred while establishing the call.","type":"text"}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TalkCallError","kind":"identifier"}],"abstract":[{"text":"Represents errors occuring for a ","type":"text"},{"type":"codeVoice","code":"failed"},{"type":"text","text":" or "},{"code":"disconnected","type":"codeVoice"},{"text":" call.","type":"text"}],"kind":"symbol","title":"TalkCallError","role":"symbol","url":"\/documentation\/talksdk\/talkcallerror","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError","type":"topic","navigatorTitle":[{"text":"TalkCallError","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/unknown":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"type":"topic","title":"TalkCallError.unknown","kind":"symbol","url":"\/documentation\/talksdk\/talkcallerror\/unknown","navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorUnknown"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/unknown","abstract":[{"text":"An unknown error occurred while establishing the call.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"TalkCallErrorUnknown"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"TalkCallErrorUnknown","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"TalkCallErrorUnknown","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/title","value":"TalkCallError","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/fragments","value":[{"kind":"identifier","text":"TalkCallError"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1unknown\/title","value":"TalkCallErrorUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1unknown\/fragments","value":[{"text":"TalkCallErrorUnknown","kind":"identifier"}]}]}]}