{"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen"]]},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callLoadingView","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callLoadingView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallLoadingView","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView","text":"CallLoadingView"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Loading view with activity indicator."}],"variants":[{"paths":["\/documentation\/talksdk\/callscreen\/callloadingview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callscreen\/callloadingview"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"TalkSDK"}],"symbolKind":"property","navigatorTitle":[{"text":"callLoadingView","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callLoadingView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallLoadingView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallLoadingView"}],"required":true,"externalID":"c:@M@TalkSDK@objc(pl)CallScreen(py)callLoadingView","title":"callLoadingView","role":"symbol"},"kind":"symbol","references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen":{"type":"topic","abstract":[{"text":"A screen presented for an ongoing call.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallScreen","kind":"identifier"}],"title":"CallScreen","url":"\/documentation\/talksdk\/callscreen","role":"symbol","navigatorTitle":[{"text":"CallScreen","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallLoadingView":{"title":"CallLoadingView","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView","url":"\/documentation\/talksdk\/callloadingview","navigatorTitle":[{"text":"CallLoadingView","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Represent the loading view with activity indicator on the call screen."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CallLoadingView","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen/callLoadingView":{"title":"callLoadingView","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/callLoadingView","url":"\/documentation\/talksdk\/callscreen\/callloadingview","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callLoadingView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"kind":"typeIdentifier","text":"CallLoadingView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallLoadingView"}],"navigatorTitle":[{"text":"callLoadingView","kind":"identifier"}],"abstract":[{"type":"text","text":"Loading view with activity indicator."}],"kind":"symbol","type":"topic","required":true},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"callLoadingView","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"callLoadingView","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"UIView<CallLoadingView>","preciseIdentifier":"c:Q$objc(cs)UIView@M@TalkSDK@objc(pl)CallLoadingView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"callLoadingView"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"CallScreen","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CallScreen"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/fragments"},{"value":"CallLoadingView","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView\/fragments","value":[{"kind":"identifier","text":"CallLoadingView"}]},{"value":"callLoadingView","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callLoadingView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1callLoadingView\/fragments","value":[{"kind":"identifier","text":"callLoadingView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}