{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnect","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"It is possible to manually disconnect the call from every state of the call. After disconnecting, the "},{"type":"codeVoice","code":"callDidFinishHandler"},{"type":"text","text":" is called."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Disconnects the call."}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@TalkSDK@objc(pl)CallScreen(im)disconnect","role":"symbol","title":"disconnect()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"disconnect","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"TalkSDK"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"disconnect"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/disconnect()"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen"]]},"variants":[{"paths":["\/documentation\/talksdk\/callscreen\/disconnect()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callscreen\/disconnect()"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen":{"type":"topic","abstract":[{"text":"A screen presented for an ongoing call.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallScreen","kind":"identifier"}],"title":"CallScreen","url":"\/documentation\/talksdk\/callscreen","role":"symbol","navigatorTitle":[{"text":"CallScreen","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen/disconnect()":{"type":"topic","abstract":[{"text":"Disconnects the call.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen\/disconnect()","url":"\/documentation\/talksdk\/callscreen\/disconnect()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"disconnect","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","required":true,"navigatorTitle":[{"text":"disconnect","kind":"identifier"}],"title":"disconnect()"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"disconnect","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disconnect"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"disconnect","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"CallScreen","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/fragments","value":[{"text":"CallScreen","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1disconnect()\/title","op":"replace","value":"disconnect"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen~1disconnect()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"disconnect"}],"op":"replace"}]}]}