{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea","text":"DigitalLine"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/calldata\/digitalline"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/calldata\/digitalline"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData\/digitalLine","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Name of digital line configured by the admin in Talk Settings."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"digitalLine"}],"role":"symbol","title":"digitalLine","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)CallData(py)digitalLine","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData/digitalLine":{"navigatorTitle":[{"kind":"identifier","text":"digitalLine"}],"role":"symbol","title":"digitalLine","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"}],"abstract":[{"type":"text","text":"Name of digital line configured by the admin in Talk Settings."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData\/digitalLine","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/calldata\/digitalline"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/DigitalLine":{"role":"symbol","title":"DigitalLine","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalLine"}],"abstract":[{"type":"text","text":"Name of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DigitalLine"}],"url":"\/documentation\/talksdk\/digitalline"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData":{"role":"symbol","title":"CallData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallData"}],"abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallData"}],"url":"\/documentation\/talksdk\/calldata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"digitalLine"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"digitalLine"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"digitalLine"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData~1digitalLine\/title","value":"digitalLine"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData~1digitalLine\/fragments","value":[{"kind":"identifier","text":"digitalLine"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/title","value":"CallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/fragments","value":[{"kind":"identifier","text":"CallData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}