{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentAnswer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer","text":"RecordingConsentAnswer"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/calldata\/recordingconsentanswer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/calldata\/recordingconsentanswer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData\/recordingConsentAnswer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Answer received from end user about recording the call."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"recordingConsentAnswer"}],"role":"symbol","title":"recordingConsentAnswer","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentAnswer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)CallData(py)recordingConsentAnswer","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData/recordingConsentAnswer":{"navigatorTitle":[{"kind":"identifier","text":"recordingConsentAnswer"}],"role":"symbol","title":"recordingConsentAnswer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentAnswer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer"}],"abstract":[{"type":"text","text":"Answer received from end user about recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData\/recordingConsentAnswer","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/calldata\/recordingconsentanswer"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer":{"role":"symbol","title":"RecordingConsentAnswer","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentAnswer"}],"abstract":[{"type":"text","text":"Represents the answer received from end user about recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswer"}],"url":"\/documentation\/talksdk\/recordingconsentanswer"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData":{"role":"symbol","title":"CallData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallData"}],"abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallData"}],"url":"\/documentation\/talksdk\/calldata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"recordingConsentAnswer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"recordingConsentAnswer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer","text":"RecordingConsentAnswer"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentAnswer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData~1recordingConsentAnswer\/title","value":"recordingConsentAnswer"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData~1recordingConsentAnswer\/fragments","value":[{"kind":"identifier","text":"recordingConsentAnswer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/title","value":"RecordingConsentAnswer"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/title","value":"CallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/fragments","value":[{"kind":"identifier","text":"CallData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}