{"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallViewController(with:callDidFinishHandler:)-1jwxw"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeCallViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"callData","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData","text":"CallData","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData"},{"text":", ","kind":"text"},{"text":"callDidFinishHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"duration","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":" & "},{"text":"CallScreen","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallScreen","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen","kind":"typeIdentifier"}]}]},{"parameters":[{"name":"callData","content":[{"inlineContent":[{"type":"text","text":"Data which contains all required call details such as "},{"code":"DigitaLine","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RecordingConsentAnswer"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"callDidFinishHandler","content":[{"inlineContent":[{"text":"Handler which will be called when the call is finished with CallScreen and CallSummary as parameters. Will be called for both success and failure scenarios.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"CallScreen","type":"codeVoice"},{"type":"text","text":" which is also "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":" with all configured UI and logic for making calls."}]}],"kind":"content"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Before showing that screen you may want to check ","type":"text"},{"code":"microphone permission","type":"codeVoice"},{"type":"text","text":", "},{"code":"digital line","type":"codeVoice"},{"type":"text","text":" status, and "},{"type":"codeVoice","code":"recording consent"},{"type":"text","text":" first."},{"type":"text","text":" "},{"text":"You can use this already prepared view controller, with all required logic for making calls.","type":"text"}]}],"kind":"content"}],"abstract":[{"text":"Returns Call View Controller","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/talk\/makecallviewcontroller(with:calldidfinishhandler:)-1jwxw"]},{"paths":["\/documentation\/talksdk\/talk\/makecallviewcontroller(with:calldidfinishhandler:)-1jwxw"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"makeCallViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callDidFinishHandler"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallScreen","text":"CallScreen","kind":"typeIdentifier"}],"extendedModule":"TalkSDK","navigatorTitle":[{"text":"makeCallViewControllerWith:callDidFinishHandler:","kind":"identifier"}],"platforms":[],"externalID":"c:@CM@TalkSDK@objc(cs)ZDKTalk(im)makeCallViewControllerWith:callDidFinishHandler:","title":"makeCallViewController(with:callDidFinishHandler:)","role":"symbol","modules":[{"name":"TalkSDK"}],"roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/makeCallViewController(with:callDidFinishHandler:)-1jwxw":{"navigatorTitle":[{"text":"makeCallViewControllerWith:callDidFinishHandler:","kind":"identifier"}],"title":"makeCallViewController(with:callDidFinishHandler:)","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallViewController(with:callDidFinishHandler:)-1jwxw","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Returns Call View Controller"}],"kind":"symbol","url":"\/documentation\/talksdk\/talk\/makecallviewcontroller(with:calldidfinishhandler:)-1jwxw","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCallViewController"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData","text":"CallData","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"callDidFinishHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"duration","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":" & ","kind":"text"},{"text":"CallScreen","kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallScreen"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen":{"type":"topic","abstract":[{"text":"A screen presented for an ongoing call.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallScreen","kind":"identifier"}],"title":"CallScreen","url":"\/documentation\/talksdk\/callscreen","role":"symbol","navigatorTitle":[{"text":"CallScreen","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","navigatorTitle":[{"text":"CallData","kind":"identifier"}],"type":"topic","title":"CallData","url":"\/documentation\/talksdk\/calldata","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallData","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"title":"Talk","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","url":"\/documentation\/talksdk\/talk","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"type":"topic","kind":"symbol","abstract":[{"text":"An entry point into Talk SDK for iOS.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Talk","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"makeCallViewControllerWith:callDidFinishHandler:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"makeCallViewControllerWith:callDidFinishHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIViewController@M@TalkSDK@objc(pl)CallScreen","text":"UIViewController<CallScreen>"},{"text":" *) ","kind":"text"},{"text":"makeCallViewControllerWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<CallData>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"callData"},{"kind":"text","text":" "},{"kind":"identifier","text":"callDidFinishHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#d#*$objc(cs)NSError)","text":"void (^)(double, NSError *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"callDidFinishHandler","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"makeCallViewControllerWith:callDidFinishHandler:","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1makeCallViewController(with:callDidFinishHandler:)-1jwxw\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1makeCallViewController(with:callDidFinishHandler:)-1jwxw\/fragments","value":[{"text":"- ","kind":"text"},{"text":"makeCallViewControllerWith:callDidFinishHandler:","kind":"identifier"}],"op":"replace"},{"value":"CallScreen","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/title"},{"value":[{"kind":"identifier","text":"CallScreen"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/fragments"},{"value":"CallData","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/fragments","value":[{"text":"CallData","kind":"identifier"}],"op":"replace"},{"value":"ZDKTalk","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","op":"replace","value":[{"text":"ZDKTalk","kind":"identifier"}]}]}]}