{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/talk\/startcall(to:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/talk\/startcall(to:)"]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"startCallToDigitalLine:"}],"role":"symbol","extendedModule":"TalkSDK","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCall"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"},{"kind":"text","text":")"}],"modules":[{"name":"TalkSDK"}],"title":"startCall(to:)","externalID":"c:@CM@TalkSDK@objc(cs)ZDKTalk(im)startCallToDigitalLine:","symbolKind":"method"},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/startCall(to:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkFlowProvider-Implementations"]]},"kind":"symbol","abstract":[{"type":"text","text":"Starts the call flow. All screens are presented modally."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(startCallToDigitalLine:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startCall"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":" "},{"text":"digitalLine","kind":"internalParam"},{"kind":"text","text":": "},{"text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"digitalLine","content":[{"inlineContent":[{"type":"text","text":"name of digital line configured by the admin in Talk Settings"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"If necessary, first configuration screen is presented where the user is asked to grant microphone access permission (if were not provided earlier) and call recording consent (if required). After appropriate permissions are granted the call screen is presented and the call with agent will be started."}],"type":"paragraph"}]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/TalkFlowProvider-Implementations":{"title":"TalkFlowProvider Implementations","url":"\/documentation\/talksdk\/talk\/talkflowprovider-implementations","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkFlowProvider-Implementations","role":"collectionGroup"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"title":"Talk","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","url":"\/documentation\/talksdk\/talk","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"type":"topic","kind":"symbol","abstract":[{"text":"An entry point into Talk SDK for iOS.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Talk","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/DigitalLine":{"title":"DigitalLine","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalLine"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DigitalLine"}],"url":"\/documentation\/talksdk\/digitalline","kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","type":"topic","abstract":[{"type":"text","text":"Name of digital line."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/startCall(to:)":{"title":"startCall(to:)","url":"\/documentation\/talksdk\/talk\/startcall(to:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startCall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"DigitalLine","kind":"typeIdentifier","preciseIdentifier":"s:7TalkSDK11DigitalLinea"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Starts the call flow. All screens are presented modally.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/startCall(to:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startCallToDigitalLine:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"startCallToDigitalLine:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startCallToDigitalLine:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"startCallToDigitalLine:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"digitalLine","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKTalk","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title"},{"value":[{"text":"ZDKTalk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1startCall(to:)\/title","value":"startCallToDigitalLine:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"startCallToDigitalLine:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1startCall(to:)\/fragments"}]}]}