{"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk"]]},"metadata":{"title":"TalkScreenProvider Implementations","role":"collectionGroup","modules":[{"name":"TalkSDK"}]},"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/talk\/talkscreenprovider-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/talk\/talkscreenprovider-implementations"]}],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallConfigurationViewController(for:)","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallViewController(with:callDidFinishHandler:)-8h7uu"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkScreenProvider-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"title":"Talk","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","url":"\/documentation\/talksdk\/talk","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"type":"topic","kind":"symbol","abstract":[{"text":"An entry point into Talk SDK for iOS.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Talk","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/makeCallViewController(with:callDidFinishHandler:)-8h7uu":{"type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallViewController(with:callDidFinishHandler:)-8h7uu","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"makeCallViewController"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData","text":"CallData"},{"kind":"text","text":", "},{"text":"callDidFinishHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"CallScreenViewController","kind":"typeIdentifier","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP04CallC14ViewControllera"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"CallSummary","preciseIdentifier":"s:7TalkSDK11CallSummaryP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP04CallC14ViewControllera","text":"CallScreenViewController","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns Call View Controller"}],"title":"makeCallViewController(with:callDidFinishHandler:)","url":"\/documentation\/talksdk\/talk\/makecallviewcontroller(with:calldidfinishhandler:)-8h7uu"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/makeCallConfigurationViewController(for:)":{"kind":"symbol","abstract":[{"type":"text","text":"Returns Call Configuration view controller"}],"navigatorTitle":[{"text":"makeCallConfigurationViewControllerFor:","kind":"identifier"}],"url":"\/documentation\/talksdk\/talk\/makecallconfigurationviewcontroller(for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"makeCallConfigurationViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CallConfigurationScreenViewController","kind":"typeIdentifier","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP017CallConfigurationC14ViewControllera"}],"type":"topic","title":"makeCallConfigurationViewController(for:)","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallConfigurationViewController(for:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallConfigurationViewController(for:)","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallViewController(with:callDidFinishHandler:)-8h7uu"],"generated":true}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":"ZDKTalk","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKTalk"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments"},{"value":"makeCallConfigurationViewControllerFor:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1makeCallConfigurationViewController(for:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"makeCallConfigurationViewControllerFor:"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1makeCallConfigurationViewController(for:)\/fragments"}]}]}