{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/audiooutput\/speaker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/audiooutput\/speaker"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/speaker","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The call audio will be routed through the speakers."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker"}],"title":"AudioOutput.speaker","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@TalkSDK@E@AudioOutput@AudioOutputSpeaker","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AudioOutputSpeaker"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput":{"role":"symbol","title":"AudioOutput","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOutput"}],"abstract":[{"type":"text","text":"Describes possible options for audio playback during the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioOutput"}],"url":"\/documentation\/talksdk\/audiooutput"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput/speaker":{"role":"symbol","title":"AudioOutput.speaker","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"speaker"}],"abstract":[{"type":"text","text":"The call audio will be routed through the speakers."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput\/speaker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioOutputSpeaker"}],"url":"\/documentation\/talksdk\/audiooutput\/speaker"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AudioOutputSpeaker"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AudioOutputSpeaker"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AudioOutputSpeaker"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput\/title","value":"AudioOutput"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput\/fragments","value":[{"kind":"identifier","text":"AudioOutput"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput~1speaker\/title","value":"AudioOutputSpeaker"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput~1speaker\/fragments","value":[{"kind":"identifier","text":"AudioOutputSpeaker"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}