{"metadata":{"externalID":"c:@M@TalkSDK@objc(pl)CallButtonsView(py)hangUpButton","roleHeading":"Instance Property","title":"hangUpButton","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hangUpButton","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"kind":"text","text":"!"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"hangUpButton"}],"required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/hangUpButton"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Button for disconnecting the call."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callbuttonsview\/hangupbutton"]},{"paths":["\/documentation\/talksdk\/callbuttonsview\/hangupbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hangUpButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView":{"title":"CallButtonsView","url":"\/documentation\/talksdk\/callbuttonsview","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallButtonsView","kind":"identifier"}],"type":"topic","abstract":[{"text":"Represent the bottom buttons view in call screen.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","role":"symbol","navigatorTitle":[{"text":"CallButtonsView","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView/hangUpButton":{"type":"topic","navigatorTitle":[{"text":"hangUpButton","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Button for disconnecting the call.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hangUpButton","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/hangUpButton","url":"\/documentation\/talksdk\/callbuttonsview\/hangupbutton","title":"hangUpButton","kind":"symbol","required":true},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"hangUpButton","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"hangUpButton","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"kind":"text","text":" * "},{"text":"hangUpButton","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/title","value":"CallButtonsView"},{"value":[{"kind":"identifier","text":"CallButtonsView"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1hangUpButton\/title","value":"hangUpButton","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1hangUpButton\/fragments","op":"replace","value":[{"kind":"identifier","text":"hangUpButton"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}