{"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView"]]},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/hangUpTitleLabel","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","required":true,"externalID":"c:@M@TalkSDK@objc(pl)CallButtonsView(py)hangUpTitleLabel","modules":[{"name":"TalkSDK"}],"title":"hangUpTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hangUpTitleLabel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"},{"text":"!","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"hangUpTitleLabel"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hangUpTitleLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callbuttonsview\/hanguptitlelabel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callbuttonsview\/hanguptitlelabel"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView/hangUpTitleLabel":{"type":"topic","navigatorTitle":[{"text":"hangUpTitleLabel","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hangUpTitleLabel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/hangUpTitleLabel","url":"\/documentation\/talksdk\/callbuttonsview\/hanguptitlelabel","title":"hangUpTitleLabel","kind":"symbol","required":true},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView":{"title":"CallButtonsView","url":"\/documentation\/talksdk\/callbuttonsview","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallButtonsView","kind":"identifier"}],"type":"topic","abstract":[{"text":"Represent the bottom buttons view in call screen.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","role":"symbol","navigatorTitle":[{"text":"CallButtonsView","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"hangUpTitleLabel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"hangUpTitleLabel","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"},{"kind":"text","text":" * "},{"text":"hangUpTitleLabel","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1hangUpTitleLabel\/title","value":"hangUpTitleLabel"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1hangUpTitleLabel\/fragments","op":"replace","value":[{"text":"hangUpTitleLabel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/title","value":"CallButtonsView","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/fragments","value":[{"text":"CallButtonsView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}