{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"speakerButton"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"text":"! { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"By default it toggles the audio output between "},{"type":"codeVoice","code":"headset"},{"type":"text","text":" and "},{"type":"codeVoice","code":"speaker"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"When Bluetooth headset is available the button displays picker for changing the audio routing."}],"type":"paragraph"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView"]]},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/speakerButton","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"TalkSDK"}],"roleHeading":"Instance Property","symbolKind":"property","required":true,"navigatorTitle":[{"text":"speakerButton","kind":"identifier"}],"role":"symbol","externalID":"c:@M@TalkSDK@objc(pl)CallButtonsView(py)speakerButton","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"speakerButton","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"},{"kind":"text","text":"!"}],"title":"speakerButton"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callbuttonsview\/speakerbutton"]},{"paths":["\/documentation\/talksdk\/callbuttonsview\/speakerbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Button for changing the ongoing call’s audio configuration. It operates differently depending on Bluetooth enabled headsets being connnected to the device:"}],"kind":"symbol","sections":[],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView":{"title":"CallButtonsView","url":"\/documentation\/talksdk\/callbuttonsview","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallButtonsView","kind":"identifier"}],"type":"topic","abstract":[{"text":"Represent the bottom buttons view in call screen.","type":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","role":"symbol","navigatorTitle":[{"text":"CallButtonsView","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView/speakerButton":{"type":"topic","navigatorTitle":[{"text":"speakerButton","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Button for changing the ongoing call’s audio configuration. It operates differently depending on Bluetooth enabled headsets being connnected to the device:"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"speakerButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/speakerButton","url":"\/documentation\/talksdk\/callbuttonsview\/speakerbutton","title":"speakerButton","kind":"symbol","required":true},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"speakerButton","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"speakerButton","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":" * "},{"kind":"identifier","text":"speakerButton"}]}],"kind":"declarations"},"op":"replace"},{"value":"CallButtonsView","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/title","op":"replace"},{"value":[{"text":"CallButtonsView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/fragments"},{"op":"replace","value":"speakerButton","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1speakerButton\/title"},{"op":"replace","value":[{"text":"speakerButton","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1speakerButton\/fragments"}]}]}