{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/CancelRequestHandler","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP20CancelRequestHandlera","text":"CancelRequestHandler"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callconfigurationscreen\/cancelhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callconfigurationscreen\/cancelhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/cancelHandler","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Handler that is called when end user cancels the configuration at any time."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"cancelHandler"}],"role":"symbol","title":"cancelHandler","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CancelRequestHandler","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP20CancelRequestHandlera"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)CallConfigurationScreen(py)cancelHandler","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen":{"role":"symbol","title":"CallConfigurationScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationScreen"}],"abstract":[{"type":"text","text":"A screen presented before making a call, used to ask the user about necessary permissions that need to be granted."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallConfigurationScreen"}],"url":"\/documentation\/talksdk\/callconfigurationscreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/cancelHandler":{"navigatorTitle":[{"kind":"identifier","text":"cancelHandler"}],"role":"symbol","title":"cancelHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CancelRequestHandler","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP20CancelRequestHandlera"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Handler that is called when end user cancels the configuration at any time."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/cancelHandler","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callconfigurationscreen\/cancelhandler"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/CancelRequestHandler":{"role":"symbol","title":"CallConfigurationScreen.CancelRequestHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CancelRequestHandler"}],"abstract":[{"type":"text","text":"Handler type which is called when user taps on Cancel button on configuration screen."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/CancelRequestHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CancelRequestHandler"}],"url":"\/documentation\/talksdk\/callconfigurationscreen\/cancelrequesthandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cancelHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cancelHandler"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelHandler"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/title","value":"CallConfigurationScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/fragments","value":[{"kind":"identifier","text":"CallConfigurationScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1cancelHandler\/title","value":"cancelHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1cancelHandler\/fragments","value":[{"kind":"identifier","text":"cancelHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}