{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCallHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/StartCallHandler-swift.typealias","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera","text":"StartCallHandler"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/startCallHandler-swift.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Handler called after completing the configuration, it will be called with user’s "},{"type":"codeVoice","code":"RecordingConsentAnswer"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"startCallHandler"}],"role":"symbol","title":"startCallHandler","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCallHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StartCallHandler","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)CallConfigurationScreen(py)startCallHandler","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/StartCallHandler-swift.typealias":{"role":"symbol","title":"CallConfigurationScreen.StartCallHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"StartCallHandler"}],"abstract":[{"type":"text","text":"Handler type which is called when all call configuration steps are completed (microphone permission is granted and recording consent configuration is fetched and answered) and call can be made."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/StartCallHandler-swift.typealias","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StartCallHandler"}],"url":"\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-swift.typealias"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen":{"role":"symbol","title":"CallConfigurationScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationScreen"}],"abstract":[{"type":"text","text":"A screen presented before making a call, used to ask the user about necessary permissions that need to be granted."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallConfigurationScreen"}],"url":"\/documentation\/talksdk\/callconfigurationscreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/startCallHandler-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"startCallHandler"}],"role":"symbol","title":"startCallHandler","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCallHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StartCallHandler","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Handler called after completing the configuration, it will be called with user’s "},{"type":"codeVoice","code":"RecordingConsentAnswer"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/startCallHandler-swift.property","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-swift.property"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"startCallHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"startCallHandler"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"void (^)(enum RecordingConsentAnswer)","preciseIdentifier":"c:BFv(#$@M@TalkSDK@E@RecordingConsentAnswer)"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCallHandler"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/title","value":"CallConfigurationScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen\/fragments","value":[{"kind":"identifier","text":"CallConfigurationScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1startCallHandler-swift.property\/title","value":"startCallHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationScreen~1startCallHandler-swift.property\/fragments","value":[{"kind":"identifier","text":"startCallHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}