{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callloadingview\/activityindicator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callloadingview\/activityindicator"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView\/activityIndicator","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"activityIndicator"}],"role":"symbol","title":"activityIndicator","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)CallLoadingView(py)activityIndicator","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallLoadingView/activityIndicator":{"navigatorTitle":[{"kind":"identifier","text":"activityIndicator"}],"role":"symbol","title":"activityIndicator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView\/activityIndicator","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callloadingview\/activityindicator"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallLoadingView":{"role":"symbol","title":"CallLoadingView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallLoadingView"}],"abstract":[{"type":"text","text":"Represent the loading view with activity indicator on the call screen."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallLoadingView"}],"url":"\/documentation\/talksdk\/callloadingview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"activityIndicator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"activityIndicator"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"activityIndicator"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView~1activityIndicator\/title","value":"activityIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView~1activityIndicator\/fragments","value":[{"kind":"identifier","text":"activityIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView\/title","value":"CallLoadingView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView\/fragments","value":[{"kind":"identifier","text":"CallLoadingView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}