{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioRoutingOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/audioroutingoption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/audioroutingoption"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Describes possible options for routing call’s audio input and output."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioRoutingOption"}],"title":"AudioRoutingOption","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@TalkSDK@objc(pl)AudioRoutingOption","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AudioRoutingOption"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption\/name","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption\/type"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingOption/name":{"navigatorTitle":[{"kind":"identifier","text":"name"}],"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Localized name of the routing option."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption\/name","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/audioroutingoption\/name"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingOption/type":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioRoutingType","preciseIdentifier":"c:@M@TalkSDK@E@AudioRoutingType"}],"abstract":[{"type":"text","text":"Type of audio routing option."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption\/type","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/audioroutingoption\/type"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingOption":{"role":"symbol","title":"AudioRoutingOption","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioRoutingOption"}],"abstract":[{"type":"text","text":"Describes possible options for routing call’s audio input and output."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioRoutingOption"}],"url":"\/documentation\/talksdk\/audioroutingoption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AudioRoutingOption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AudioRoutingOption"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AudioRoutingOption"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption\/name","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingOption\/type"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioRoutingOption"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption\/title","value":"AudioRoutingOption"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingOption\/fragments","value":[{"kind":"identifier","text":"AudioRoutingOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}