{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallLoadingView"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When starting a call the SDK needs to prepare the call configuration."},{"type":"text","text":" "},{"type":"text","text":"At this time on the "},{"type":"codeVoice","code":"CallScreen"},{"type":"text","text":" an activity indicator with a title is shown."},{"type":"text","text":" "},{"type":"text","text":"This view has customizable font, text colors, background color, etc."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You cannot change layout of elements. In case you need your own layout setup, use other SDK API methods and build your own Call View."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callloadingview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callloadingview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represent the loading view with activity indicator on the call screen."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallLoadingView"}],"title":"CallLoadingView","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@TalkSDK@objc(pl)CallLoadingView","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CallLoadingView"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView\/activityIndicator","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView\/titleLabel"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallLoadingView":{"role":"symbol","title":"CallLoadingView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallLoadingView"}],"abstract":[{"type":"text","text":"Represent the loading view with activity indicator on the call screen."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallLoadingView"}],"url":"\/documentation\/talksdk\/callloadingview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallLoadingView/titleLabel":{"navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView\/titleLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callloadingview\/titlelabel"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallLoadingView/activityIndicator":{"navigatorTitle":[{"kind":"identifier","text":"activityIndicator"}],"role":"symbol","title":"activityIndicator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityIndicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView\/activityIndicator","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callloadingview\/activityindicator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"CallLoadingView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallLoadingView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CallLoadingView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView\/activityIndicator","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView\/titleLabel"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallLoadingView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView\/title","value":"CallLoadingView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView\/fragments","value":[{"kind":"identifier","text":"CallLoadingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView~1activityIndicator\/title","value":"activityIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView~1activityIndicator\/fragments","value":[{"kind":"identifier","text":"activityIndicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}