{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/objc(pl)AVRoutePickerViewDelegate","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen","doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSCoding","doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.TalkSDK\/s7CVarArgP","doc:\/\/com.zendesk.TalkSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.TalkSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.TalkSDK\/SQ","doc:\/\/com.zendesk.TalkSDK\/SH","doc:\/\/com.zendesk.TalkSDK\/s8SendableP","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIAppearanceContainer","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIContentContainer","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIFocusEnvironment","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIStateRestoring","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UITraitEnvironment","doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A view controller displayed for an ongoing call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallViewController"}],"title":"CallViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TalkSDK@objc(cs)CallViewController","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CallViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/init(callData:talk:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callButtonsView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callErrorView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callLoadingView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callTimerView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/disconnect()","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/viewDidLoad()","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/viewWillAppear(_:)","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/viewWillDisappear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/AVRoutePickerViewDelegate-Implementations"],"generated":true}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/AVRoutePickerViewDelegate-Implementations":{"role":"collectionGroup","title":"AVRoutePickerViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/AVRoutePickerViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/callviewcontroller\/avroutepickerviewdelegate-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/talksdk\/callviewcontroller\/viewwillappear(_:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/callLoadingView":{"role":"symbol","title":"callLoadingView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callLoadingView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallLoadingView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallLoadingView"}],"abstract":[{"type":"text","text":"Loading view with activity indicator."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callLoadingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callLoadingView"}],"url":"\/documentation\/talksdk\/callviewcontroller\/callloadingview"},"doc://com.zendesk.TalkSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIResponderStandardEditActions"},"doc://com.zendesk.TalkSDK/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIContentContainer"},"doc://com.zendesk.TalkSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UITraitEnvironment"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/callButtonsView":{"role":"symbol","title":"callButtonsView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callButtonsView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallButtonsView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallButtonsView"}],"abstract":[{"type":"text","text":"View containing call screen action buttons."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callButtonsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callButtonsView"}],"url":"\/documentation\/talksdk\/callviewcontroller\/callbuttonsview"},"doc://com.zendesk.TalkSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.zendesk.TalkSDK/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIStateRestoring"},"doc://com.zendesk.TalkSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.zendesk.TalkSDK\/s8SendableP"},"doc://com.zendesk.TalkSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.zendesk.TalkSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIAppearanceContainer"},"doc://com.zendesk.TalkSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.TalkSDK\/s7CVarArgP"},"doc://com.zendesk.TalkSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSObject"},"doc://com.zendesk.TalkSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIFocusEnvironment"},"doc://com.zendesk.TalkSDK/objc(pl)AVRoutePickerViewDelegate":{"type":"unresolvable","title":"AVKit.AVRoutePickerViewDelegate","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)AVRoutePickerViewDelegate"},"doc://com.zendesk.TalkSDK/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSExtensionRequestHandling"},"doc://com.zendesk.TalkSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.TalkSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSCoding"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/disconnect()":{"role":"symbol","title":"disconnect()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnect"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Disconnects the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/disconnect()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disconnect"}],"url":"\/documentation\/talksdk\/callviewcontroller\/disconnect()"},"doc://com.zendesk.TalkSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.TalkSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/init(callData:talk:)":{"role":"symbol","title":"init(callData:talk:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"talk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Talk","preciseIdentifier":"c:@M@TalkSDK@objc(cs)ZDKTalk"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/init(callData:talk:)","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callviewcontroller\/init(calldata:talk:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/callTimerView":{"role":"symbol","title":"callTimerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callTimerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallTimerView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallTimerView"}],"abstract":[{"type":"text","text":"Timer view displaying call duration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callTimerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callTimerView"}],"url":"\/documentation\/talksdk\/callviewcontroller\/calltimerview"},"doc://com.zendesk.TalkSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SQ"},"doc://com.zendesk.TalkSDK/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(cs)UIViewController"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController":{"role":"symbol","title":"CallViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallViewController"}],"abstract":[{"type":"text","text":"A view controller displayed for an ongoing call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}],"url":"\/documentation\/talksdk\/callviewcontroller"},"doc://com.zendesk.TalkSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SH"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallScreen":{"role":"symbol","title":"CallScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallScreen"}],"abstract":[{"type":"text","text":"A screen presented for an ongoing call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallScreen"}],"url":"\/documentation\/talksdk\/callscreen"},"doc://com.zendesk.TalkSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)UIUserActivityRestoring"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/callErrorView":{"role":"symbol","title":"callErrorView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callErrorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallErrorView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallErrorView"}],"abstract":[{"type":"text","text":"Error view with retry and cancel buttons."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callErrorView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callErrorView"}],"url":"\/documentation\/talksdk\/callviewcontroller\/callerrorview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/talksdk\/callviewcontroller\/viewdidload()"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/viewWillDisappear(_:)":{"role":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/viewWillDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"url":"\/documentation\/talksdk\/callviewcontroller\/viewwilldisappear(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CallViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CallViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callButtonsView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callErrorView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callLoadingView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callTimerView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/disconnect()","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/viewDidLoad()","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/viewWillAppear(_:)","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/viewWillDisappear(_:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/AVRoutePickerViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallScreen"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callLoadingView\/title","value":"callLoadingView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callLoadingView\/fragments","value":[{"kind":"identifier","text":"callLoadingView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callButtonsView\/title","value":"callButtonsView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callButtonsView\/fragments","value":[{"kind":"identifier","text":"callButtonsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1disconnect()\/title","value":"disconnect"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1disconnect()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disconnect"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callTimerView\/title","value":"callTimerView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callTimerView\/fragments","value":[{"kind":"identifier","text":"callTimerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/title","value":"CallViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/fragments","value":[{"kind":"identifier","text":"CallViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/title","value":"CallScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallScreen\/fragments","value":[{"kind":"identifier","text":"CallScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callErrorView\/title","value":"callErrorView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callErrorView\/fragments","value":[{"kind":"identifier","text":"callErrorView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}