{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallButtonsView"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This view contains buttons for: mute, change audio source and hang up actions."},{"type":"text","text":" "},{"type":"text","text":"The view contains buttons and matching title labels."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You cannot change layout of elements. In case you need your own layout setup, use other SDK API methods and build your own Call View."}]}],"type":"aside","name":"Important"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Labels with text under the buttons are not the part of the buttons."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callbuttonsview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callbuttonsview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represent the bottom buttons view in call screen."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallButtonsView"}],"title":"CallButtonsView","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@TalkSDK@objc(pl)CallButtonsView","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CallButtonsView"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/hangUpButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/hangUpTitleLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/muteButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/muteTitleLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/speakerButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/speakerTitleLabel"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView/muteButton":{"navigatorTitle":[{"kind":"identifier","text":"muteButton"}],"role":"symbol","title":"muteButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Button for muting\/unmuting the microphone."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/muteButton","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callbuttonsview\/mutebutton"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView/hangUpTitleLabel":{"navigatorTitle":[{"kind":"identifier","text":"hangUpTitleLabel"}],"role":"symbol","title":"hangUpTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hangUpTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/hangUpTitleLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callbuttonsview\/hanguptitlelabel"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView":{"role":"symbol","title":"CallButtonsView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallButtonsView"}],"abstract":[{"type":"text","text":"Represent the bottom buttons view in call screen."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallButtonsView"}],"url":"\/documentation\/talksdk\/callbuttonsview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView/speakerButton":{"navigatorTitle":[{"kind":"identifier","text":"speakerButton"}],"role":"symbol","title":"speakerButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speakerButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Button for changing the ongoing call’s audio configuration. It operates differently depending on Bluetooth enabled headsets being connnected to the device:"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/speakerButton","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callbuttonsview\/speakerbutton"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView/hangUpButton":{"navigatorTitle":[{"kind":"identifier","text":"hangUpButton"}],"role":"symbol","title":"hangUpButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hangUpButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Button for disconnecting the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/hangUpButton","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callbuttonsview\/hangupbutton"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView/speakerTitleLabel":{"navigatorTitle":[{"kind":"identifier","text":"speakerTitleLabel"}],"role":"symbol","title":"speakerTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"speakerTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/speakerTitleLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callbuttonsview\/speakertitlelabel"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallButtonsView/muteTitleLabel":{"navigatorTitle":[{"kind":"identifier","text":"muteTitleLabel"}],"role":"symbol","title":"muteTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"muteTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/muteTitleLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callbuttonsview\/mutetitlelabel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"CallButtonsView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallButtonsView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CallButtonsView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/hangUpButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/hangUpTitleLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/muteButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/muteTitleLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/speakerButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallButtonsView\/speakerTitleLabel"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallButtonsView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1muteButton\/title","value":"muteButton"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1muteButton\/fragments","value":[{"kind":"identifier","text":"muteButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1hangUpTitleLabel\/title","value":"hangUpTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1hangUpTitleLabel\/fragments","value":[{"kind":"identifier","text":"hangUpTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/title","value":"CallButtonsView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView\/fragments","value":[{"kind":"identifier","text":"CallButtonsView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1speakerButton\/title","value":"speakerButton"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1speakerButton\/fragments","value":[{"kind":"identifier","text":"speakerButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1hangUpButton\/title","value":"hangUpButton"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1hangUpButton\/fragments","value":[{"kind":"identifier","text":"hangUpButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1speakerTitleLabel\/title","value":"speakerTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1speakerTitleLabel\/fragments","value":[{"kind":"identifier","text":"speakerTitleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1muteTitleLabel\/title","value":"muteTitleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallButtonsView~1muteTitleLabel\/fragments","value":[{"kind":"identifier","text":"muteTitleLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}