{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallErrorView"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"CallErrorView"},{"type":"text","text":" is visible when starting a call has failed. The screen will is shown full screen."},{"type":"text","text":" "},{"type":"text","text":"On that screen you can change fonts, text colors, background colors, etc."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You cannot change layout of elements. In case you need your own layout setup, use other SDK API methods and build your own Call View."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callerrorview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callerrorview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represent the error view with "},{"type":"codeVoice","code":"retry"},{"type":"text","text":" and "},{"type":"codeVoice","code":"cancel"},{"type":"text","text":" buttons."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallErrorView"}],"title":"CallErrorView","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@TalkSDK@objc(pl)CallErrorView","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CallErrorView"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/cancelButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/messageLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/retryButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/titleLabel"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView/messageLabel":{"navigatorTitle":[{"kind":"identifier","text":"messageLabel"}],"role":"symbol","title":"messageLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/messageLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callerrorview\/messagelabel"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView":{"role":"symbol","title":"CallErrorView","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallErrorView"}],"abstract":[{"type":"text","text":"Represent the error view with "},{"type":"codeVoice","code":"retry"},{"type":"text","text":" and "},{"type":"codeVoice","code":"cancel"},{"type":"text","text":" buttons."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallErrorView"}],"url":"\/documentation\/talksdk\/callerrorview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView/retryButton":{"navigatorTitle":[{"kind":"identifier","text":"retryButton"}],"role":"symbol","title":"retryButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retryButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Retry button. When user will tap it call will try to reconnect."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/retryButton","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callerrorview\/retrybutton"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView/cancelButton":{"navigatorTitle":[{"kind":"identifier","text":"cancelButton"}],"role":"symbol","title":"cancelButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Cancel button. Tapping will close the Call Screen."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/cancelButton","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callerrorview\/cancelbutton"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallErrorView/titleLabel":{"navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/titleLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/callerrorview\/titlelabel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"CallErrorView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallErrorView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CallErrorView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/cancelButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/messageLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/retryButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallErrorView\/titleLabel"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallErrorView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1messageLabel\/title","value":"messageLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1messageLabel\/fragments","value":[{"kind":"identifier","text":"messageLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/title","value":"CallErrorView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView\/fragments","value":[{"kind":"identifier","text":"CallErrorView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1retryButton\/title","value":"retryButton"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1retryButton\/fragments","value":[{"kind":"identifier","text":"retryButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1cancelButton\/title","value":"cancelButton"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1cancelButton\/fragments","value":[{"kind":"identifier","text":"cancelButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallErrorView~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}