{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/SQ","doc:\/\/com.zendesk.TalkSDK\/SH","doc:\/\/com.zendesk.TalkSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents all possible states of the call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallStatus"}],"title":"CallStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@TalkSDK@E@CallStatus","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CallStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/connected","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/connecting","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/disconnected","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/failed","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/reconnected","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/reconnecting"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/Equatable-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/reconnecting":{"role":"symbol","title":"CallStatus.reconnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnecting"}],"abstract":[{"type":"text","text":"The call starts to reconnect."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/reconnecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatusReconnecting"}],"url":"\/documentation\/talksdk\/callstatus\/reconnecting"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/callstatus\/equatable-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/reconnected":{"role":"symbol","title":"CallStatus.reconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnected"}],"abstract":[{"type":"text","text":"The call has reconnected."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/reconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatusReconnected"}],"url":"\/documentation\/talksdk\/callstatus\/reconnected"},"doc://com.zendesk.TalkSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SY"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/callstatus\/rawrepresentable-implementations"},"doc://com.zendesk.TalkSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SH"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/connecting":{"role":"symbol","title":"CallStatus.connecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connecting"}],"abstract":[{"type":"text","text":"The call is connecting."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/connecting","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatusConnecting"}],"url":"\/documentation\/talksdk\/callstatus\/connecting"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/failed":{"role":"symbol","title":"CallStatus.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"The call has been disconnected."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatusFailed"}],"url":"\/documentation\/talksdk\/callstatus\/failed"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus":{"role":"symbol","title":"CallStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallStatus"}],"abstract":[{"type":"text","text":"Represents all possible states of the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatus"}],"url":"\/documentation\/talksdk\/callstatus"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/disconnected":{"role":"symbol","title":"CallStatus.disconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"abstract":[{"type":"text","text":"The call has disconnected."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/disconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatusDisconnected"}],"url":"\/documentation\/talksdk\/callstatus\/disconnected"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/connected":{"role":"symbol","title":"CallStatus.connected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connected"}],"abstract":[{"type":"text","text":"The call has been connected."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/connected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatusConnected"}],"url":"\/documentation\/talksdk\/callstatus\/connected"},"doc://com.zendesk.TalkSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SQ"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callstatus\/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"CallStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CallStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/connected","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/connecting","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/disconnected","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/failed","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/reconnected","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/reconnecting"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1reconnecting\/title","value":"CallStatusReconnecting"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1reconnecting\/fragments","value":[{"kind":"identifier","text":"CallStatusReconnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1reconnected\/title","value":"CallStatusReconnected"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1reconnected\/fragments","value":[{"kind":"identifier","text":"CallStatusReconnected"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1connecting\/title","value":"CallStatusConnecting"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1connecting\/fragments","value":[{"kind":"identifier","text":"CallStatusConnecting"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1failed\/title","value":"CallStatusFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1failed\/fragments","value":[{"kind":"identifier","text":"CallStatusFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/title","value":"CallStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/fragments","value":[{"kind":"identifier","text":"CallStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1disconnected\/title","value":"CallStatusDisconnected"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1disconnected\/fragments","value":[{"kind":"identifier","text":"CallStatusDisconnected"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1connected\/title","value":"CallStatusConnected"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1connected\/fragments","value":[{"kind":"identifier","text":"CallStatusConnected"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}