{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallData"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/calldata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/calldata"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallData"}],"title":"CallData","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@TalkSDK@objc(pl)CallData","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CallData"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData\/digitalLine","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData\/recordingConsentAnswer"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallData":{"role":"symbol","title":"TalkCallData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallData"}],"abstract":[{"type":"codeVoice","code":"CallData"},{"type":"text","text":" conforming class that represents parameters required to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallData"}],"url":"\/documentation\/talksdk\/talkcalldata"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData/digitalLine":{"navigatorTitle":[{"kind":"identifier","text":"digitalLine"}],"role":"symbol","title":"digitalLine","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"}],"abstract":[{"type":"text","text":"Name of digital line configured by the admin in Talk Settings."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData\/digitalLine","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/calldata\/digitalline"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData":{"role":"symbol","title":"CallData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallData"}],"abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallData"}],"url":"\/documentation\/talksdk\/calldata"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData/recordingConsentAnswer":{"navigatorTitle":[{"kind":"identifier","text":"recordingConsentAnswer"}],"role":"symbol","title":"recordingConsentAnswer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentAnswer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecordingConsentAnswer","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsentAnswer"}],"abstract":[{"type":"text","text":"Answer received from end user about recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData\/recordingConsentAnswer","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/calldata\/recordingconsentanswer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"CallData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallData"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CallData"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData\/digitalLine","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData\/recordingConsentAnswer"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallData"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallData"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/title","value":"ZDKTalkCallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallData\/fragments","value":[{"kind":"identifier","text":"ZDKTalkCallData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData~1digitalLine\/title","value":"digitalLine"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData~1digitalLine\/fragments","value":[{"kind":"identifier","text":"digitalLine"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/title","value":"CallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/fragments","value":[{"kind":"identifier","text":"CallData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData~1recordingConsentAnswer\/title","value":"recordingConsentAnswer"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData~1recordingConsentAnswer\/fragments","value":[{"kind":"identifier","text":"recordingConsentAnswer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}