{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/linestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/linestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Comprehensive information about status of digital line."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineStatus"}],"title":"LineStatus","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@TalkSDK@objc(pl)LineStatus","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"LineStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus\/agentAvailable","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus\/recordingConsent"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/LineStatus/agentAvailable":{"navigatorTitle":[{"kind":"identifier","text":"agentAvailable"}],"role":"symbol","title":"agentAvailable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"agentAvailable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Boolean flag which should be used to determine whether the “call us button” should be visible to end user."},{"type":"text","text":" "},{"type":"text","text":"Value "},{"type":"codeVoice","code":"true"},{"type":"text","text":" means that line is available to use. Value "},{"type":"codeVoice","code":"false"},{"type":"text","text":" means that the line is either disabled or no agent is available."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus\/agentAvailable","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/linestatus\/agentavailable"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/LineStatus":{"role":"symbol","title":"LineStatus","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineStatus"}],"abstract":[{"type":"text","text":"Comprehensive information about status of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineStatus"}],"url":"\/documentation\/talksdk\/linestatus"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/LineStatus/recordingConsent":{"navigatorTitle":[{"kind":"identifier","text":"recordingConsent"}],"role":"symbol","title":"recordingConsent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecordingConsent","preciseIdentifier":"c:@M@TalkSDK@E@RecordingConsent"}],"abstract":[{"type":"text","text":"Digital line’s current recording and recording consent configuration."},{"type":"text","text":" "},{"type":"text","text":"Using value of this property the end user may be allowed for opting-in or opting-out from call recording."},{"type":"text","text":" "},{"type":"text","text":"If the "},{"type":"strong","inlineContent":[{"type":"text","text":"recordingConsent"}]},{"type":"text","text":" is "},{"type":"codeVoice","code":"unknown"},{"type":"text","text":" it means that end user does not need to opt-in or opt-out from call recording."},{"type":"text","text":" "},{"type":"text","text":"At the same time the "},{"type":"codeVoice","code":"unknown"},{"type":"text","text":" value does not provide any information whether the call will be recorded or not."},{"type":"text","text":" "},{"type":"text","text":"With the "},{"type":"codeVoice","code":"unknown"},{"type":"text","text":" value, all configuration is handled server side."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus\/recordingConsent","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/linestatus\/recordingconsent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"LineStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LineStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LineStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus\/agentAvailable","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus\/recordingConsent"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineStatus"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus~1agentAvailable\/title","value":"agentAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus~1agentAvailable\/fragments","value":[{"kind":"identifier","text":"agentAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/title","value":"LineStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/fragments","value":[{"kind":"identifier","text":"LineStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus~1recordingConsent\/title","value":"recordingConsent"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus~1recordingConsent\/fragments","value":[{"kind":"identifier","text":"recordingConsent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}