{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentAnswer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/recordingconsentanswer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/recordingconsentanswer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/SQ","doc:\/\/com.zendesk.TalkSDK\/SH","doc:\/\/com.zendesk.TalkSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents the answer received from end user about recording the call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentAnswer"}],"title":"RecordingConsentAnswer","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@TalkSDK@E@RecordingConsentAnswer","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswer"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/optedIn","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/optedOut","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/Equatable-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer/unknown":{"role":"symbol","title":"RecordingConsentAnswer.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"User did not provide answer about recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswerUnknown"}],"url":"\/documentation\/talksdk\/recordingconsentanswer\/unknown"},"doc://com.zendesk.TalkSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SQ"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer/optedIn":{"role":"symbol","title":"RecordingConsentAnswer.optedIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optedIn"}],"abstract":[{"type":"text","text":"Even if the default setting is not to record the call, end user opted in for recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/optedIn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswerOptedIn"}],"url":"\/documentation\/talksdk\/recordingconsentanswer\/optedin"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/recordingconsentanswer\/rawrepresentable-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer/optedOut":{"role":"symbol","title":"RecordingConsentAnswer.optedOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optedOut"}],"abstract":[{"type":"text","text":"Even if the default setting was to record the call, the end user opted-out from recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/optedOut","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswerOptedOut"}],"url":"\/documentation\/talksdk\/recordingconsentanswer\/optedout"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/recordingconsentanswer\/equatable-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/recordingconsentanswer\/init(rawvalue:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer":{"role":"symbol","title":"RecordingConsentAnswer","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentAnswer"}],"abstract":[{"type":"text","text":"Represents the answer received from end user about recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswer"}],"url":"\/documentation\/talksdk\/recordingconsentanswer"},"doc://com.zendesk.TalkSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SY"},"doc://com.zendesk.TalkSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"RecordingConsentAnswer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RecordingConsentAnswer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/optedIn","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/optedOut","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentAnswer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer~1unknown\/title","value":"RecordingConsentAnswerUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer~1unknown\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswerUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer~1optedIn\/title","value":"RecordingConsentAnswerOptedIn"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer~1optedIn\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswerOptedIn"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer~1optedOut\/title","value":"RecordingConsentAnswerOptedOut"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer~1optedOut\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswerOptedOut"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/title","value":"RecordingConsentAnswer"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}