{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentScreen"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The screen contains all UI elements of the view."},{"type":"text","text":" "},{"type":"text","text":"It is shown only when the "},{"type":"codeVoice","code":"Recording Consent"},{"type":"text","text":" received from "},{"type":"codeVoice","code":"lineStatus"},{"type":"text","text":" has a value of "},{"type":"codeVoice","code":"optIn"},{"type":"text","text":" or "},{"type":"codeVoice","code":"optOut"},{"type":"text","text":". Otherwise no user’s answer is required and the screen is not presented."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This view has customizable font, text colors, background color, etc."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You cannot change layout of elements. In case you need your own layout setup, use other SDK API methods and build your own "},{"type":"codeVoice","code":"Recording Consent"},{"type":"text","text":" view."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/recordingconsentscreen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/recordingconsentscreen"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Screen handling recording consent."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentScreen"}],"title":"RecordingConsentScreen","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"RecordingConsentScreen"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/activityIndicatorView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/backgroundColor","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/cancelButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentDescriptionLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentSwitch","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentSwitchView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/messageLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/startCallButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/titleLabel"]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/titleLabel":{"navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Label which shows main title. Example: “Recording this call”."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/titleLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/recordingconsentscreen\/titlelabel"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen":{"role":"symbol","title":"RecordingConsentScreen","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentScreen"}],"abstract":[{"type":"text","text":"Screen handling recording consent."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentScreen"}],"url":"\/documentation\/talksdk\/recordingconsentscreen"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/activityIndicatorView":{"navigatorTitle":[{"kind":"identifier","text":"activityIndicatorView"}],"role":"symbol","title":"activityIndicatorView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityIndicatorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Indicator which is shown when fetching digital line’s recording consent configuration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/activityIndicatorView","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/recordingconsentscreen\/activityindicatorview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/consentDescriptionLabel":{"navigatorTitle":[{"kind":"identifier","text":"consentDescriptionLabel"}],"role":"symbol","title":"consentDescriptionLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consentDescriptionLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Label which message regarding uiswitch. Example: “I agree to this call being recorder”."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentDescriptionLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/recordingconsentscreen\/consentdescriptionlabel"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/backgroundColor":{"navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Background color of the screen container."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/backgroundColor","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/recordingconsentscreen\/backgroundcolor"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/cancelButton":{"navigatorTitle":[{"kind":"identifier","text":"cancelButton"}],"role":"symbol","title":"cancelButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Cancel Button which cancels all the flow and calls "},{"type":"codeVoice","code":"cancelHandler"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/cancelButton","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/recordingconsentscreen\/cancelbutton"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/startCallButton":{"navigatorTitle":[{"kind":"identifier","text":"startCallButton"}],"role":"symbol","title":"startCallButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCallButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Button which calls "},{"type":"codeVoice","code":"startCallHandler"},{"type":"text","text":" handler."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/startCallButton","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/recordingconsentscreen\/startcallbutton"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/consentSwitch":{"navigatorTitle":[{"kind":"identifier","text":"consentSwitch"}],"role":"symbol","title":"consentSwitch","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consentSwitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISwitch","preciseIdentifier":"c:objc(cs)UISwitch"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Switch which reflects user’s "},{"type":"codeVoice","code":"RecordingConsentAnswer"},{"type":"text","text":". The "},{"type":"codeVoice","code":"on"},{"type":"text","text":" state equals to "},{"type":"codeVoice","code":".optOut"},{"type":"text","text":", and "},{"type":"codeVoice","code":"off"},{"type":"text","text":" state to "},{"type":"codeVoice","code":".optIn"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentSwitch","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/recordingconsentscreen\/consentswitch"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/consentSwitchView":{"navigatorTitle":[{"kind":"identifier","text":"consentSwitchView"}],"role":"symbol","title":"consentSwitchView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consentSwitchView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The view which contains consent "},{"type":"codeVoice","code":"UISwitch"},{"type":"text","text":" and description label."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentSwitchView","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/recordingconsentscreen\/consentswitchview"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/messageLabel":{"navigatorTitle":[{"kind":"identifier","text":"messageLabel"}],"role":"symbol","title":"messageLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Label which shows description message under the title label."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/messageLabel","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/recordingconsentscreen\/messagelabel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"RecordingConsentScreen"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RecordingConsentScreen"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RecordingConsentScreen"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/activityIndicatorView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/backgroundColor","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/cancelButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentDescriptionLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentSwitch","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentSwitchView","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/messageLabel","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/startCallButton","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/titleLabel"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentScreen"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/title","value":"RecordingConsentScreen"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/fragments","value":[{"kind":"identifier","text":"RecordingConsentScreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1activityIndicatorView\/title","value":"activityIndicatorView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1activityIndicatorView\/fragments","value":[{"kind":"identifier","text":"activityIndicatorView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1consentDescriptionLabel\/title","value":"consentDescriptionLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1consentDescriptionLabel\/fragments","value":[{"kind":"identifier","text":"consentDescriptionLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1backgroundColor\/title","value":"backgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1backgroundColor\/fragments","value":[{"kind":"identifier","text":"backgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1cancelButton\/title","value":"cancelButton"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1cancelButton\/fragments","value":[{"kind":"identifier","text":"cancelButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1startCallButton\/title","value":"startCallButton"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1startCallButton\/fragments","value":[{"kind":"identifier","text":"startCallButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1consentSwitch\/title","value":"consentSwitch"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1consentSwitch\/fragments","value":[{"kind":"identifier","text":"consentSwitch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1consentSwitchView\/title","value":"consentSwitchView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1consentSwitchView\/fragments","value":[{"kind":"identifier","text":"consentSwitchView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1messageLabel\/title","value":"messageLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1messageLabel\/fragments","value":[{"kind":"identifier","text":"messageLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}