{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKTalk) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talk"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.TalkSDK\/s7CVarArgP","doc:\/\/com.zendesk.TalkSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.TalkSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.TalkSDK\/SQ","doc:\/\/com.zendesk.TalkSDK\/SH","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkFlowProvider","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkScreenProvider"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An entry point into Talk SDK for iOS."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"title":"Talk","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TalkSDK@objc(cs)ZDKTalk","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"Talk"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/init(zendesk:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/call(callData:statusChangeHandler:)-74x7","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/lineStatus(digitalLine:completion:)-6dnz4","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallViewController(with:callDidFinishHandler:)-1jwxw"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkCoreProvider-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkFlowProvider-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkScreenProvider-Implementations"],"generated":true}],"references":{"doc://com.zendesk.TalkSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(cs)NSObject"},"doc://com.zendesk.TalkSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.TalkSDK\/objc(pl)NSObject"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/TalkCoreProvider-Implementations":{"role":"collectionGroup","title":"TalkCoreProvider Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkCoreProvider-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/talk\/talkcoreprovider-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/lineStatus(digitalLine:completion:)-6dnz4":{"role":"symbol","title":"lineStatus(digitalLine:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"LineStatus","preciseIdentifier":"c:@M@TalkSDK@objc(pl)LineStatus"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Provides asynchronous information about status of line associated with "},{"type":"codeVoice","code":"digitalLine"},{"type":"text","text":" in Talk Settings."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/lineStatus(digitalLine:completion:)-6dnz4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lineStatusWithDigitalLine:completion:"}],"url":"\/documentation\/talksdk\/talk\/linestatus(digitalline:completion:)-6dnz4"},"doc://com.zendesk.TalkSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.TalkSDK\/s7CVarArgP"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/makeCallViewController(with:callDidFinishHandler:)-1jwxw":{"role":"symbol","title":"makeCallViewController(with:callDidFinishHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCallViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callDidFinishHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"CallScreen","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallScreen"}],"abstract":[{"type":"text","text":"Returns Call View Controller"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallViewController(with:callDidFinishHandler:)-1jwxw","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeCallViewControllerWith:callDidFinishHandler:"}],"url":"\/documentation\/talksdk\/talk\/makecallviewcontroller(with:calldidfinishhandler:)-1jwxw"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCoreProvider":{"role":"symbol","title":"TalkCoreProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCoreProvider"}],"abstract":[{"type":"text","text":"Main "},{"type":"codeVoice","code":"Talk"},{"type":"text","text":" provider, responsible for the core calling API functionality."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCoreProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCoreProvider"}],"url":"\/documentation\/talksdk\/talkcoreprovider"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/init(zendesk:)":{"role":"symbol","title":"init(zendesk:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"zendesk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKZendesk"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize Talk with provided "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" configuration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/init(zendesk:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithZendesk:"}],"url":"\/documentation\/talksdk\/talk\/init(zendesk:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/call(callData:statusChangeHandler:)-74x7":{"role":"symbol","title":"call(callData:statusChangeHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"call"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusChangeHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CallStatus","preciseIdentifier":"c:@M@TalkSDK@E@CallStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TalkCall","preciseIdentifier":"c:@M@TalkSDK@objc(pl)TalkCall"}],"abstract":[{"type":"text","text":"Initializes call with provided call data."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/call(callData:statusChangeHandler:)-74x7","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callWithCallData:statusChangeHandler:"}],"url":"\/documentation\/talksdk\/talk\/call(calldata:statuschangehandler:)-74x7"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/TalkScreenProvider-Implementations":{"role":"collectionGroup","title":"TalkScreenProvider Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkScreenProvider-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/talk\/talkscreenprovider-implementations"},"doc://com.zendesk.TalkSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SH"},"doc://com.zendesk.TalkSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.TalkSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.TalkSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.TalkSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkScreenProvider":{"role":"symbol","title":"TalkScreenProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkScreenProvider"}],"abstract":[{"type":"text","text":"Screen provider, responsible for creating preconfigured and ready to use call configuration and call view controllers."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkScreenProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkScreenProvider"}],"url":"\/documentation\/talksdk\/talkscreenprovider"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkFlowProvider":{"role":"symbol","title":"TalkFlowProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkFlowProvider"}],"abstract":[{"type":"text","text":"Call flow provider, responsible for effortlessly starting the call using SDK provided screens and APIs."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkFlowProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkFlowProvider"}],"url":"\/documentation\/talksdk\/talkflowprovider"},"doc://com.zendesk.TalkSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SQ"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/TalkFlowProvider-Implementations":{"role":"collectionGroup","title":"TalkFlowProvider Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkFlowProvider-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/talk\/talkflowprovider-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"role":"symbol","title":"Talk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"abstract":[{"type":"text","text":"An entry point into Talk SDK for iOS."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"url":"\/documentation\/talksdk\/talk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKTalk"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKTalk"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/call(callData:statusChangeHandler:)-74x7","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/init(zendesk:)","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/lineStatus(digitalLine:completion:)-6dnz4","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallViewController(with:callDidFinishHandler:)-1jwxw"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkFlowProvider-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkScreenProvider-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKTalk"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1lineStatus(digitalLine:completion:)-6dnz4\/title","value":"lineStatusWithDigitalLine:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1lineStatus(digitalLine:completion:)-6dnz4\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lineStatusWithDigitalLine:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1makeCallViewController(with:callDidFinishHandler:)-1jwxw\/title","value":"makeCallViewControllerWith:callDidFinishHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1makeCallViewController(with:callDidFinishHandler:)-1jwxw\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeCallViewControllerWith:callDidFinishHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1init(zendesk:)\/title","value":"initWithZendesk:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1init(zendesk:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithZendesk:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1call(callData:statusChangeHandler:)-74x7\/title","value":"callWithCallData:statusChangeHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1call(callData:statusChangeHandler:)-74x7\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callWithCallData:statusChangeHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","value":"ZDKTalk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}