{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talkcallerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talkcallerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.TalkSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.TalkSDK\/SQ","doc:\/\/com.zendesk.TalkSDK\/s5ErrorP","doc:\/\/com.zendesk.TalkSDK\/SH","doc:\/\/com.zendesk.TalkSDK\/SY","doc:\/\/com.zendesk.TalkSDK\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents errors occuring for a "},{"type":"codeVoice","code":"failed"},{"type":"text","text":" or "},{"type":"codeVoice","code":"disconnected"},{"type":"text","text":" call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallError"}],"title":"TalkCallError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@TalkSDK@E@TalkCallError","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"TalkCallError"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/digitalLineNotFound","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/networkError","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/unauthorized","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/CustomStringConvertible-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/Equatable-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/Error-Implementations","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/unauthorized":{"role":"symbol","title":"TalkCallError.unauthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unauthorized"}],"abstract":[{"type":"text","text":"The app is not authorized to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/unauthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorUnauthorized"}],"url":"\/documentation\/talksdk\/talkcallerror\/unauthorized"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/talkcallerror\/customstringconvertible-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/digitalLineNotFound":{"role":"symbol","title":"TalkCallError.digitalLineNotFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalLineNotFound"}],"abstract":[{"type":"text","text":"No digital line was found with a provided name."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/digitalLineNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorDigitalLineNotFound"}],"url":"\/documentation\/talksdk\/talkcallerror\/digitallinenotfound"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError":{"role":"symbol","title":"TalkCallError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallError"}],"abstract":[{"type":"text","text":"Represents errors occuring for a "},{"type":"codeVoice","code":"failed"},{"type":"text","text":" or "},{"type":"codeVoice","code":"disconnected"},{"type":"text","text":" call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallError"}],"url":"\/documentation\/talksdk\/talkcallerror"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/talkcallerror\/error-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/networkError":{"role":"symbol","title":"TalkCallError.networkError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"abstract":[{"type":"text","text":"Establishing the call failed because of network issues."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/networkError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorNetworkError"}],"url":"\/documentation\/talksdk\/talkcallerror\/networkerror"},"doc://com.zendesk.TalkSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SH"},"doc://com.zendesk.TalkSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.TalkSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/unknown":{"role":"symbol","title":"TalkCallError.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"An unknown error occurred while establishing the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorUnknown"}],"url":"\/documentation\/talksdk\/talkcallerror\/unknown"},"doc://com.zendesk.TalkSDK/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.zendesk.TalkSDK\/s8SendableP"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/talkcallerror\/rawrepresentable-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/talkcallerror\/init(rawvalue:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/talkcallerror\/equatable-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SY"},"doc://com.zendesk.TalkSDK/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.zendesk.TalkSDK\/s5ErrorP"},"doc://com.zendesk.TalkSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.TalkSDK\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"TalkCallError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TalkCallError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TalkCallError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/digitalLineNotFound","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/networkError","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/unauthorized","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1unauthorized\/title","value":"TalkCallErrorUnauthorized"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1unauthorized\/fragments","value":[{"kind":"identifier","text":"TalkCallErrorUnauthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1digitalLineNotFound\/title","value":"TalkCallErrorDigitalLineNotFound"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1digitalLineNotFound\/fragments","value":[{"kind":"identifier","text":"TalkCallErrorDigitalLineNotFound"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/title","value":"TalkCallError"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/fragments","value":[{"kind":"identifier","text":"TalkCallError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1networkError\/title","value":"TalkCallErrorNetworkError"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1networkError\/fragments","value":[{"kind":"identifier","text":"TalkCallErrorNetworkError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1unknown\/title","value":"TalkCallErrorUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1unknown\/fragments","value":[{"kind":"identifier","text":"TalkCallErrorUnknown"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}