{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"optIn","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/recordingconsent\/optin"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/recordingconsent\/optin"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/optIn"},"sections":[],"abstract":[{"type":"text","text":"Call recording is disabled by default, but the end user has the option to opt-in"}],"metadata":{"externalID":"c:@M@TalkSDK@E@RecordingConsent@RecordingConsentOptIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optIn"}],"title":"RecordingConsent.optIn","role":"symbol","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"RecordingConsentOptIn"}],"symbolKind":"case","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent/optIn":{"title":"RecordingConsent.optIn","type":"topic","abstract":[{"text":"Call recording is disabled by default, but the end user has the option to opt-in","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optIn"}],"navigatorTitle":[{"kind":"identifier","text":"RecordingConsentOptIn"}],"role":"symbol","kind":"symbol","url":"\/documentation\/talksdk\/recordingconsent\/optin","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/optIn"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent":{"navigatorTitle":[{"text":"RecordingConsent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/talksdk\/recordingconsent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsent"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent","type":"topic","abstract":[{"type":"text","text":"Represents digital line’s recording consent configuration."}],"title":"RecordingConsent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"RecordingConsentOptIn","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"RecordingConsentOptIn","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"RecordingConsentOptIn"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1optIn\/title","value":"RecordingConsentOptIn"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1optIn\/fragments","value":[{"kind":"identifier","text":"RecordingConsentOptIn"}]},{"op":"replace","value":"RecordingConsent","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/title"},{"value":[{"kind":"identifier","text":"RecordingConsent"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/fragments"}]}]}