{"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent"]]},"metadata":{"roleHeading":"Case","externalID":"c:@M@TalkSDK@E@RecordingConsent@RecordingConsentOptOut","symbolKind":"case","role":"symbol","title":"RecordingConsent.optOut","navigatorTitle":[{"text":"RecordingConsentOptOut","kind":"identifier"}],"modules":[{"name":"TalkSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optOut","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/recordingconsent\/optout"]},{"paths":["\/documentation\/talksdk\/recordingconsent\/optout"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/optOut"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"abstract":[{"text":"Call recording is enabled by default, but the end user has the option to opt-out","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optOut","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent/optOut":{"kind":"symbol","title":"RecordingConsent.optOut","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/optOut","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"optOut","kind":"identifier"}],"navigatorTitle":[{"text":"RecordingConsentOptOut","kind":"identifier"}],"role":"symbol","url":"\/documentation\/talksdk\/recordingconsent\/optout","type":"topic","abstract":[{"type":"text","text":"Call recording is enabled by default, but the end user has the option to opt-out"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent":{"navigatorTitle":[{"text":"RecordingConsent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/talksdk\/recordingconsent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsent"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent","type":"topic","abstract":[{"type":"text","text":"Represents digital line’s recording consent configuration."}],"title":"RecordingConsent"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"RecordingConsentOptOut","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"RecordingConsentOptOut","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"RecordingConsentOptOut","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1optOut\/title","value":"RecordingConsentOptOut","op":"replace"},{"value":[{"kind":"identifier","text":"RecordingConsentOptOut"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1optOut\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/title","op":"replace","value":"RecordingConsent"},{"op":"replace","value":[{"text":"RecordingConsent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/fragments"}]}]}