{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/talksdk\/recordingconsent\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/recordingconsent\/unknown"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/unknown"},"metadata":{"roleHeading":"Case","title":"RecordingConsent.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"externalID":"c:@M@TalkSDK@E@RecordingConsent@RecordingConsentUnknown","role":"symbol","symbolKind":"case","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"RecordingConsentUnknown"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent"]]},"sections":[],"abstract":[{"text":"Call recording is not defined in Talk settings","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent":{"navigatorTitle":[{"text":"RecordingConsent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/talksdk\/recordingconsent","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsent"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent","type":"topic","abstract":[{"type":"text","text":"Represents digital line’s recording consent configuration."}],"title":"RecordingConsent"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsent/unknown":{"abstract":[{"type":"text","text":"Call recording is not defined in Talk settings"}],"url":"\/documentation\/talksdk\/recordingconsent\/unknown","kind":"symbol","title":"RecordingConsent.unknown","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsent\/unknown","role":"symbol","navigatorTitle":[{"text":"RecordingConsentUnknown","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"RecordingConsentUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RecordingConsentUnknown"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"RecordingConsentUnknown","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/title","op":"replace","value":"RecordingConsent"},{"value":[{"kind":"identifier","text":"RecordingConsent"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent\/fragments"},{"value":"RecordingConsentUnknown","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1unknown\/title"},{"op":"replace","value":[{"text":"RecordingConsentUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsent~1unknown\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}