{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/recordingconsentanswer\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/recordingconsentanswer\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/unknown","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"User did not provide answer about recording the call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"title":"RecordingConsentAnswer.unknown","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@TalkSDK@E@RecordingConsentAnswer@RecordingConsentAnswerUnknown","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswerUnknown"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer/unknown":{"role":"symbol","title":"RecordingConsentAnswer.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"User did not provide answer about recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswerUnknown"}],"url":"\/documentation\/talksdk\/recordingconsentanswer\/unknown"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer":{"role":"symbol","title":"RecordingConsentAnswer","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecordingConsentAnswer"}],"abstract":[{"type":"text","text":"Represents the answer received from end user about recording the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswer"}],"url":"\/documentation\/talksdk\/recordingconsentanswer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"RecordingConsentAnswerUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswerUnknown"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"RecordingConsentAnswerUnknown"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer~1unknown\/title","value":"RecordingConsentAnswerUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer~1unknown\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswerUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/title","value":"RecordingConsentAnswer"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}