{"metadata":{"roleHeading":"Instance Property","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"title":"titleLabel","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"externalID":"c:@M@TalkSDK@objc(pl)CallTimerView(py)titleLabel","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView\/titleLabel"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/talksdk\/calltimerview\/titlelabel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/calltimerview\/titlelabel"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"titleLabel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"! { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallTimerView/titleLabel":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"titleLabel","kind":"identifier"},{"kind":"text","text":": "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView\/titleLabel","role":"symbol","kind":"symbol","title":"titleLabel","url":"\/documentation\/talksdk\/calltimerview\/titlelabel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"abstract":[]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallTimerView":{"navigatorTitle":[{"text":"CallTimerView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/talksdk\/calltimerview","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallTimerView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallTimerView","type":"topic","abstract":[{"type":"text","text":"Represent the timer view with a label showing call’s duration."}],"title":"CallTimerView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"titleLabel"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"titleLabel","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"},{"text":" * ","kind":"text"},{"text":"titleLabel","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"titleLabel","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView~1titleLabel\/title"},{"op":"replace","value":[{"text":"titleLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView~1titleLabel\/fragments"},{"value":"CallTimerView","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView\/title"},{"value":[{"text":"CallTimerView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallTimerView\/fragments"}]}]}