{"abstract":[{"text":"Indicator which is shown when fetching digital line’s recording consent configuration.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityIndicatorView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","kind":"typeIdentifier","text":"UIActivityIndicatorView"},{"kind":"text","text":"! { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/activityIndicatorView","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/talksdk\/recordingconsentscreen\/activityindicatorview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/recordingconsentscreen\/activityindicatorview"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"activityIndicatorView","symbolKind":"property","modules":[{"name":"TalkSDK"}],"externalID":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen(py)activityIndicatorView","navigatorTitle":[{"kind":"identifier","text":"activityIndicatorView"}],"required":true,"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityIndicatorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"!"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/activityIndicatorView":{"required":true,"url":"\/documentation\/talksdk\/recordingconsentscreen\/activityindicatorview","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activityIndicatorView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","kind":"typeIdentifier","text":"UIActivityIndicatorView"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/activityIndicatorView","title":"activityIndicatorView","kind":"symbol","abstract":[{"type":"text","text":"Indicator which is shown when fetching digital line’s recording consent configuration."}],"type":"topic","navigatorTitle":[{"text":"activityIndicatorView","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen":{"title":"RecordingConsentScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","url":"\/documentation\/talksdk\/recordingconsentscreen","navigatorTitle":[{"text":"RecordingConsentScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Screen handling recording consent.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RecordingConsentScreen","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"activityIndicatorView"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"activityIndicatorView","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","text":"UIActivityIndicatorView"},{"kind":"text","text":" * "},{"text":"activityIndicatorView","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1activityIndicatorView\/title","value":"activityIndicatorView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1activityIndicatorView\/fragments","value":[{"text":"activityIndicatorView","kind":"identifier"}]},{"op":"replace","value":"RecordingConsentScreen","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/fragments","op":"replace","value":[{"text":"RecordingConsentScreen","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}