{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Switch which reflects user’s "},{"type":"codeVoice","code":"RecordingConsentAnswer"},{"type":"text","text":". The "},{"code":"on","type":"codeVoice"},{"text":" state equals to ","type":"text"},{"type":"codeVoice","code":".optOut"},{"text":", and ","type":"text"},{"code":"off","type":"codeVoice"},{"type":"text","text":" state to "},{"code":".optIn","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentSwitch","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/talksdk\/recordingconsentscreen\/consentswitch"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/recordingconsentscreen\/consentswitch"]}],"metadata":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"consentSwitch"}],"externalID":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen(py)consentSwitch","modules":[{"name":"TalkSDK"}],"roleHeading":"Instance Property","symbolKind":"property","title":"consentSwitch","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"consentSwitch","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UISwitch","preciseIdentifier":"c:objc(cs)UISwitch"},{"text":"!","kind":"text"}],"role":"symbol"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consentSwitch"},{"kind":"text","text":": "},{"text":"UISwitch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISwitch"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/consentSwitch":{"required":true,"url":"\/documentation\/talksdk\/recordingconsentscreen\/consentswitch","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"consentSwitch"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISwitch","kind":"typeIdentifier","text":"UISwitch"},{"kind":"text","text":"!"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentSwitch","title":"consentSwitch","kind":"symbol","abstract":[{"type":"text","text":"Switch which reflects user’s "},{"code":"RecordingConsentAnswer","type":"codeVoice"},{"type":"text","text":". The "},{"type":"codeVoice","code":"on"},{"type":"text","text":" state equals to "},{"code":".optOut","type":"codeVoice"},{"text":", and ","type":"text"},{"type":"codeVoice","code":"off"},{"type":"text","text":" state to "},{"type":"codeVoice","code":".optIn"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"consentSwitch"}],"role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen":{"title":"RecordingConsentScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","url":"\/documentation\/talksdk\/recordingconsentscreen","navigatorTitle":[{"text":"RecordingConsentScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Screen handling recording consent.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RecordingConsentScreen","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"consentSwitch"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"consentSwitch"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"UISwitch","preciseIdentifier":"c:objc(cs)UISwitch","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"consentSwitch","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1consentSwitch\/title","value":"consentSwitch","op":"replace"},{"value":[{"kind":"identifier","text":"consentSwitch"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1consentSwitch\/fragments","op":"replace"},{"value":"RecordingConsentScreen","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/title","op":"replace"},{"value":[{"kind":"identifier","text":"RecordingConsentScreen"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}