{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"consentDescriptionLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"},{"kind":"text","text":"! { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentDescriptionLabel","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/recordingconsentscreen\/consentdescriptionlabel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/recordingconsentscreen\/consentdescriptionlabel"]}],"metadata":{"required":true,"modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"consentDescriptionLabel"}],"roleHeading":"Instance Property","externalID":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen(py)consentDescriptionLabel","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"consentDescriptionLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"text":"!","kind":"text"}],"title":"consentDescriptionLabel"},"kind":"symbol","abstract":[{"type":"text","text":"Label which message regarding uiswitch. Example: “I agree to this call being recorder”."}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen":{"title":"RecordingConsentScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","url":"\/documentation\/talksdk\/recordingconsentscreen","navigatorTitle":[{"text":"RecordingConsentScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Screen handling recording consent.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RecordingConsentScreen","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen/consentDescriptionLabel":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen\/consentDescriptionLabel","navigatorTitle":[{"kind":"identifier","text":"consentDescriptionLabel"}],"kind":"symbol","url":"\/documentation\/talksdk\/recordingconsentscreen\/consentdescriptionlabel","title":"consentDescriptionLabel","abstract":[{"type":"text","text":"Label which message regarding uiswitch. Example: “I agree to this call being recorder”."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"consentDescriptionLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"},{"text":"!","kind":"text"}],"required":true,"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"consentDescriptionLabel"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"consentDescriptionLabel","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"consentDescriptionLabel"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/title","value":"RecordingConsentScreen","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/fragments","value":[{"kind":"identifier","text":"RecordingConsentScreen"}],"op":"replace"},{"value":"consentDescriptionLabel","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1consentDescriptionLabel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen~1consentDescriptionLabel\/fragments","value":[{"text":"consentDescriptionLabel","kind":"identifier"}]}]}]}