{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"call"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData","text":"CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusChangeHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","preciseIdentifier":"c:@M@TalkSDK@E@CallStatus","text":"CallStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","preciseIdentifier":"c:@M@TalkSDK@objc(pl)TalkCall","text":"TalkCall"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"TalkCall"},{"type":"text","text":" object where user can change "},{"type":"codeVoice","code":"DeviceOutput"},{"type":"text","text":", "},{"type":"codeVoice","code":"mute"},{"type":"text","text":" or "},{"type":"codeVoice","code":"disconnect"},{"type":"text","text":"."}]}]},{"kind":"parameters","parameters":[{"name":"callData","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Details for the call which contain "},{"type":"codeVoice","code":"digitalLine"},{"type":"text","text":" and "},{"type":"codeVoice","code":"recordingConsentAnswer"}]}]},{"name":"statusChangeHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"will be called on every call status change"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When call will be initialized or failed, handler will be called with proper result."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talk\/call(calldata:statuschangehandler:)-74x7"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talk\/call(calldata:statuschangehandler:)-74x7"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/call(callData:statusChangeHandler:)-74x7","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes call with provided call data."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"callWithCallData:statusChangeHandler:"}],"role":"symbol","title":"call(callData:statusChangeHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"call"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusChangeHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CallStatus","preciseIdentifier":"c:@M@TalkSDK@E@CallStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TalkCall","preciseIdentifier":"c:@M@TalkSDK@objc(pl)TalkCall"}],"symbolKind":"method","externalID":"c:@CM@TalkSDK@objc(cs)ZDKTalk(im)callWithCallData:statusChangeHandler:","modules":[{"name":"TalkSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/call(callData:statusChangeHandler:)-74x7":{"role":"symbol","title":"call(callData:statusChangeHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"call"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusChangeHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CallStatus","preciseIdentifier":"c:@M@TalkSDK@E@CallStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TalkCall","preciseIdentifier":"c:@M@TalkSDK@objc(pl)TalkCall"}],"abstract":[{"type":"text","text":"Initializes call with provided call data."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/call(callData:statusChangeHandler:)-74x7","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callWithCallData:statusChangeHandler:"}],"url":"\/documentation\/talksdk\/talk\/call(calldata:statuschangehandler:)-74x7"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"role":"symbol","title":"Talk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"abstract":[{"type":"text","text":"An entry point into Talk SDK for iOS."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"url":"\/documentation\/talksdk\/talk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus":{"role":"symbol","title":"CallStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallStatus"}],"abstract":[{"type":"text","text":"Represents all possible states of the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatus"}],"url":"\/documentation\/talksdk\/callstatus"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall":{"role":"symbol","title":"TalkCall","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCall"}],"abstract":[{"type":"text","text":"Represents a call created by Talk SDK."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCall"}],"url":"\/documentation\/talksdk\/talkcall"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData":{"role":"symbol","title":"CallData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallData"}],"abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallData"}],"url":"\/documentation\/talksdk\/calldata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"callWithCallData:statusChangeHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callWithCallData:statusChangeHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<TalkCall>","preciseIdentifier":"c:Qo@M@TalkSDK@objc(pl)TalkCall"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"callWithCallData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<CallData>","preciseIdentifier":"c:Qo@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"callData"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusChangeHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum CallStatus, NSError *)","preciseIdentifier":"c:BFv(#$@M@TalkSDK@E@CallStatus#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"statusChangeHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1call(callData:statusChangeHandler:)-74x7\/title","value":"callWithCallData:statusChangeHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1call(callData:statusChangeHandler:)-74x7\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callWithCallData:statusChangeHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","value":"ZDKTalk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/title","value":"CallStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/fragments","value":[{"kind":"identifier","text":"CallStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/title","value":"TalkCall"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/fragments","value":[{"kind":"identifier","text":"TalkCall"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/title","value":"CallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/fragments","value":[{"kind":"identifier","text":"CallData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}