{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"zendesk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKZendesk"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talk\/init(zendesk:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talk\/init(zendesk:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/init(zendesk:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize Talk with provided "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"zendesk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKZendesk"},{"kind":"text","text":")"}],"title":"init(zendesk:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@TalkSDK@objc(cs)ZDKTalk(im)initWithZendesk:","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initWithZendesk:"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/init(zendesk:)":{"role":"symbol","title":"init(zendesk:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"zendesk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKZendesk"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize Talk with provided "},{"type":"codeVoice","code":"Zendesk"},{"type":"text","text":" configuration."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/init(zendesk:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithZendesk:"}],"url":"\/documentation\/talksdk\/talk\/init(zendesk:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"role":"symbol","title":"Talk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"abstract":[{"type":"text","text":"An entry point into Talk SDK for iOS."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"url":"\/documentation\/talksdk\/talk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithZendesk:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithZendesk:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithZendesk:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKZendesk","preciseIdentifier":"c:objc(cs)ZDKZendesk"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"zendesk"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1init(zendesk:)\/title","value":"initWithZendesk:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1init(zendesk:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithZendesk:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","value":"ZDKTalk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}