{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea","text":"DigitalLine"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","preciseIdentifier":"c:@M@TalkSDK@objc(pl)LineStatus","text":"LineStatus"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"digitalLine","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name of digital line configured by the admin in Talk Settings"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"return "},{"type":"codeVoice","code":"Result"},{"type":"text","text":" with "},{"type":"codeVoice","code":"LineStatus"},{"type":"text","text":" for success status or "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" for fail."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information about line status, see the "},{"type":"codeVoice","code":"LineStatus"},{"type":"text","text":" documentation."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talk\/linestatus(digitalline:completion:)-6dnz4"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talk\/linestatus(digitalline:completion:)-6dnz4"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/lineStatus(digitalLine:completion:)-6dnz4","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides asynchronous information about status of line associated with "},{"type":"codeVoice","code":"digitalLine"},{"type":"text","text":" in Talk Settings."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"lineStatusWithDigitalLine:completion:"}],"role":"symbol","title":"lineStatus(digitalLine:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"LineStatus","preciseIdentifier":"c:@M@TalkSDK@objc(pl)LineStatus"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@TalkSDK@objc(cs)ZDKTalk(im)lineStatusWithDigitalLine:completion:","modules":[{"name":"TalkSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/LineStatus":{"role":"symbol","title":"LineStatus","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineStatus"}],"abstract":[{"type":"text","text":"Comprehensive information about status of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineStatus"}],"url":"\/documentation\/talksdk\/linestatus"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"role":"symbol","title":"Talk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"abstract":[{"type":"text","text":"An entry point into Talk SDK for iOS."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"url":"\/documentation\/talksdk\/talk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/DigitalLine":{"role":"symbol","title":"DigitalLine","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalLine"}],"abstract":[{"type":"text","text":"Name of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DigitalLine"}],"url":"\/documentation\/talksdk\/digitalline"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/lineStatus(digitalLine:completion:)-6dnz4":{"role":"symbol","title":"lineStatus(digitalLine:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"LineStatus","preciseIdentifier":"c:@M@TalkSDK@objc(pl)LineStatus"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Provides asynchronous information about status of line associated with "},{"type":"codeVoice","code":"digitalLine"},{"type":"text","text":" in Talk Settings."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/lineStatus(digitalLine:completion:)-6dnz4","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lineStatusWithDigitalLine:completion:"}],"url":"\/documentation\/talksdk\/talk\/linestatus(digitalline:completion:)-6dnz4"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"lineStatusWithDigitalLine:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lineStatusWithDigitalLine:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"lineStatusWithDigitalLine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"digitalLine"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(id<LineStatus>, NSError *)","preciseIdentifier":"c:BFv(#*Qo@M@TalkSDK@objc(pl)LineStatus#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/title","value":"LineStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/fragments","value":[{"kind":"identifier","text":"LineStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","value":"ZDKTalk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1lineStatus(digitalLine:completion:)-6dnz4\/title","value":"lineStatusWithDigitalLine:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1lineStatus(digitalLine:completion:)-6dnz4\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lineStatusWithDigitalLine:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}