{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea","text":"DigitalLine"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","preciseIdentifier":"c:@M@TalkSDK@objc(pl)LineStatus","text":"LineStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AgentStatusError","preciseIdentifier":"s:7TalkSDK16AgentStatusErrorO","text":"AgentStatusError"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"digitalLine","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"name of digital line configured by the admin in Talk Settings"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"return "},{"type":"codeVoice","code":"Result"},{"type":"text","text":" with "},{"type":"codeVoice","code":"LineStatus"},{"type":"text","text":" for success status or "},{"type":"codeVoice","code":"LineStatusError"},{"type":"text","text":" for failure."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information about line status, see the "},{"type":"codeVoice","code":"LineStatus"},{"type":"text","text":" documentation."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talk\/linestatus(digitalline:completion:)-7x9j7"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/lineStatus(digitalLine:completion:)-7x9j7","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provides asynchronous information about the status of a digital line associated with "},{"type":"codeVoice","code":"digitalLine"},{"type":"text","text":" name, as defined in Talk Settings."}],"kind":"symbol","metadata":{"role":"symbol","title":"lineStatus(digitalLine:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"LineStatus","preciseIdentifier":"c:@M@TalkSDK@objc(pl)LineStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AgentStatusError","preciseIdentifier":"s:7TalkSDK16AgentStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:7TalkSDK0A0C10lineStatus11digitalLine10completionySS_ys6ResultOyAA0fD0_pAA05AgentD5ErrorOGctF","extendedModule":"TalkSDK","modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkCoreProvider-Implementations"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"role":"symbol","title":"Talk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"abstract":[{"type":"text","text":"An entry point into Talk SDK for iOS."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"url":"\/documentation\/talksdk\/talk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/TalkCoreProvider-Implementations":{"role":"collectionGroup","title":"TalkCoreProvider Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkCoreProvider-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/talk\/talkcoreprovider-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/LineStatus":{"role":"symbol","title":"LineStatus","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LineStatus"}],"abstract":[{"type":"text","text":"Comprehensive information about status of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/LineStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LineStatus"}],"url":"\/documentation\/talksdk\/linestatus"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/lineStatus(digitalLine:completion:)-7x9j7":{"role":"symbol","title":"lineStatus(digitalLine:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"LineStatus","preciseIdentifier":"c:@M@TalkSDK@objc(pl)LineStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"AgentStatusError","preciseIdentifier":"s:7TalkSDK16AgentStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Provides asynchronous information about the status of a digital line associated with "},{"type":"codeVoice","code":"digitalLine"},{"type":"text","text":" name, as defined in Talk Settings."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/lineStatus(digitalLine:completion:)-7x9j7","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/talk\/linestatus(digitalline:completion:)-7x9j7"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AgentStatusError":{"role":"symbol","title":"AgentStatusError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AgentStatusError"}],"abstract":[{"type":"text","text":"Represents errors occuring during "},{"type":"codeVoice","code":"lineStatus"},{"type":"text","text":" check."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AgentStatusError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AgentStatusError"}],"url":"\/documentation\/talksdk\/agentstatuserror"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/DigitalLine":{"role":"symbol","title":"DigitalLine","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalLine"}],"abstract":[{"type":"text","text":"Name of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DigitalLine"}],"url":"\/documentation\/talksdk\/digitalline"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","value":"ZDKTalk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/title","value":"LineStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1LineStatus\/fragments","value":[{"kind":"identifier","text":"LineStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}