{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCallViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"callData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData","text":"CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callDidFinishHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkScreenProvider\/CallScreenViewController","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP04CallC14ViewControllera","text":"CallScreenViewController"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallSummary","preciseIdentifier":"s:7TalkSDK11CallSummaryP","text":"CallSummary"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkScreenProvider\/CallScreenViewController","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP04CallC14ViewControllera","text":"CallScreenViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"CallScreenViewController"},{"type":"text","text":", which is  a "},{"type":"codeVoice","code":"CallScreen"},{"type":"text","text":" conforming "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":", with all configured UI and logic for making a call."}]}]},{"kind":"parameters","parameters":[{"name":"callData","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data containing all required call parameters such as "},{"type":"codeVoice","code":"DigitaLine"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RecordingConsentAnswer"},{"type":"text","text":"."}]}]},{"name":"callDidFinishHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handler called when the call is finished with "},{"type":"codeVoice","code":"CallScreen"},{"type":"text","text":" and "},{"type":"codeVoice","code":"CallSummary"},{"type":"text","text":" as parameters. Is called for both success and failure scenarios."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Before showing that screen you should check "},{"type":"codeVoice","code":"microphone permission"},{"type":"text","text":", "},{"type":"codeVoice","code":"digital line"},{"type":"text","text":" status, and "},{"type":"codeVoice","code":"recording consent"},{"type":"text","text":" first."},{"type":"text","text":" "},{"type":"text","text":"You can use this provided view controller, with all required logic for making a call."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talk\/makecallviewcontroller(with:calldidfinishhandler:)-8h7uu"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallViewController(with:callDidFinishHandler:)-8h7uu","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns Call View Controller"}],"kind":"symbol","metadata":{"role":"symbol","title":"makeCallViewController(with:callDidFinishHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCallViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callDidFinishHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CallScreenViewController","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP04CallC14ViewControllera"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"CallSummary","preciseIdentifier":"s:7TalkSDK11CallSummaryP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CallScreenViewController","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP04CallC14ViewControllera"}],"symbolKind":"method","externalID":"s:7TalkSDK0A0C22makeCallViewController4with20callDidFinishHandlerAA0D6Screen_So06UIViewF0CXcAA0D4Data_p_yAaG_AIXc_AA0D7Summary_ptctF","extendedModule":"TalkSDK","modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkScreenProvider-Implementations"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallSummary":{"role":"symbol","title":"CallSummary","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallSummary"}],"abstract":[{"type":"text","text":"Represents details of a finished call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallSummary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallSummary"}],"url":"\/documentation\/talksdk\/callsummary"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData":{"role":"symbol","title":"CallData","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallData"}],"abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallData"}],"url":"\/documentation\/talksdk\/calldata"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"role":"symbol","title":"Talk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"abstract":[{"type":"text","text":"An entry point into Talk SDK for iOS."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"url":"\/documentation\/talksdk\/talk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkScreenProvider/CallScreenViewController":{"role":"symbol","title":"TalkScreenProvider.CallScreenViewController","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallScreenViewController"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkScreenProvider\/CallScreenViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallScreenViewController"}],"url":"\/documentation\/talksdk\/talkscreenprovider\/callscreenviewcontroller"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/makeCallViewController(with:callDidFinishHandler:)-8h7uu":{"role":"symbol","title":"makeCallViewController(with:callDidFinishHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCallViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callDidFinishHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CallScreenViewController","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP04CallC14ViewControllera"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"CallSummary","preciseIdentifier":"s:7TalkSDK11CallSummaryP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CallScreenViewController","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP04CallC14ViewControllera"}],"abstract":[{"type":"text","text":"Returns Call View Controller"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallViewController(with:callDidFinishHandler:)-8h7uu","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/talk\/makecallviewcontroller(with:calldidfinishhandler:)-8h7uu"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/TalkScreenProvider-Implementations":{"role":"collectionGroup","title":"TalkScreenProvider Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkScreenProvider-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/talk\/talkscreenprovider-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/title","value":"CallData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/fragments","value":[{"kind":"identifier","text":"CallData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","value":"ZDKTalk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}