{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCallConfigurationViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkScreenProvider\/CallConfigurationScreenViewController","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP017CallConfigurationC14ViewControllera","text":"CallConfigurationScreenViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"CallConfigurationScreenViewController"},{"type":"text","text":", which is a "},{"type":"codeVoice","code":"CallConfigurationScreen"},{"type":"text","text":" conforming "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" with configured components and flow."}]}]},{"kind":"parameters","parameters":[{"name":"digitalLine","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A nickname of a digital line for which the configuration will be displayed."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Before making a call you need to make sure user has granted all required permissions. You can use this provided view controller for checking and asking for the permissions and validating all states."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This view controller won’t start a call as its responsibility is only to handle required permissions. Please provide the handlers for implementing the navigation flow: "},{"type":"codeVoice","code":"cancelHandler"},{"type":"text","text":" for the view controller’s dismissal and "},{"type":"codeVoice","code":"startCallHandler"},{"type":"text","text":" for presenting the call view controller and starting a call."}]}],"type":"aside","name":"Important"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talk\/makecallconfigurationviewcontroller(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talk\/makecallconfigurationviewcontroller(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallConfigurationViewController(for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns Call Configuration view controller"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"makeCallConfigurationViewControllerFor:"}],"role":"symbol","title":"makeCallConfigurationViewController(for:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCallConfigurationViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CallConfigurationScreenViewController","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP017CallConfigurationC14ViewControllera"}],"symbolKind":"method","externalID":"c:@CM@TalkSDK@objc(cs)ZDKTalk(im)makeCallConfigurationViewControllerFor:","extendedModule":"TalkSDK","modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkScreenProvider-Implementations"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/TalkScreenProvider-Implementations":{"role":"collectionGroup","title":"TalkScreenProvider Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/TalkScreenProvider-Implementations","kind":"article","type":"topic","url":"\/documentation\/talksdk\/talk\/talkscreenprovider-implementations"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk/makeCallConfigurationViewController(for:)":{"role":"symbol","title":"makeCallConfigurationViewController(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeCallConfigurationViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CallConfigurationScreenViewController","preciseIdentifier":"s:7TalkSDK0A14ScreenProviderP017CallConfigurationC14ViewControllera"}],"abstract":[{"type":"text","text":"Returns Call Configuration view controller"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk\/makeCallConfigurationViewController(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeCallConfigurationViewControllerFor:"}],"url":"\/documentation\/talksdk\/talk\/makecallconfigurationviewcontroller(for:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkScreenProvider/CallConfigurationScreenViewController":{"role":"symbol","title":"TalkScreenProvider.CallConfigurationScreenViewController","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationScreenViewController"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkScreenProvider\/CallConfigurationScreenViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallConfigurationScreenViewController"}],"url":"\/documentation\/talksdk\/talkscreenprovider\/callconfigurationscreenviewcontroller"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"role":"symbol","title":"Talk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"abstract":[{"type":"text","text":"An entry point into Talk SDK for iOS."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"url":"\/documentation\/talksdk\/talk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"makeCallConfigurationViewControllerFor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeCallConfigurationViewControllerFor:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIViewController<CallConfigurationScreen>","preciseIdentifier":"c:Q$objc(cs)UIViewController@M@TalkSDK@objc(pl)CallConfigurationScreen"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"makeCallConfigurationViewControllerFor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"digitalLine"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1makeCallConfigurationViewController(for:)\/title","value":"makeCallConfigurationViewControllerFor:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk~1makeCallConfigurationViewController(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeCallConfigurationViewControllerFor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","value":"ZDKTalk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}