{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalLineNotFound"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talkcallerror\/digitallinenotfound"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talkcallerror\/digitallinenotfound"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/digitalLineNotFound","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No digital line was found with a provided name."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalLineNotFound"}],"title":"TalkCallError.digitalLineNotFound","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@TalkSDK@E@TalkCallError@TalkCallErrorDigitalLineNotFound","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorDigitalLineNotFound"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError":{"role":"symbol","title":"TalkCallError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCallError"}],"abstract":[{"type":"text","text":"Represents errors occuring for a "},{"type":"codeVoice","code":"failed"},{"type":"text","text":" or "},{"type":"codeVoice","code":"disconnected"},{"type":"text","text":" call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallError"}],"url":"\/documentation\/talksdk\/talkcallerror"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCallError/digitalLineNotFound":{"role":"symbol","title":"TalkCallError.digitalLineNotFound","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalLineNotFound"}],"abstract":[{"type":"text","text":"No digital line was found with a provided name."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCallError\/digitalLineNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCallErrorDigitalLineNotFound"}],"url":"\/documentation\/talksdk\/talkcallerror\/digitallinenotfound"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"TalkCallErrorDigitalLineNotFound"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TalkCallErrorDigitalLineNotFound"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"TalkCallErrorDigitalLineNotFound"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/title","value":"TalkCallError"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError\/fragments","value":[{"kind":"identifier","text":"TalkCallError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1digitalLineNotFound\/title","value":"TalkCallErrorDigitalLineNotFound"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCallError~1digitalLineNotFound\/fragments","value":[{"kind":"identifier","text":"TalkCallErrorDigitalLineNotFound"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}