{"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callLoadingView"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" & "},{"text":"CallLoadingView","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallLoadingView","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/talksdk\/callviewcontroller\/callloadingview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callviewcontroller\/callloadingview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Loading view with activity indicator."}],"metadata":{"roleHeading":"Instance Property","title":"callLoadingView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"callLoadingView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallLoadingView","text":"CallLoadingView","kind":"typeIdentifier"}],"modules":[{"name":"TalkSDK"}],"externalID":"c:@M@TalkSDK@objc(cs)CallViewController(py)callLoadingView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"callLoadingView"}],"symbolKind":"property"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callLoadingView"},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/callLoadingView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callLoadingView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallLoadingView","text":"CallLoadingView","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"callLoadingView","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/callLoadingView","url":"\/documentation\/talksdk\/callviewcontroller\/callloadingview","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Loading view with activity indicator."}],"title":"callLoadingView"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallLoadingView":{"title":"CallLoadingView","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallLoadingView","url":"\/documentation\/talksdk\/callloadingview","navigatorTitle":[{"text":"CallLoadingView","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Represent the loading view with activity indicator on the call screen."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CallLoadingView","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","url":"\/documentation\/talksdk\/callviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}],"kind":"symbol","abstract":[{"text":"A view controller displayed for an ongoing call.","type":"text"}],"role":"symbol","title":"CallViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"callLoadingView","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"callLoadingView"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIView<CallLoadingView>","preciseIdentifier":"c:Q$objc(cs)UIView@M@TalkSDK@objc(pl)CallLoadingView"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"callLoadingView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callLoadingView\/title","value":"callLoadingView"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1callLoadingView\/fragments","value":[{"text":"callLoadingView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView\/title","value":"CallLoadingView"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallLoadingView\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallLoadingView"}]},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/title","op":"replace","value":"CallViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/fragments","value":[{"text":"CallViewController","kind":"identifier"}]}]}]}