{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disconnect"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It is possible to manually disconnect the call from every state of the call. After disconnecting, the "},{"type":"codeVoice","code":"callDidFinishHandler"},{"text":" is called.","type":"text"}]}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController"]]},"abstract":[{"type":"text","text":"Disconnects the call."}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","title":"disconnect()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"disconnect","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"TalkSDK"}],"externalID":"c:@M@TalkSDK@objc(cs)CallViewController(im)disconnect","role":"symbol","navigatorTitle":[{"text":"disconnect","kind":"identifier"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callviewcontroller\/disconnect()"]},{"paths":["\/documentation\/talksdk\/callviewcontroller\/disconnect()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/disconnect()","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","url":"\/documentation\/talksdk\/callviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}],"kind":"symbol","abstract":[{"text":"A view controller displayed for an ongoing call.","type":"text"}],"role":"symbol","title":"CallViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallViewController","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/disconnect()":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnect"},{"text":"()","kind":"text"}],"title":"disconnect()","type":"topic","abstract":[{"type":"text","text":"Disconnects the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/disconnect()","navigatorTitle":[{"text":"disconnect","kind":"identifier"}],"url":"\/documentation\/talksdk\/callviewcontroller\/disconnect()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"disconnect"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"disconnect","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"disconnect","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"CallViewController","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/title"},{"value":[{"text":"CallViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1disconnect()\/title","op":"replace","value":"disconnect"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"disconnect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1disconnect()\/fragments"}]}]}