{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"callData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CallData","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData"},{"text":", ","kind":"text"},{"text":"talk","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(cs)ZDKTalk","text":"Talk","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController"]]},"metadata":{"externalID":"s:7TalkSDK18CallViewControllerC8callData4talkAcA0cG0_p_AA0A0Ctcfc","modules":[{"name":"TalkSDK"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(callData:talk:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callData"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData","text":"CallData"},{"text":", ","kind":"text"},{"text":"talk","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TalkSDK@objc(cs)ZDKTalk","kind":"typeIdentifier","text":"Talk"},{"text":")","kind":"text"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/talksdk\/callviewcontroller\/init(calldata:talk:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/init(callData:talk:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallData":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallData","navigatorTitle":[{"text":"CallData","kind":"identifier"}],"type":"topic","title":"CallData","url":"\/documentation\/talksdk\/calldata","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallData","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents all required parameters to make a call."}],"role":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","url":"\/documentation\/talksdk\/callviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}],"kind":"symbol","abstract":[{"text":"A view controller displayed for an ongoing call.","type":"text"}],"role":"symbol","title":"CallViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallViewController","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"title":"Talk","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","url":"\/documentation\/talksdk\/talk","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"type":"topic","kind":"symbol","abstract":[{"text":"An entry point into Talk SDK for iOS.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Talk","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/init(callData:talk:)":{"kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callviewcontroller\/init(calldata:talk:)","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/init(callData:talk:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callData"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)CallData","kind":"typeIdentifier","text":"CallData"},{"kind":"text","text":", "},{"text":"talk","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(cs)ZDKTalk","text":"Talk"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"title":"init(callData:talk:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/title","value":"CallData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallData\/fragments","value":[{"kind":"identifier","text":"CallData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/title","value":"CallViewController"},{"value":[{"kind":"identifier","text":"CallViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/fragments"},{"value":"ZDKTalk","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}