{"metadata":{"externalID":"c:@CM@TalkSDK@objc(cs)CallViewController(im)routePickerViewWillBeginPresentingRoutes:","navigatorTitle":[{"text":"routePickerViewWillBeginPresentingRoutes:","kind":"identifier"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"routePickerViewWillBeginPresentingRoutes","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AVRoutePickerView","preciseIdentifier":"c:objc(cs)AVRoutePickerView"},{"text":")","kind":"text"}],"modules":[{"name":"TalkSDK"}],"title":"routePickerViewWillBeginPresentingRoutes(_:)"},"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/routePickerViewWillBeginPresentingRoutes(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"routePickerViewWillBeginPresentingRoutes"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"routePickerView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AVRoutePickerView","preciseIdentifier":"c:objc(cs)AVRoutePickerView"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/AVRoutePickerViewDelegate-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AVRoutePickerViewDelegate.routePickerViewWillBeginPresentingRoutes(_:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/talksdk\/callviewcontroller\/routepickerviewwillbeginpresentingroutes(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callviewcontroller\/routepickerviewwillbeginpresentingroutes(_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/routePickerViewWillBeginPresentingRoutes(_:)":{"url":"\/documentation\/talksdk\/callviewcontroller\/routepickerviewwillbeginpresentingroutes(_:)","title":"routePickerViewWillBeginPresentingRoutes(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"routePickerViewWillBeginPresentingRoutes","kind":"identifier"},{"kind":"text","text":"("},{"text":"AVRoutePickerView","preciseIdentifier":"c:objc(cs)AVRoutePickerView","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/routePickerViewWillBeginPresentingRoutes(_:)","navigatorTitle":[{"text":"routePickerViewWillBeginPresentingRoutes:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","url":"\/documentation\/talksdk\/callviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}],"kind":"symbol","abstract":[{"text":"A view controller displayed for an ongoing call.","type":"text"}],"role":"symbol","title":"CallViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallViewController","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/AVRoutePickerViewDelegate-Implementations":{"url":"\/documentation\/talksdk\/callviewcontroller\/avroutepickerviewdelegate-implementations","kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/AVRoutePickerViewDelegate-Implementations","title":"AVRoutePickerViewDelegate Implementations","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"routePickerViewWillBeginPresentingRoutes:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"routePickerViewWillBeginPresentingRoutes:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"routePickerViewWillBeginPresentingRoutes:","kind":"identifier"},{"kind":"text","text":"("},{"text":"AVRoutePickerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVRoutePickerView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"routePickerView"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"routePickerViewWillBeginPresentingRoutes:","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1routePickerViewWillBeginPresentingRoutes(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"routePickerViewWillBeginPresentingRoutes:"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1routePickerViewWillBeginPresentingRoutes(_:)\/fragments","op":"replace"},{"op":"replace","value":"CallViewController","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/title"},{"op":"replace","value":[{"text":"CallViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/fragments"}]}]}