{"kind":"symbol","metadata":{"roleHeading":"Instance Method","title":"routePickerViewDidEndPresentingRoutes(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"routePickerViewDidEndPresentingRoutes"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVRoutePickerView","text":"AVRoutePickerView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"TalkSDK"}],"extendedModule":"TalkSDK","externalID":"c:@CM@TalkSDK@objc(cs)CallViewController(im)routePickerViewDidEndPresentingRoutes:","role":"symbol","navigatorTitle":[{"text":"routePickerViewDidEndPresentingRoutes:","kind":"identifier"}],"symbolKind":"method"},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/routePickerViewDidEndPresentingRoutes(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/AVRoutePickerViewDelegate-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AVRoutePickerViewDelegate.routePickerViewDidEndPresentingRoutes(_:)"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"routePickerViewDidEndPresentingRoutes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"routePickerView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"AVRoutePickerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVRoutePickerView"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callviewcontroller\/routepickerviewdidendpresentingroutes(_:)"]},{"paths":["\/documentation\/talksdk\/callviewcontroller\/routepickerviewdidendpresentingroutes(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/routePickerViewDidEndPresentingRoutes(_:)":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/routePickerViewDidEndPresentingRoutes(_:)","title":"routePickerViewDidEndPresentingRoutes(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"routePickerViewDidEndPresentingRoutes","kind":"identifier"},{"kind":"text","text":"("},{"text":"AVRoutePickerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVRoutePickerView"},{"text":")","kind":"text"}],"url":"\/documentation\/talksdk\/callviewcontroller\/routepickerviewdidendpresentingroutes(_:)","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"routePickerViewDidEndPresentingRoutes:"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController/AVRoutePickerViewDelegate-Implementations":{"url":"\/documentation\/talksdk\/callviewcontroller\/avroutepickerviewdelegate-implementations","kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController\/AVRoutePickerViewDelegate-Implementations","title":"AVRoutePickerViewDelegate Implementations","type":"topic"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallViewController":{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallViewController","url":"\/documentation\/talksdk\/callviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallViewController"}],"kind":"symbol","abstract":[{"text":"A view controller displayed for an ongoing call.","type":"text"}],"role":"symbol","title":"CallViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"routePickerViewDidEndPresentingRoutes:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"routePickerViewDidEndPresentingRoutes:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"routePickerViewDidEndPresentingRoutes:"},{"text":"(","kind":"text"},{"text":"AVRoutePickerView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVRoutePickerView"},{"kind":"text","text":" *) "},{"text":"routePickerView","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"routePickerViewDidEndPresentingRoutes:","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1routePickerViewDidEndPresentingRoutes(_:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"routePickerViewDidEndPresentingRoutes:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController~1routePickerViewDidEndPresentingRoutes(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/title","value":"CallViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallViewController\/fragments","value":[{"text":"CallViewController","kind":"identifier"}]}]}]}