{"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"]]},"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelHandler"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP20CancelRequestHandlera","text":"CancelRequestHandler"},{"kind":"text","text":"?"}],"title":"cancelHandler","role":"symbol","navigatorTitle":[{"text":"cancelHandler","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"TalkSDK"}],"externalID":"c:@M@TalkSDK@objc(cs)CallConfigurationViewController(py)cancelHandler"},"variants":[{"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller\/cancelhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller\/cancelhandler"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cancelHandler","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/CancelRequestHandler","text":"CancelRequestHandler","kind":"typeIdentifier","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP20CancelRequestHandlera"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/cancelHandler","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Handler that is called when end user cancels the configuration at any time."}],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/CancelRequestHandler":{"type":"topic","abstract":[{"type":"text","text":"Handler type which is called when user taps on Cancel button on configuration screen."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/CancelRequestHandler","url":"\/documentation\/talksdk\/callconfigurationscreen\/cancelrequesthandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"CancelRequestHandler","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CancelRequestHandler"}],"title":"CallConfigurationScreen.CancelRequestHandler"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallConfigurationViewController"}],"navigatorTitle":[{"text":"CallConfigurationViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A view controller that is displayed before making a call, used to ask the user about necessary permissions that need to be granted."}],"type":"topic","url":"\/documentation\/talksdk\/callconfigurationviewcontroller","title":"CallConfigurationViewController","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/cancelHandler":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancelHandler","kind":"identifier"},{"kind":"text","text":": "},{"text":"CancelRequestHandler","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP20CancelRequestHandlera","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/cancelHandler","title":"cancelHandler","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/cancelhandler","role":"symbol","navigatorTitle":[{"text":"cancelHandler","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Handler that is called when end user cancels the configuration at any time."}],"kind":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"cancelHandler","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"cancelHandler","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv()","text":"void (^)(void)"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelHandler"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"CallConfigurationViewController","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/title"},{"value":[{"text":"CallConfigurationViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1cancelHandler\/title","value":"cancelHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1cancelHandler\/fragments","value":[{"text":"cancelHandler","kind":"identifier"}]}]}]}