{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"microphoneScreen","kind":"identifier"},{"kind":"text","text":": "},{"text":"MicrophonePermissionScreen","kind":"typeIdentifier","preciseIdentifier":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/microphoneScreen"},"abstract":[{"type":"text","text":"Container for UI elements shown as Microphone permission screen. Enables customization of UI controls such as font, text colors, etc."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller\/microphonescreen"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller\/microphonescreen"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"]]},"kind":"symbol","metadata":{"externalID":"c:@M@TalkSDK@objc(cs)CallConfigurationViewController(py)microphoneScreen","modules":[{"name":"TalkSDK"}],"title":"microphoneScreen","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"microphoneScreen"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"microphoneScreen"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen","kind":"typeIdentifier","text":"MicrophonePermissionScreen"}],"roleHeading":"Instance Property"},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/microphoneScreen":{"title":"microphoneScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/microphoneScreen","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/microphonescreen","navigatorTitle":[{"text":"microphoneScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Container for UI elements shown as Microphone permission screen. Enables customization of UI controls such as font, text colors, etc."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"microphoneScreen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MicrophonePermissionScreen","preciseIdentifier":"c:@M@TalkSDK@objc(pl)MicrophonePermissionScreen"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/MicrophonePermissionScreen":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MicrophonePermissionScreen","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MicrophonePermissionScreen","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/MicrophonePermissionScreen","url":"\/documentation\/talksdk\/microphonepermissionscreen","role":"symbol","title":"MicrophonePermissionScreen","kind":"symbol","abstract":[{"type":"text","text":"Screen handling microphone permission configuration."}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallConfigurationViewController"}],"navigatorTitle":[{"text":"CallConfigurationViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A view controller that is displayed before making a call, used to ask the user about necessary permissions that need to be granted."}],"type":"topic","url":"\/documentation\/talksdk\/callconfigurationviewcontroller","title":"CallConfigurationViewController","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"microphoneScreen","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"microphoneScreen"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@TalkSDK@objc(pl)MicrophonePermissionScreen","kind":"typeIdentifier","text":"id<MicrophonePermissionScreen>"},{"text":" * ","kind":"text"},{"text":"microphoneScreen","kind":"identifier"}]}]}},{"value":"microphoneScreen","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1microphoneScreen\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1microphoneScreen\/fragments","value":[{"text":"microphoneScreen","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/title","value":"MicrophonePermissionScreen"},{"op":"replace","value":[{"kind":"identifier","text":"MicrophonePermissionScreen"}],"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1MicrophonePermissionScreen\/fragments"},{"value":"CallConfigurationViewController","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/fragments","op":"replace","value":[{"text":"CallConfigurationViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}