{"abstract":[{"type":"text","text":"Container for UI elements shown as Recording Consent screen. Enables customization of UI controls such as font, text colors, etc."}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/recordingConsentScreen","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recordingConsentScreen"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen","text":"RecordingConsentScreen","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller\/recordingconsentscreen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller\/recordingconsentscreen"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"]]},"sections":[],"metadata":{"modules":[{"name":"TalkSDK"}],"title":"recordingConsentScreen","externalID":"c:@M@TalkSDK@objc(cs)CallConfigurationViewController(py)recordingConsentScreen","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"recordingConsentScreen"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentScreen"},{"text":": ","kind":"text"},{"text":"RecordingConsentScreen","preciseIdentifier":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentScreen":{"title":"RecordingConsentScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentScreen","url":"\/documentation\/talksdk\/recordingconsentscreen","navigatorTitle":[{"text":"RecordingConsentScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Screen handling recording consent.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RecordingConsentScreen","kind":"identifier"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallConfigurationViewController"}],"navigatorTitle":[{"text":"CallConfigurationViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A view controller that is displayed before making a call, used to ask the user about necessary permissions that need to be granted."}],"type":"topic","url":"\/documentation\/talksdk\/callconfigurationviewcontroller","title":"CallConfigurationViewController","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/recordingConsentScreen":{"title":"recordingConsentScreen","role":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/recordingConsentScreen","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/recordingconsentscreen","navigatorTitle":[{"text":"recordingConsentScreen","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Container for UI elements shown as Recording Consent screen. Enables customization of UI controls such as font, text colors, etc.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordingConsentScreen"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@TalkSDK@objc(pl)RecordingConsentScreen","kind":"typeIdentifier","text":"RecordingConsentScreen"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"recordingConsentScreen"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"recordingConsentScreen","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@TalkSDK@objc(pl)RecordingConsentScreen","text":"id<RecordingConsentScreen>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"recordingConsentScreen"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/title","value":"RecordingConsentScreen","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentScreen\/fragments","value":[{"text":"RecordingConsentScreen","kind":"identifier"}],"op":"replace"},{"value":"CallConfigurationViewController","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallConfigurationViewController"}]},{"value":"recordingConsentScreen","op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1recordingConsentScreen\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1recordingConsentScreen\/fragments","value":[{"kind":"identifier","text":"recordingConsentScreen"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}