{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startCallHandler","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/StartCallHandler-swift.typealias","text":"StartCallHandler","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/startCallHandler"},"metadata":{"externalID":"c:@M@TalkSDK@objc(cs)CallConfigurationViewController(py)startCallHandler","roleHeading":"Instance Property","modules":[{"name":"TalkSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCallHandler"},{"kind":"text","text":": "},{"text":"StartCallHandler","preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"startCallHandler","kind":"identifier"}],"title":"startCallHandler"},"variants":[{"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller\/startcallhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller\/startcallhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Handler called after completing the configuration, it will be called with user’s "},{"type":"codeVoice","code":"RecordingConsentAnswer"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/startCallHandler":{"navigatorTitle":[{"text":"startCallHandler","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/startCallHandler","title":"startCallHandler","role":"symbol","type":"topic","abstract":[{"text":"Handler called after completing the configuration, it will be called with user’s ","type":"text"},{"code":"RecordingConsentAnswer","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/startcallhandler","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startCallHandler"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7TalkSDK23CallConfigurationScreenP05StartC7Handlera","text":"StartCallHandler","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallConfigurationViewController"}],"navigatorTitle":[{"text":"CallConfigurationViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A view controller that is displayed before making a call, used to ask the user about necessary permissions that need to be granted."}],"type":"topic","url":"\/documentation\/talksdk\/callconfigurationviewcontroller","title":"CallConfigurationViewController","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationScreen/StartCallHandler-swift.typealias":{"kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callconfigurationscreen\/startcallhandler-swift.typealias","role":"symbol","title":"CallConfigurationScreen.StartCallHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"StartCallHandler","kind":"identifier"}],"abstract":[{"type":"text","text":"Handler type which is called when all call configuration steps are completed (microphone permission is granted and recording consent configuration is fetched and answered) and call can be made."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationScreen\/StartCallHandler-swift.typealias","navigatorTitle":[{"text":"StartCallHandler","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"startCallHandler","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"startCallHandler","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:BFv(#$@M@TalkSDK@E@RecordingConsentAnswer)","text":"void (^)(enum RecordingConsentAnswer)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"startCallHandler","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1startCallHandler\/title","value":"startCallHandler","op":"replace"},{"value":[{"kind":"identifier","text":"startCallHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController~1startCallHandler\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/title","value":"CallConfigurationViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/fragments","value":[{"text":"CallConfigurationViewController","kind":"identifier"}]}]}]}