{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea","text":"DigitalLine"},{"kind":"text","text":", "},{"kind":"externalParam","text":"talk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","preciseIdentifier":"c:@M@TalkSDK@objc(cs)ZDKTalk","text":"Talk"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callconfigurationviewcontroller\/init(digitalline:talk:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/init(digitalLine:talk:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"talk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Talk","preciseIdentifier":"c:@M@TalkSDK@objc(cs)ZDKTalk"},{"kind":"text","text":")"}],"title":"init(digitalLine:talk:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:7TalkSDK31CallConfigurationViewControllerC11digitalLine4talkACSS_AA0A0Ctcfc","modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController":{"role":"symbol","title":"CallConfigurationViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallConfigurationViewController"}],"abstract":[{"type":"text","text":"A view controller that is displayed before making a call, used to ask the user about necessary permissions that need to be granted."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallConfigurationViewController"}],"url":"\/documentation\/talksdk\/callconfigurationviewcontroller"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallConfigurationViewController/init(digitalLine:talk:)":{"role":"symbol","title":"init(digitalLine:talk:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"digitalLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DigitalLine","preciseIdentifier":"s:7TalkSDK11DigitalLinea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"talk"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Talk","preciseIdentifier":"c:@M@TalkSDK@objc(cs)ZDKTalk"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallConfigurationViewController\/init(digitalLine:talk:)","kind":"symbol","type":"topic","url":"\/documentation\/talksdk\/callconfigurationviewcontroller\/init(digitalline:talk:)"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/Talk":{"role":"symbol","title":"Talk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Talk"}],"abstract":[{"type":"text","text":"An entry point into Talk SDK for iOS."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/Talk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Talk"}],"url":"\/documentation\/talksdk\/talk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/DigitalLine":{"role":"symbol","title":"DigitalLine","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalLine"}],"abstract":[{"type":"text","text":"Name of digital line."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/DigitalLine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DigitalLine"}],"url":"\/documentation\/talksdk\/digitalline"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/title","value":"CallConfigurationViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallConfigurationViewController\/fragments","value":[{"kind":"identifier","text":"CallConfigurationViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/title","value":"ZDKTalk"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1Talk\/fragments","value":[{"kind":"identifier","text":"ZDKTalk"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}