{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bluetooth"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/audioroutingtype\/bluetooth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/audioroutingtype\/bluetooth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/bluetooth","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Used for routing option using bluetooth connectivity."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bluetooth"}],"title":"AudioRoutingType.bluetooth","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@TalkSDK@E@AudioRoutingType@AudioRoutingTypeBluetooth","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AudioRoutingTypeBluetooth"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType":{"role":"symbol","title":"AudioRoutingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioRoutingType"}],"abstract":[{"type":"text","text":"Describes type of an audio routing option."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioRoutingType"}],"url":"\/documentation\/talksdk\/audioroutingtype"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType/bluetooth":{"role":"symbol","title":"AudioRoutingType.bluetooth","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bluetooth"}],"abstract":[{"type":"text","text":"Used for routing option using bluetooth connectivity."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/bluetooth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioRoutingTypeBluetooth"}],"url":"\/documentation\/talksdk\/audioroutingtype\/bluetooth"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AudioRoutingTypeBluetooth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AudioRoutingTypeBluetooth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AudioRoutingTypeBluetooth"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType\/title","value":"AudioRoutingType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType\/fragments","value":[{"kind":"identifier","text":"AudioRoutingType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType~1bluetooth\/title","value":"AudioRoutingTypeBluetooth"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType~1bluetooth\/fragments","value":[{"kind":"identifier","text":"AudioRoutingTypeBluetooth"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}