{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"builtIn"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/audioroutingtype\/builtin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/audioroutingtype\/builtin"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/builtIn","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Used for routing option using built-in speakers and microphone."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"builtIn"}],"title":"AudioRoutingType.builtIn","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@TalkSDK@E@AudioRoutingType@AudioRoutingTypeBuiltIn","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"AudioRoutingTypeBuiltIn"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType":{"role":"symbol","title":"AudioRoutingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioRoutingType"}],"abstract":[{"type":"text","text":"Describes type of an audio routing option."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioRoutingType"}],"url":"\/documentation\/talksdk\/audioroutingtype"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioRoutingType/builtIn":{"role":"symbol","title":"AudioRoutingType.builtIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"builtIn"}],"abstract":[{"type":"text","text":"Used for routing option using built-in speakers and microphone."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioRoutingType\/builtIn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioRoutingTypeBuiltIn"}],"url":"\/documentation\/talksdk\/audioroutingtype\/builtin"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AudioRoutingTypeBuiltIn"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AudioRoutingTypeBuiltIn"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AudioRoutingTypeBuiltIn"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType\/title","value":"AudioRoutingType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType\/fragments","value":[{"kind":"identifier","text":"AudioRoutingType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType~1builtIn\/title","value":"AudioRoutingTypeBuiltIn"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioRoutingType~1builtIn\/fragments","value":[{"kind":"identifier","text":"AudioRoutingTypeBuiltIn"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}