{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnected"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/callstatus\/reconnected"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/callstatus\/reconnected"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/reconnected","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The call has reconnected."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnected"}],"title":"CallStatus.reconnected","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@TalkSDK@E@CallStatus@CallStatusReconnected","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CallStatusReconnected"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus":{"role":"symbol","title":"CallStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallStatus"}],"abstract":[{"type":"text","text":"Represents all possible states of the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatus"}],"url":"\/documentation\/talksdk\/callstatus"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/CallStatus/reconnected":{"role":"symbol","title":"CallStatus.reconnected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnected"}],"abstract":[{"type":"text","text":"The call has reconnected."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/CallStatus\/reconnected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallStatusReconnected"}],"url":"\/documentation\/talksdk\/callstatus\/reconnected"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CallStatusReconnected"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallStatusReconnected"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CallStatusReconnected"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/title","value":"CallStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus\/fragments","value":[{"kind":"identifier","text":"CallStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1reconnected\/title","value":"CallStatusReconnected"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1CallStatus~1reconnected\/fragments","value":[{"kind":"identifier","text":"CallStatusReconnected"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}