{"metadata":{"externalID":"c:@M@TalkSDK@E@RecordingConsentAnswer@RecordingConsentAnswerOptedIn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optedIn"}],"role":"symbol","roleHeading":"Case","title":"RecordingConsentAnswer.optedIn","symbolKind":"case","modules":[{"name":"TalkSDK"}],"navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswerOptedIn"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer"]]},"abstract":[{"type":"text","text":"Even if the default setting is not to record the call, end user opted in for recording the call."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/talksdk\/recordingconsentanswer\/optedin"]},{"paths":["\/documentation\/talksdk\/recordingconsentanswer\/optedin"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optedIn","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/optedIn"},"kind":"symbol","references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer":{"title":"RecordingConsentAnswer","abstract":[{"type":"text","text":"Represents the answer received from end user about recording the call."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecordingConsentAnswer","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer","url":"\/documentation\/talksdk\/recordingconsentanswer","navigatorTitle":[{"kind":"identifier","text":"RecordingConsentAnswer"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","url":"\/documentation\/talksdk","kind":"symbol","title":"TalkSDK"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/RecordingConsentAnswer/optedIn":{"role":"symbol","abstract":[{"text":"Even if the default setting is not to record the call, end user opted in for recording the call.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/RecordingConsentAnswer\/optedIn","url":"\/documentation\/talksdk\/recordingconsentanswer\/optedin","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optedIn","kind":"identifier"}],"type":"topic","title":"RecordingConsentAnswer.optedIn","navigatorTitle":[{"text":"RecordingConsentAnswerOptedIn","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"RecordingConsentAnswerOptedIn"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"RecordingConsentAnswerOptedIn","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"RecordingConsentAnswerOptedIn","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"RecordingConsentAnswer","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/title"},{"path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer\/fragments","op":"replace","value":[{"text":"RecordingConsentAnswer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer~1optedIn\/title","value":"RecordingConsentAnswerOptedIn"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1RecordingConsentAnswer~1optedIn\/fragments","value":[{"kind":"identifier","text":"RecordingConsentAnswerOptedIn"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}