{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput","preciseIdentifier":"c:@M@TalkSDK@E@AudioOutput","text":"AudioOutput"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default value is "},{"type":"codeVoice","code":"AudioOutput.headset"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/talksdk\/talkcall\/audiooutput"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/talksdk\/talkcall\/audiooutput"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/audioOutput","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Device specified audio output."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"audioOutput"}],"role":"symbol","title":"audioOutput","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioOutput","preciseIdentifier":"c:@M@TalkSDK@E@AudioOutput"}],"symbolKind":"property","externalID":"c:@M@TalkSDK@objc(pl)TalkCall(py)audioOutput","required":true,"modules":[{"name":"TalkSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall"]]},"references":{"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall/audioOutput":{"navigatorTitle":[{"kind":"identifier","text":"audioOutput"}],"role":"symbol","title":"audioOutput","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioOutput","preciseIdentifier":"c:@M@TalkSDK@E@AudioOutput"}],"abstract":[{"type":"text","text":"Device specified audio output."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall\/audioOutput","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/talksdk\/talkcall\/audiooutput"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK":{"role":"collection","title":"TalkSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK","kind":"symbol","type":"topic","url":"\/documentation\/talksdk"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/TalkCall":{"role":"symbol","title":"TalkCall","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TalkCall"}],"abstract":[{"type":"text","text":"Represents a call created by Talk SDK."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/TalkCall","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TalkCall"}],"url":"\/documentation\/talksdk\/talkcall"},"doc://com.zendesk.TalkSDK/documentation/TalkSDK/AudioOutput":{"role":"symbol","title":"AudioOutput","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioOutput"}],"abstract":[{"type":"text","text":"Describes possible options for audio playback during the call."}],"identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioOutput"}],"url":"\/documentation\/talksdk\/audiooutput"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"audioOutput"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"audioOutput"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.TalkSDK\/documentation\/TalkSDK\/AudioOutput","preciseIdentifier":"c:@M@TalkSDK@E@AudioOutput","text":"AudioOutput"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioOutput"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1audioOutput\/title","value":"audioOutput"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall~1audioOutput\/fragments","value":[{"kind":"identifier","text":"audioOutput"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/title","value":"TalkCall"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1TalkCall\/fragments","value":[{"kind":"identifier","text":"TalkCall"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput\/title","value":"AudioOutput"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.TalkSDK~1documentation~1TalkSDK~1AudioOutput\/fragments","value":[{"kind":"identifier","text":"AudioOutput"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}